package contract_test

import (
	"os"
	"testing"

	"github.com/pact-foundation/pact-go/v2/models"
	"github.com/pact-foundation/pact-go/v2/provider"
)

func TestBackendSatisfiesFrontendContract(t *testing.T) {
	// This test verifies the backend satisfies the frontend consumer contract.
	// It uses the pact file generated by the frontend consumer tests.
	//
	// Prerequisites:
	// 1. Run frontend consumer tests: cd services/frontend && npm run test:contract
	// 2. Start backend with database: make up (or start postgres + backend manually)
	// 3. Set PACT_PROVIDER_TEST=1 to enable this test
	//
	// Run:
	//   PACT_PROVIDER_TEST=1 go test ./internal/grpc/contract_test/ -v -run TestBackendSatisfiesFrontendContract
	//
	// For CI, use the Pact Broker instead of local files:
	// Set PACT_BROKER_URL, PACT_BROKER_USERNAME, PACT_BROKER_PASSWORD env vars.

	if os.Getenv("PACT_PROVIDER_TEST") == "" {
		t.Skip("Skipping provider verification (set PACT_PROVIDER_TEST=1 to run)")
	}

	verifier := provider.NewVerifier()

	err := verifier.VerifyProvider(t, provider.VerifyRequest{
		ProviderBaseURL: "http://localhost:8080", // Running backend gateway
		Provider:        "LotusBackend",

		// Option A: Verify from local pact files (for local development)
		PactFiles: []string{
			"../../../../frontend/pacts/LotusFrontend-LotusBackend.json",
		},

		// Option B: Verify from broker (for CI) - uncomment and set env vars:
		// BrokerURL:      os.Getenv("PACT_BROKER_URL"),
		// BrokerUsername:  os.Getenv("PACT_BROKER_USERNAME"),
		// BrokerPassword:  os.Getenv("PACT_BROKER_PASSWORD"),
		// PublishVerificationResults: true,
		// ProviderVersion:            os.Getenv("GIT_COMMIT"),

		// State handlers set up test data for each provider state.
		// These are no-ops because the bootstrap SQL (docker/db/01-bootstrap.sql)
		// already seeds the required test data: users, journal entries, and feature flags.
		// If seed data changes, these handlers may need to insert data explicitly.
		// setup=true is called before each interaction, setup=false after (teardown).
		StateHandlers: models.StateHandlers{
			"a user exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"a user has journal entries": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"a user with email exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"no user with this email exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"feature flags exist": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
		},
	})

	if err != nil {
		t.Fatal("Provider verification failed:", err)
	}
}
