package contract_test

import (
	"testing"

	"github.com/pact-foundation/pact-go/v2/models"
	"github.com/pact-foundation/pact-go/v2/provider"
)

func TestBackendSatisfiesFrontendContract(t *testing.T) {
	// This test verifies the backend satisfies the frontend consumer contract.
	// It uses the pact file generated by the frontend consumer tests.
	//
	// To run this test:
	// 1. First run frontend consumer tests: cd services/frontend && npm run test:contract
	// 2. Then run this test with a running backend: go test ./internal/grpc/contract_test/ -v -run TestBackendSatisfiesFrontendContract
	//
	// For CI, use the Pact Broker instead of local files:
	// Set PACT_BROKER_URL, PACT_BROKER_USERNAME, PACT_BROKER_PASSWORD env vars.

	verifier := provider.NewVerifier()

	err := verifier.VerifyProvider(t, provider.VerifyRequest{
		ProviderBaseURL: "http://localhost:8080", // Running backend gateway
		Provider:        "LotusBackend",

		// Option A: Verify from local pact files (for local development)
		PactFiles: []string{
			"../../../../frontend/pacts/LotusFrontend-LotusBackend.json",
		},

		// Option B: Verify from broker (for CI) - uncomment and set env vars:
		// BrokerURL:      os.Getenv("PACT_BROKER_URL"),
		// BrokerUsername:  os.Getenv("PACT_BROKER_USERNAME"),
		// BrokerPassword:  os.Getenv("PACT_BROKER_PASSWORD"),
		// PublishVerificationResults: true,
		// ProviderVersion:            os.Getenv("GIT_COMMIT"),

		// State handlers set up test data for each provider state
		StateHandlers: models.StateHandlers{
			"a user exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				// The bootstrap SQL already seeds test users
				return nil, nil
			},
			"a user has journal entries": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				// The bootstrap SQL already seeds journal entries
				return nil, nil
			},
			"a user with email exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"no user with this email exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"feature flags exist": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
		},
	})

	if err != nil {
		t.Fatal("Provider verification failed:", err)
	}
}
