// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_ml_models.sql

package db

import (
	"context"
)

const getActiveMLModel = `-- name: GetActiveMLModel :one
SELECT is_enabled FROM active_ml_models WHERE ml_model = $1
`

func (q *Queries) GetActiveMLModel(ctx context.Context, mlModel string) (bool, error) {
	row := q.db.QueryRow(ctx, getActiveMLModel, mlModel)
	var is_enabled bool
	err := row.Scan(&is_enabled)
	return is_enabled, err
}
