// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: community.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCommunityMoodRollupsForBucket = `-- name: DeleteCommunityMoodRollupsForBucket :exec
DELETE FROM source.community_mood_rollups
WHERE bucket_date = $1 AND time_grain = $2
`

type DeleteCommunityMoodRollupsForBucketParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
}

func (q *Queries) DeleteCommunityMoodRollupsForBucket(ctx context.Context, arg DeleteCommunityMoodRollupsForBucketParams) error {
	_, err := q.db.Exec(ctx, deleteCommunityMoodRollupsForBucket, arg.BucketDate, arg.TimeGrain)
	return err
}

const deleteCommunityPromptSetsForBucket = `-- name: DeleteCommunityPromptSetsForBucket :exec
DELETE FROM source.community_prompt_sets
WHERE bucket_date = $1 AND time_grain = $2
`

type DeleteCommunityPromptSetsForBucketParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
}

func (q *Queries) DeleteCommunityPromptSetsForBucket(ctx context.Context, arg DeleteCommunityPromptSetsForBucketParams) error {
	_, err := q.db.Exec(ctx, deleteCommunityPromptSetsForBucket, arg.BucketDate, arg.TimeGrain)
	return err
}

const deleteCommunitySummariesForBucket = `-- name: DeleteCommunitySummariesForBucket :exec
DELETE FROM source.community_summaries
WHERE bucket_date = $1 AND time_grain = $2
`

type DeleteCommunitySummariesForBucketParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
}

func (q *Queries) DeleteCommunitySummariesForBucket(ctx context.Context, arg DeleteCommunitySummariesForBucketParams) error {
	_, err := q.db.Exec(ctx, deleteCommunitySummariesForBucket, arg.BucketDate, arg.TimeGrain)
	return err
}

const deleteCommunityThemeRollupsForBucket = `-- name: DeleteCommunityThemeRollupsForBucket :exec
DELETE FROM source.community_theme_rollups
WHERE bucket_date = $1 AND time_grain = $2
`

type DeleteCommunityThemeRollupsForBucketParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
}

func (q *Queries) DeleteCommunityThemeRollupsForBucket(ctx context.Context, arg DeleteCommunityThemeRollupsForBucketParams) error {
	_, err := q.db.Exec(ctx, deleteCommunityThemeRollupsForBucket, arg.BucketDate, arg.TimeGrain)
	return err
}

const getCommunityProjectionSourceByJournalId = `-- name: GetCommunityProjectionSourceByJournalId :one
SELECT
    j.id AS journal_id,
    j.user_id,
    j.created_at,
    j.mood_score,
    u.timezone,
    u.community_insights_opt_in,
    u.community_location_opt_in,
    u.community_country_code,
    u.community_region_code,
    sentiment.sentiment AS primary_sentiment,
    sentiment.ml_model_version AS sentiment_model_version,
    COALESCE(topics.topic_names, ARRAY[]::text[]) AS theme_names,
    topics.topic_model_version
FROM source.journals j
JOIN source.users u ON u.id = j.user_id
LEFT JOIN LATERAL (
    SELECT js.sentiment, js.ml_model_version
    FROM source.journal_sentiments js
    WHERE js.journal_id = j.id AND js.is_reliable = TRUE
    ORDER BY js.created_at DESC, js.id DESC
    LIMIT 1
) sentiment ON TRUE
LEFT JOIN LATERAL (
    SELECT
        ARRAY_AGG(jt.topic_name ORDER BY jt.confidence DESC, jt.topic_name ASC) AS topic_names,
        MAX(jt.ml_model_version) AS topic_model_version
    FROM source.journal_topics jt
    WHERE jt.journal_id = j.id
) topics ON TRUE
WHERE j.id = $1
`

type GetCommunityProjectionSourceByJournalIdRow struct {
	JournalID              int32
	UserID                 pgtype.UUID
	CreatedAt              pgtype.Timestamp
	MoodScore              *int32
	Timezone               string
	CommunityInsightsOptIn bool
	CommunityLocationOptIn bool
	CommunityCountryCode   *string
	CommunityRegionCode    *string
	PrimarySentiment       string
	SentimentModelVersion  string
	ThemeNames             interface{}
	TopicModelVersion      interface{}
}

func (q *Queries) GetCommunityProjectionSourceByJournalId(ctx context.Context, id int32) (GetCommunityProjectionSourceByJournalIdRow, error) {
	row := q.db.QueryRow(ctx, getCommunityProjectionSourceByJournalId, id)
	var i GetCommunityProjectionSourceByJournalIdRow
	err := row.Scan(
		&i.JournalID,
		&i.UserID,
		&i.CreatedAt,
		&i.MoodScore,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
		&i.PrimarySentiment,
		&i.SentimentModelVersion,
		&i.ThemeNames,
		&i.TopicModelVersion,
	)
	return i, err
}

const getCommunityPromptSetByBucketAndScope = `-- name: GetCommunityPromptSetByBucketAndScope :one
SELECT id, bucket_date, time_grain, scope_type, scope_value, prompt_set_json, source_theme_names, source_mood_names, generation_method, updated_at, created_at FROM source.community_prompt_sets
WHERE
    bucket_date = $1
    AND time_grain = $2
    AND scope_type = $3
    AND scope_value = $4
`

type GetCommunityPromptSetByBucketAndScopeParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
	ScopeType  string
	ScopeValue string
}

func (q *Queries) GetCommunityPromptSetByBucketAndScope(ctx context.Context, arg GetCommunityPromptSetByBucketAndScopeParams) (SourceCommunityPromptSet, error) {
	row := q.db.QueryRow(ctx, getCommunityPromptSetByBucketAndScope,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
	)
	var i SourceCommunityPromptSet
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.PromptSetJson,
		&i.SourceThemeNames,
		&i.SourceMoodNames,
		&i.GenerationMethod,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCommunitySummaryByBucketAndScope = `-- name: GetCommunitySummaryByBucketAndScope :one
SELECT id, bucket_date, time_grain, scope_type, scope_value, summary_text, source_theme_names, source_mood_names, generation_method, updated_at, created_at FROM source.community_summaries
WHERE
    bucket_date = $1
    AND time_grain = $2
    AND scope_type = $3
    AND scope_value = $4
`

type GetCommunitySummaryByBucketAndScopeParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
	ScopeType  string
	ScopeValue string
}

func (q *Queries) GetCommunitySummaryByBucketAndScope(ctx context.Context, arg GetCommunitySummaryByBucketAndScopeParams) (SourceCommunitySummary, error) {
	row := q.db.QueryRow(ctx, getCommunitySummaryByBucketAndScope,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
	)
	var i SourceCommunitySummary
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.SummaryText,
		&i.SourceThemeNames,
		&i.SourceMoodNames,
		&i.GenerationMethod,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalCommunityProjectionByJournalId = `-- name: GetJournalCommunityProjectionByJournalId :one
SELECT journal_id, user_id, eligible_for_community, entry_local_date, primary_mood, primary_sentiment, theme_names, country_code, region_code, analysis_version, updated_at, created_at FROM source.journal_community_projections
WHERE journal_id = $1
`

func (q *Queries) GetJournalCommunityProjectionByJournalId(ctx context.Context, journalID int32) (SourceJournalCommunityProjection, error) {
	row := q.db.QueryRow(ctx, getJournalCommunityProjectionByJournalId, journalID)
	var i SourceJournalCommunityProjection
	err := row.Scan(
		&i.JournalID,
		&i.UserID,
		&i.EligibleForCommunity,
		&i.EntryLocalDate,
		&i.PrimaryMood,
		&i.PrimarySentiment,
		&i.ThemeNames,
		&i.CountryCode,
		&i.RegionCode,
		&i.AnalysisVersion,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMoodRollupsByBucketAndScope = `-- name: GetMoodRollupsByBucketAndScope :many
SELECT id, bucket_date, time_grain, scope_type, scope_value, mood_name, entry_count, unique_user_count, rank, delta_vs_previous, updated_at FROM source.community_mood_rollups
WHERE
    bucket_date = $1
    AND time_grain = $2
    AND scope_type = $3
    AND scope_value = $4
ORDER BY rank ASC, mood_name ASC
`

type GetMoodRollupsByBucketAndScopeParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
	ScopeType  string
	ScopeValue string
}

func (q *Queries) GetMoodRollupsByBucketAndScope(ctx context.Context, arg GetMoodRollupsByBucketAndScopeParams) ([]SourceCommunityMoodRollup, error) {
	rows, err := q.db.Query(ctx, getMoodRollupsByBucketAndScope,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceCommunityMoodRollup
	for rows.Next() {
		var i SourceCommunityMoodRollup
		if err := rows.Scan(
			&i.ID,
			&i.BucketDate,
			&i.TimeGrain,
			&i.ScopeType,
			&i.ScopeValue,
			&i.MoodName,
			&i.EntryCount,
			&i.UniqueUserCount,
			&i.Rank,
			&i.DeltaVsPrevious,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThemeRollupsByBucketAndScope = `-- name: GetThemeRollupsByBucketAndScope :many
SELECT id, bucket_date, time_grain, scope_type, scope_value, theme_name, entry_count, unique_user_count, rank, delta_vs_previous, updated_at FROM source.community_theme_rollups
WHERE
    bucket_date = $1
    AND time_grain = $2
    AND scope_type = $3
    AND scope_value = $4
ORDER BY rank ASC, theme_name ASC
`

type GetThemeRollupsByBucketAndScopeParams struct {
	BucketDate pgtype.Date
	TimeGrain  string
	ScopeType  string
	ScopeValue string
}

func (q *Queries) GetThemeRollupsByBucketAndScope(ctx context.Context, arg GetThemeRollupsByBucketAndScopeParams) ([]SourceCommunityThemeRollup, error) {
	rows, err := q.db.Query(ctx, getThemeRollupsByBucketAndScope,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceCommunityThemeRollup
	for rows.Next() {
		var i SourceCommunityThemeRollup
		if err := rows.Scan(
			&i.ID,
			&i.BucketDate,
			&i.TimeGrain,
			&i.ScopeType,
			&i.ScopeValue,
			&i.ThemeName,
			&i.EntryCount,
			&i.UniqueUserCount,
			&i.Rank,
			&i.DeltaVsPrevious,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityRepairJournalIds = `-- name: ListCommunityRepairJournalIds :many
SELECT DISTINCT j.id
FROM source.journals j
JOIN source.users u ON u.id = j.user_id
WHERE
    j.created_at >= $1
    OR j.modified_at >= $1
    OR u.modified_at >= $1
ORDER BY j.id
`

func (q *Queries) ListCommunityRepairJournalIds(ctx context.Context, createdAt pgtype.Timestamp) ([]int32, error) {
	rows, err := q.db.Query(ctx, listCommunityRepairJournalIds, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleCommunityProjectionsByDateRange = `-- name: ListEligibleCommunityProjectionsByDateRange :many
SELECT journal_id, user_id, eligible_for_community, entry_local_date, primary_mood, primary_sentiment, theme_names, country_code, region_code, analysis_version, updated_at, created_at
FROM source.journal_community_projections
WHERE eligible_for_community = TRUE
  AND entry_local_date >= $1
  AND entry_local_date <= $2
ORDER BY entry_local_date, journal_id
`

type ListEligibleCommunityProjectionsByDateRangeParams struct {
	EntryLocalDate   pgtype.Date
	EntryLocalDate_2 pgtype.Date
}

func (q *Queries) ListEligibleCommunityProjectionsByDateRange(ctx context.Context, arg ListEligibleCommunityProjectionsByDateRangeParams) ([]SourceJournalCommunityProjection, error) {
	rows, err := q.db.Query(ctx, listEligibleCommunityProjectionsByDateRange, arg.EntryLocalDate, arg.EntryLocalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceJournalCommunityProjection
	for rows.Next() {
		var i SourceJournalCommunityProjection
		if err := rows.Scan(
			&i.JournalID,
			&i.UserID,
			&i.EligibleForCommunity,
			&i.EntryLocalDate,
			&i.PrimaryMood,
			&i.PrimarySentiment,
			&i.ThemeNames,
			&i.CountryCode,
			&i.RegionCode,
			&i.AnalysisVersion,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommunityMoodRollup = `-- name: UpsertCommunityMoodRollup :one
INSERT INTO source.community_mood_rollups (
    bucket_date,
    time_grain,
    scope_type,
    scope_value,
    mood_name,
    entry_count,
    unique_user_count,
    rank,
    delta_vs_previous
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (bucket_date, time_grain, scope_type, scope_value, mood_name) DO UPDATE
SET
    entry_count = EXCLUDED.entry_count,
    unique_user_count = EXCLUDED.unique_user_count,
    rank = EXCLUDED.rank,
    delta_vs_previous = EXCLUDED.delta_vs_previous,
    updated_at = NOW()
RETURNING id, bucket_date, time_grain, scope_type, scope_value, mood_name, entry_count, unique_user_count, rank, delta_vs_previous, updated_at
`

type UpsertCommunityMoodRollupParams struct {
	BucketDate      pgtype.Date
	TimeGrain       string
	ScopeType       string
	ScopeValue      string
	MoodName        string
	EntryCount      int32
	UniqueUserCount int32
	Rank            int32
	DeltaVsPrevious pgtype.Numeric
}

func (q *Queries) UpsertCommunityMoodRollup(ctx context.Context, arg UpsertCommunityMoodRollupParams) (SourceCommunityMoodRollup, error) {
	row := q.db.QueryRow(ctx, upsertCommunityMoodRollup,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
		arg.MoodName,
		arg.EntryCount,
		arg.UniqueUserCount,
		arg.Rank,
		arg.DeltaVsPrevious,
	)
	var i SourceCommunityMoodRollup
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.MoodName,
		&i.EntryCount,
		&i.UniqueUserCount,
		&i.Rank,
		&i.DeltaVsPrevious,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCommunityPromptSet = `-- name: UpsertCommunityPromptSet :one
INSERT INTO source.community_prompt_sets (
    bucket_date,
    time_grain,
    scope_type,
    scope_value,
    prompt_set_json,
    source_theme_names,
    source_mood_names,
    generation_method
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (bucket_date, time_grain, scope_type, scope_value) DO UPDATE
SET
    prompt_set_json = EXCLUDED.prompt_set_json,
    source_theme_names = EXCLUDED.source_theme_names,
    source_mood_names = EXCLUDED.source_mood_names,
    generation_method = EXCLUDED.generation_method,
    updated_at = NOW()
RETURNING id, bucket_date, time_grain, scope_type, scope_value, prompt_set_json, source_theme_names, source_mood_names, generation_method, updated_at, created_at
`

type UpsertCommunityPromptSetParams struct {
	BucketDate       pgtype.Date
	TimeGrain        string
	ScopeType        string
	ScopeValue       string
	PromptSetJson    []byte
	SourceThemeNames []string
	SourceMoodNames  []string
	GenerationMethod string
}

func (q *Queries) UpsertCommunityPromptSet(ctx context.Context, arg UpsertCommunityPromptSetParams) (SourceCommunityPromptSet, error) {
	row := q.db.QueryRow(ctx, upsertCommunityPromptSet,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
		arg.PromptSetJson,
		arg.SourceThemeNames,
		arg.SourceMoodNames,
		arg.GenerationMethod,
	)
	var i SourceCommunityPromptSet
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.PromptSetJson,
		&i.SourceThemeNames,
		&i.SourceMoodNames,
		&i.GenerationMethod,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCommunitySummary = `-- name: UpsertCommunitySummary :one
INSERT INTO source.community_summaries (
    bucket_date,
    time_grain,
    scope_type,
    scope_value,
    summary_text,
    source_theme_names,
    source_mood_names,
    generation_method
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (bucket_date, time_grain, scope_type, scope_value) DO UPDATE
SET
    summary_text = EXCLUDED.summary_text,
    source_theme_names = EXCLUDED.source_theme_names,
    source_mood_names = EXCLUDED.source_mood_names,
    generation_method = EXCLUDED.generation_method,
    updated_at = NOW()
RETURNING id, bucket_date, time_grain, scope_type, scope_value, summary_text, source_theme_names, source_mood_names, generation_method, updated_at, created_at
`

type UpsertCommunitySummaryParams struct {
	BucketDate       pgtype.Date
	TimeGrain        string
	ScopeType        string
	ScopeValue       string
	SummaryText      string
	SourceThemeNames []string
	SourceMoodNames  []string
	GenerationMethod string
}

func (q *Queries) UpsertCommunitySummary(ctx context.Context, arg UpsertCommunitySummaryParams) (SourceCommunitySummary, error) {
	row := q.db.QueryRow(ctx, upsertCommunitySummary,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
		arg.SummaryText,
		arg.SourceThemeNames,
		arg.SourceMoodNames,
		arg.GenerationMethod,
	)
	var i SourceCommunitySummary
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.SummaryText,
		&i.SourceThemeNames,
		&i.SourceMoodNames,
		&i.GenerationMethod,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCommunityThemeRollup = `-- name: UpsertCommunityThemeRollup :one
INSERT INTO source.community_theme_rollups (
    bucket_date,
    time_grain,
    scope_type,
    scope_value,
    theme_name,
    entry_count,
    unique_user_count,
    rank,
    delta_vs_previous
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (bucket_date, time_grain, scope_type, scope_value, theme_name) DO UPDATE
SET
    entry_count = EXCLUDED.entry_count,
    unique_user_count = EXCLUDED.unique_user_count,
    rank = EXCLUDED.rank,
    delta_vs_previous = EXCLUDED.delta_vs_previous,
    updated_at = NOW()
RETURNING id, bucket_date, time_grain, scope_type, scope_value, theme_name, entry_count, unique_user_count, rank, delta_vs_previous, updated_at
`

type UpsertCommunityThemeRollupParams struct {
	BucketDate      pgtype.Date
	TimeGrain       string
	ScopeType       string
	ScopeValue      string
	ThemeName       string
	EntryCount      int32
	UniqueUserCount int32
	Rank            int32
	DeltaVsPrevious pgtype.Numeric
}

func (q *Queries) UpsertCommunityThemeRollup(ctx context.Context, arg UpsertCommunityThemeRollupParams) (SourceCommunityThemeRollup, error) {
	row := q.db.QueryRow(ctx, upsertCommunityThemeRollup,
		arg.BucketDate,
		arg.TimeGrain,
		arg.ScopeType,
		arg.ScopeValue,
		arg.ThemeName,
		arg.EntryCount,
		arg.UniqueUserCount,
		arg.Rank,
		arg.DeltaVsPrevious,
	)
	var i SourceCommunityThemeRollup
	err := row.Scan(
		&i.ID,
		&i.BucketDate,
		&i.TimeGrain,
		&i.ScopeType,
		&i.ScopeValue,
		&i.ThemeName,
		&i.EntryCount,
		&i.UniqueUserCount,
		&i.Rank,
		&i.DeltaVsPrevious,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJournalCommunityProjection = `-- name: UpsertJournalCommunityProjection :one
INSERT INTO source.journal_community_projections (
    journal_id,
    user_id,
    eligible_for_community,
    entry_local_date,
    primary_mood,
    primary_sentiment,
    theme_names,
    country_code,
    region_code,
    analysis_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (journal_id) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    eligible_for_community = EXCLUDED.eligible_for_community,
    entry_local_date = EXCLUDED.entry_local_date,
    primary_mood = EXCLUDED.primary_mood,
    primary_sentiment = EXCLUDED.primary_sentiment,
    theme_names = EXCLUDED.theme_names,
    country_code = EXCLUDED.country_code,
    region_code = EXCLUDED.region_code,
    analysis_version = EXCLUDED.analysis_version,
    updated_at = NOW()
RETURNING journal_id, user_id, eligible_for_community, entry_local_date, primary_mood, primary_sentiment, theme_names, country_code, region_code, analysis_version, updated_at, created_at
`

type UpsertJournalCommunityProjectionParams struct {
	JournalID            int32
	UserID               pgtype.UUID
	EligibleForCommunity bool
	EntryLocalDate       pgtype.Date
	PrimaryMood          *string
	PrimarySentiment     *string
	ThemeNames           []string
	CountryCode          *string
	RegionCode           *string
	AnalysisVersion      string
}

func (q *Queries) UpsertJournalCommunityProjection(ctx context.Context, arg UpsertJournalCommunityProjectionParams) (SourceJournalCommunityProjection, error) {
	row := q.db.QueryRow(ctx, upsertJournalCommunityProjection,
		arg.JournalID,
		arg.UserID,
		arg.EligibleForCommunity,
		arg.EntryLocalDate,
		arg.PrimaryMood,
		arg.PrimarySentiment,
		arg.ThemeNames,
		arg.CountryCode,
		arg.RegionCode,
		arg.AnalysisVersion,
	)
	var i SourceJournalCommunityProjection
	err := row.Scan(
		&i.JournalID,
		&i.UserID,
		&i.EligibleForCommunity,
		&i.EntryLocalDate,
		&i.PrimaryMood,
		&i.PrimarySentiment,
		&i.ThemeNames,
		&i.CountryCode,
		&i.RegionCode,
		&i.AnalysisVersion,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
