// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feature_flags.sql

package db

import (
	"context"
)

const getActiveFeatureFlags = `-- name: GetActiveFeatureFlags :many
SELECT id, name, everyone, percent, testing, superusers, staff, authenticated, languages, rollout, note, created, modified FROM source.waffle_flag
`

func (q *Queries) GetActiveFeatureFlags(ctx context.Context) ([]SourceWaffleFlag, error) {
	rows, err := q.db.Query(ctx, getActiveFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceWaffleFlag
	for rows.Next() {
		var i SourceWaffleFlag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Everyone,
			&i.Percent,
			&i.Testing,
			&i.Superusers,
			&i.Staff,
			&i.Authenticated,
			&i.Languages,
			&i.Rollout,
			&i.Note,
			&i.Created,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeatureFlagByName = `-- name: GetFeatureFlagByName :one
SELECT id, name, everyone, percent, testing, superusers, staff, authenticated, languages, rollout, note, created, modified FROM source.waffle_flag WHERE name = $1
`

func (q *Queries) GetFeatureFlagByName(ctx context.Context, name string) (SourceWaffleFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagByName, name)
	var i SourceWaffleFlag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Everyone,
		&i.Percent,
		&i.Testing,
		&i.Superusers,
		&i.Staff,
		&i.Authenticated,
		&i.Languages,
		&i.Rollout,
		&i.Note,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
