// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_exports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalExport = `-- name: CreateJournalExport :one
INSERT INTO source.journal_exports (user_id, format, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, format, status, content, error_msg, created_at, completed_at
`

type CreateJournalExportParams struct {
	UserID pgtype.UUID
	Format SourceExportFormat
}

func (q *Queries) CreateJournalExport(ctx context.Context, arg CreateJournalExportParams) (SourceJournalExport, error) {
	row := q.db.QueryRow(ctx, createJournalExport, arg.UserID, arg.Format)
	var i SourceJournalExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJournalExport = `-- name: GetJournalExport :one
SELECT id, user_id, format, status, content, error_msg, created_at, completed_at FROM source.journal_exports
WHERE id = $1 AND user_id = $2
`

type GetJournalExportParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetJournalExport(ctx context.Context, arg GetJournalExportParams) (SourceJournalExport, error) {
	row := q.db.QueryRow(ctx, getJournalExport, arg.ID, arg.UserID)
	var i SourceJournalExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJournalExportComplete = `-- name: UpdateJournalExportComplete :one
UPDATE source.journal_exports
SET status       = 'complete',
    content      = $2,
    completed_at = now()
WHERE id = $1
RETURNING id, user_id, format, status, content, error_msg, created_at, completed_at
`

type UpdateJournalExportCompleteParams struct {
	ID      pgtype.UUID
	Content *string
}

func (q *Queries) UpdateJournalExportComplete(ctx context.Context, arg UpdateJournalExportCompleteParams) (SourceJournalExport, error) {
	row := q.db.QueryRow(ctx, updateJournalExportComplete, arg.ID, arg.Content)
	var i SourceJournalExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJournalExportFailed = `-- name: UpdateJournalExportFailed :one
UPDATE source.journal_exports
SET status    = 'failed',
    error_msg = $2
WHERE id = $1
RETURNING id, user_id, format, status, content, error_msg, created_at, completed_at
`

type UpdateJournalExportFailedParams struct {
	ID       pgtype.UUID
	ErrorMsg *string
}

func (q *Queries) UpdateJournalExportFailed(ctx context.Context, arg UpdateJournalExportFailedParams) (SourceJournalExport, error) {
	row := q.db.QueryRow(ctx, updateJournalExportFailed, arg.ID, arg.ErrorMsg)
	var i SourceJournalExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJournalExportProcessing = `-- name: UpdateJournalExportProcessing :one
UPDATE source.journal_exports
SET status = 'processing'
WHERE id = $1
RETURNING id, user_id, format, status, content, error_msg, created_at, completed_at
`

func (q *Queries) UpdateJournalExportProcessing(ctx context.Context, id pgtype.UUID) (SourceJournalExport, error) {
	row := q.db.QueryRow(ctx, updateJournalExportProcessing, id)
	var i SourceJournalExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
