// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_topics.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getTopicsByJournalIds = `-- name: GetTopicsByJournalIds :many
SELECT journal_id, topic_name
FROM source.journal_topics
WHERE journal_id = ANY($1::int[])
ORDER BY journal_id, confidence DESC
`

type GetTopicsByJournalIdsRow struct {
	JournalID int32
	TopicName string
}

func (q *Queries) GetTopicsByJournalIds(ctx context.Context, dollar_1 []int32) ([]GetTopicsByJournalIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopicsByJournalIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopicsByJournalIdsRow
	for rows.Next() {
		var i GetTopicsByJournalIdsRow
		if err := rows.Scan(&i.JournalID, &i.TopicName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
