// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActiveMlModel struct {
	ID         int32
	MlModel    string
	IsEnabled  bool
	CreatedAt  time.Time
	ModifiedAt time.Time
}

type GoldUserJournalSummary struct {
	UserID                         uuid.UUID
	UserEmail                      sql.NullString
	UserRole                       sql.NullString
	UserTimezone                   sql.NullString
	UserCreatedAt                  sql.NullTime
	TotalJournals                  int32
	ActiveDays                     int32
	AvgMoodScore                   sql.NullString
	MinMoodScore                   sql.NullInt32
	MaxMoodScore                   sql.NullInt32
	MoodScoreStddev                sql.NullString
	PositiveEntries                int32
	NegativeEntries                int32
	NeutralEntries                 int32
	AvgSentimentScore              sql.NullString
	AvgJournalLength               sql.NullString
	FirstJournalAt                 sql.NullTime
	LastJournalAt                  sql.NullTime
	LastModifiedAt                 sql.NullTime
	TotalJournals30d               int32
	AvgMoodScore30d                sql.NullString
	MinMoodScore30d                sql.NullInt32
	MaxMoodScore30d                sql.NullInt32
	DailyStreak                    int32
	PositivePercentage             sql.NullString
	DaysSinceLastJournal           sql.NullInt32
	DaysBetweenFirstAndLastJournal sql.NullInt32
	JournalsPerActiveDay           sql.NullString
}

type SourceJournal struct {
	ID          int32
	UserID      uuid.UUID
	JournalText string
	MoodScore   sql.NullInt32
	CreatedAt   time.Time
	ModifiedAt  time.Time
}

type SourceJournalDetail struct {
	JournalID      int32
	SentimentScore sql.NullFloat64
	MoodLabel      sql.NullString
	Keywords       []string
	CreatedAt      time.Time
	ModifiedAt     time.Time
}

type SourceJournalSentiment struct {
	ID              int32
	JournalID       sql.NullInt32
	Sentiment       string
	Confidence      string
	ConfidenceLevel string
	IsReliable      bool
	MlModelVersion  string
	CreatedAt       sql.NullTime
	AllScores       pqtype.NullRawMessage
}

type SourceJournalTopic struct {
	ID             int32
	JournalID      int32
	TopicName      string
	Confidence     string
	MlModelVersion string
	CreatedAt      sql.NullTime
}

type SourceRuntimeConfig struct {
	ID          int32
	Key         string
	Value       json.RawMessage
	Service     string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
}

type SourceUser struct {
	ID            uuid.UUID
	Email         string
	Password      sql.NullString
	Salt          sql.NullString
	OauthProvider sql.NullString
	Role          string
	CreatedAt     time.Time
	ModifiedAt    time.Time
	Timezone      string
}

type SourceUserGameBalance struct {
	ID         int32
	UserID     uuid.UUID
	Balance    int32
	CreatedAt  time.Time
	ModifiedAt time.Time
}

type SourceUserGameBet struct {
	ID         int32
	UserID     uuid.UUID
	Zone       string
	Amount     int32
	RollResult int32
	Payout     int32
	CreatedAt  time.Time
}

type SourceWaffleFlag struct {
	ID            int32
	Name          string
	Everyone      sql.NullBool
	Percent       sql.NullString
	Testing       bool
	Superusers    bool
	Staff         bool
	Authenticated bool
	Languages     string
	Rollout       bool
	Note          string
	Created       time.Time
	Modified      time.Time
}
