// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GoldUserJournalSummary struct {
	UserID                         uuid.UUID
	UserEmail                      sql.NullString
	UserRole                       sql.NullString
	UserTimezone                   sql.NullString
	UserCreatedAt                  sql.NullTime
	TotalJournals                  int32
	ActiveDays                     int32
	AvgMoodScore                   sql.NullString
	MinMoodScore                   sql.NullInt32
	MaxMoodScore                   sql.NullInt32
	MoodScoreStddev                sql.NullString
	PositiveEntries                int32
	NegativeEntries                int32
	NeutralEntries                 int32
	AvgSentimentScore              sql.NullString
	AvgJournalLength               sql.NullString
	FirstJournalAt                 sql.NullTime
	LastJournalAt                  sql.NullTime
	LastModifiedAt                 sql.NullTime
	TotalJournals30d               int32
	AvgMoodScore30d                sql.NullString
	MinMoodScore30d                sql.NullInt32
	MaxMoodScore30d                sql.NullInt32
	DailyStreak                    int32
	PositivePercentage             sql.NullString
	DaysSinceLastJournal           sql.NullInt32
	DaysBetweenFirstAndLastJournal sql.NullInt32
	JournalsPerActiveDay           sql.NullString
}

type SourceJournal struct {
	ID          int32
	UserID      uuid.UUID
	JournalText string
	MoodScore   sql.NullInt32
	CreatedAt   time.Time
	ModifiedAt  time.Time
}

type SourceUser struct {
	ID            uuid.UUID
	Email         string
	Password      sql.NullString
	Salt          sql.NullString
	OauthProvider sql.NullString
	Role          string
	CreatedAt     time.Time
	ModifiedAt    time.Time
	Timezone      string
}
