// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateJournal(ctx context.Context, arg CreateJournalParams) (SourceJournal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (SourceUser, error)
	CreateUserOauth(ctx context.Context, arg CreateUserOauthParams) (SourceUser, error)
	GetJournalById(ctx context.Context, id int32) (SourceJournal, error)
	GetJournalCountByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	GetJournalsByUserId(ctx context.Context, userID uuid.UUID) ([]SourceJournal, error)
	GetJournalsByUserIdPaginated(ctx context.Context, arg GetJournalsByUserIdPaginatedParams) ([]SourceJournal, error)
	GetUserByEmail(ctx context.Context, email string) (SourceUser, error)
	GetUserById(ctx context.Context, id uuid.UUID) (SourceUser, error)
	GetUserJournalSummaryByUserId(ctx context.Context, userID uuid.UUID) (GoldUserJournalSummary, error)
}

var _ Querier = (*Queries)(nil)
