// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateJournal(ctx context.Context, arg CreateJournalParams) (SourceJournal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (SourceUser, error)
	CreateUserOauth(ctx context.Context, arg CreateUserOauthParams) (SourceUser, error)
	GetActiveFeatureFlags(ctx context.Context) ([]SourceWaffleFlag, error)
	GetActiveMLModel(ctx context.Context, mlModel string) (bool, error)
	GetFeatureFlagByName(ctx context.Context, name string) (SourceWaffleFlag, error)
	GetJournalById(ctx context.Context, id int32) (SourceJournal, error)
	GetJournalCountByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	GetJournalsByUserId(ctx context.Context, userID uuid.UUID) ([]SourceJournal, error)
	GetJournalsByUserIdPaginated(ctx context.Context, arg GetJournalsByUserIdPaginatedParams) ([]SourceJournal, error)
	GetRuntimeConfigByKey(ctx context.Context, key string) (SourceRuntimeConfig, error)
	GetTopicsByJournalIds(ctx context.Context, dollar_1 []int32) ([]GetTopicsByJournalIdsRow, error)
	GetUserByEmail(ctx context.Context, email string) (SourceUser, error)
	GetUserById(ctx context.Context, id uuid.UUID) (SourceUser, error)
	GetUserGameBalance(ctx context.Context, userID uuid.UUID) (SourceUserGameBalance, error)
	GetUserGameBets(ctx context.Context, arg GetUserGameBetsParams) ([]SourceUserGameBet, error)
	GetUserJournalSummaryByUserId(ctx context.Context, userID uuid.UUID) (GoldUserJournalSummary, error)
	InsertUserGameBet(ctx context.Context, arg InsertUserGameBetParams) (SourceUserGameBet, error)
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (SourceUser, error)
	UpsertRuntimeConfigValue(ctx context.Context, arg UpsertRuntimeConfigValueParams) (SourceRuntimeConfig, error)
	UpsertUserGameBalance(ctx context.Context, arg UpsertUserGameBalanceParams) (SourceUserGameBalance, error)
}

var _ Querier = (*Queries)(nil)
