// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_config.sql

package db

import (
	"context"
	"encoding/json"
)

const getRuntimeConfigByKey = `-- name: GetRuntimeConfigByKey :one
SELECT id, key, value, service, description, created_at, modified_at FROM source.runtime_config WHERE key = $1
`

func (q *Queries) GetRuntimeConfigByKey(ctx context.Context, key string) (SourceRuntimeConfig, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeConfigByKey, key)
	var i SourceRuntimeConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Service,
		&i.Description,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const upsertRuntimeConfigValue = `-- name: UpsertRuntimeConfigValue :one
INSERT INTO source.runtime_config (key, value, service, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key)
DO UPDATE SET value = $2, modified_at = NOW()
RETURNING id, key, value, service, description, created_at, modified_at
`

type UpsertRuntimeConfigValueParams struct {
	Key         string
	Value       json.RawMessage
	Service     string
	Description string
}

func (q *Queries) UpsertRuntimeConfigValue(ctx context.Context, arg UpsertRuntimeConfigValueParams) (SourceRuntimeConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertRuntimeConfigValue,
		arg.Key,
		arg.Value,
		arg.Service,
		arg.Description,
	)
	var i SourceRuntimeConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Service,
		&i.Description,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
