// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_game_balance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserGameBalance = `-- name: GetUserGameBalance :one
SELECT id, user_id, balance, created_at, modified_at FROM source.user_game_balances WHERE user_id = $1
`

func (q *Queries) GetUserGameBalance(ctx context.Context, userID uuid.UUID) (SourceUserGameBalance, error) {
	row := q.db.QueryRowContext(ctx, getUserGameBalance, userID)
	var i SourceUserGameBalance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const upsertUserGameBalance = `-- name: UpsertUserGameBalance :one
INSERT INTO source.user_game_balances (user_id, balance)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
    SET balance     = EXCLUDED.balance,
        modified_at = NOW()
RETURNING id, user_id, balance, created_at, modified_at
`

type UpsertUserGameBalanceParams struct {
	UserID  uuid.UUID
	Balance int32
}

func (q *Queries) UpsertUserGameBalance(ctx context.Context, arg UpsertUserGameBalanceParams) (SourceUserGameBalance, error) {
	row := q.db.QueryRowContext(ctx, upsertUserGameBalance, arg.UserID, arg.Balance)
	var i SourceUserGameBalance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
