// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO source.users(email, password, salt)
VALUES ($1, $2, $3)
RETURNING id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code
`

type CreateUserParams struct {
	Email    string
	Password *string
	Salt     *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (SourceUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Salt)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}

const createUserOauth = `-- name: CreateUserOauth :one
INSERT INTO source.users(email, oauth_provider)
VALUES ($1, $2)
RETURNING id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code
`

type CreateUserOauthParams struct {
	Email         string
	OauthProvider *string
}

func (q *Queries) CreateUserOauth(ctx context.Context, arg CreateUserOauthParams) (SourceUser, error) {
	row := q.db.QueryRow(ctx, createUserOauth, arg.Email, arg.OauthProvider)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM source.users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const getCommunitySettingsByUserId = `-- name: GetCommunitySettingsByUserId :one
SELECT
    id,
    community_insights_opt_in,
    community_location_opt_in,
    community_country_code,
    community_region_code,
    modified_at
FROM source.users
WHERE id = $1
`

type GetCommunitySettingsByUserIdRow struct {
	ID                     pgtype.UUID
	CommunityInsightsOptIn bool
	CommunityLocationOptIn bool
	CommunityCountryCode   *string
	CommunityRegionCode    *string
	ModifiedAt             pgtype.Timestamp
}

func (q *Queries) GetCommunitySettingsByUserId(ctx context.Context, id pgtype.UUID) (GetCommunitySettingsByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getCommunitySettingsByUserId, id)
	var i GetCommunitySettingsByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code FROM source.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (SourceUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code FROM source.users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (SourceUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}

const updateCommunitySettingsByUserId = `-- name: UpdateCommunitySettingsByUserId :one
UPDATE source.users
SET
    community_insights_opt_in = $2,
    community_location_opt_in = $3,
    community_country_code = $4,
    community_region_code = $5,
    modified_at = NOW()
WHERE id = $1
RETURNING id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code
`

type UpdateCommunitySettingsByUserIdParams struct {
	ID                     pgtype.UUID
	CommunityInsightsOptIn bool
	CommunityLocationOptIn bool
	CommunityCountryCode   *string
	CommunityRegionCode    *string
}

func (q *Queries) UpdateCommunitySettingsByUserId(ctx context.Context, arg UpdateCommunitySettingsByUserIdParams) (SourceUser, error) {
	row := q.db.QueryRow(ctx, updateCommunitySettingsByUserId,
		arg.ID,
		arg.CommunityInsightsOptIn,
		arg.CommunityLocationOptIn,
		arg.CommunityCountryCode,
		arg.CommunityRegionCode,
	)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE source.users
SET timezone = $2, modified_at = NOW()
WHERE id = $1
RETURNING id, email, password, salt, oauth_provider, role, created_at, modified_at, timezone, community_insights_opt_in, community_location_opt_in, community_country_code, community_region_code
`

type UpdateUserTimezoneParams struct {
	ID       pgtype.UUID
	Timezone string
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (SourceUser, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i SourceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.OauthProvider,
		&i.Role,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Timezone,
		&i.CommunityInsightsOptIn,
		&i.CommunityLocationOptIn,
		&i.CommunityCountryCode,
		&i.CommunityRegionCode,
	)
	return i, err
}
