# Generated by Django 5.2.9 on 2025-12-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # Seed ML models
        migrations.RunSQL(
            sql="""
                INSERT INTO active_ml_models (ml_model, is_enabled, created_at, modified_at)
                VALUES 
                    ('sentiment_analysis', true, NOW(), NOW()),
                    ('topic_modeling', true, NOW(), NOW());
            """,
            reverse_sql="""
                DELETE FROM active_ml_models 
                WHERE ml_model IN ('sentiment_analysis', 'topic_modeling');
            """,
        ),
        # Seed feature flag
        migrations.RunSQL(
            sql="""
                INSERT INTO feature_flags (id, flag_name, enabled, created_at, modified_at)
                VALUES (
                    uuid_generate_v4(),
                    'enable_ai_insights',
                    false,
                    NOW(),
                    NOW()
                );
            """,
            reverse_sql="DELETE FROM feature_flags WHERE flag_name = 'enable_ai_insights';",
        ),
    ]
