# Generated by Django 5.2.9 on 2025-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveMLModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ml_model", models.CharField(max_length=255, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "active_ml_models",
                "ordering": ["ml_model"],
            },
        ),
    ]
