# Generated by Django 5.2.9 on 2026-03-14 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGameBalance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.IntegerField(default=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_balance",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_game_balances",
            },
        ),
        migrations.CreateModel(
            name="UserGameBet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("zone", models.CharField(max_length=10)),
                ("amount", models.IntegerField()),
                ("roll_result", models.IntegerField()),
                ("payout", models.IntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_bets",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_game_bets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="idx_ugb_user_created")
                ],
            },
        ),
    ]
