# Generated by Django 5.2.9 on 2026-03-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_usergamebalance_usergamebet"),
    ]

    operations = [
        migrations.AddField(
            model_name="journaltopic",
            name="subtopic_name",
            field=models.CharField(db_default=None, max_length=100, null=True),
        ),
    ]
