# Generated by Django 5.2.9 on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_openai_topic_modeling"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEmbedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("embedding", models.TextField()),
                (
                    "model_version",
                    models.CharField(default="all-MiniLM-L6-v2", max_length=50),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        db_column="journal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.journal",
                    ),
                ),
            ],
            options={
                "db_table": "journal_embeddings",
                "unique_together": {("journal", "model_version")},
            },
        ),
        # Enable pgvector extension and convert the TextField to vector(384)
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS vector SCHEMA public;",
                "ALTER TABLE source.journal_embeddings ALTER COLUMN embedding TYPE public.vector(384) USING embedding::public.vector(384);",
                "CREATE INDEX idx_journal_embeddings_hnsw ON source.journal_embeddings USING hnsw (embedding vector_cosine_ops);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS source.idx_journal_embeddings_hnsw;",
                "ALTER TABLE source.journal_embeddings ALTER COLUMN embedding TYPE text USING embedding::text;",
            ],
        ),
    ]
