# Generated by Django 5.2.9 on 2026-03-22 14:56

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_journalembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        # Backfill existing rows with tsvector data.
        migrations.RunSQL(
            sql="UPDATE source.journals SET search_vector = to_tsvector('english', journal_text);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Trigger function to auto-populate search_vector on INSERT/UPDATE.
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION source.journals_search_vector_trigger() RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector := to_tsvector('english', NEW.journal_text);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS source.journals_search_vector_trigger();",
        ),
        # Wire the trigger to the journals table.
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trg_journals_search_vector
                    BEFORE INSERT OR UPDATE OF journal_text ON source.journals
                    FOR EACH ROW
                    EXECUTE FUNCTION source.journals_search_vector_trigger();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trg_journals_search_vector ON source.journals;",
        ),
    ]
