# Generated by Django 5.2.9 on 2026-04-01 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_seed_dev_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("attention", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "invoice_clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePaymentInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_payable_to", models.CharField(max_length=255)),
                ("ach_account_number", models.CharField(max_length=50)),
                ("ach_routing_number", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "payment info",
                "verbose_name_plural": "payment info",
                "db_table": "invoice_payment_info",
            },
        ),
        migrations.CreateModel(
            name="InvoiceSender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "invoice_senders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "terms",
                    models.CharField(
                        choices=[
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                            ("Due on Receipt", "Due on Receipt"),
                        ],
                        default="Net 30",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="client_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.invoiceclient",
                    ),
                ),
                (
                    "payment_info",
                    models.ForeignKey(
                        db_column="payment_info_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.invoicepaymentinfo",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="sender_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.invoicesender",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=8)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        db_column="invoice_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["id"],
            },
        ),
    ]
