# Generated by Django 5.2.9 on 2026-04-04 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_journal_child_fk_on_delete_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.models.UUIDGenerateV4(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("markdown", "Markdown")],
                        default="csv",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_exports",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "journal_exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
