# Generated by Django 5.2.9 on 2026-04-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_journalexport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.user",
            ),
        ),
    ]
