# Generated by Django 5.2.9 on 2026-04-05 14:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_journal_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalContentFlag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("flag_type", models.CharField(max_length=32)),
                ("severity", models.CharField(max_length=16)),
                (
                    "matched_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("analysis_summary", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        db_column="journal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.journal",
                    ),
                ),
            ],
            options={
                "db_table": "journal_content_flags",
                "indexes": [
                    models.Index(fields=["journal"], name="idx_jcf_journal_id"),
                    models.Index(fields=["flag_type"], name="idx_jcf_flag_type"),
                ],
            },
        ),
    ]
