# Generated by Django 5.2.9 on 2026-04-07 22:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_journal_content_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="community_country_code",
            field=models.CharField(blank=True, db_default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="community_insights_opt_in",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="community_location_opt_in",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="community_region_code",
            field=models.CharField(blank=True, db_default=None, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name="CommunityMoodRollup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bucket_date", models.DateField()),
                ("time_grain", models.CharField(max_length=16)),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_value", models.CharField(max_length=64)),
                ("mood_name", models.CharField(max_length=100)),
                ("entry_count", models.IntegerField()),
                ("unique_user_count", models.IntegerField()),
                ("rank", models.IntegerField()),
                (
                    "delta_vs_previous",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "community_mood_rollups",
                "indexes": [
                    models.Index(
                        fields=["bucket_date", "time_grain", "scope_type", "scope_value"],
                        name="idx_cmr_bucket_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "bucket_date",
                            "time_grain",
                            "scope_type",
                            "scope_value",
                            "mood_name",
                        ),
                        name="uniq_community_mood_rollup",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityPromptSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bucket_date", models.DateField()),
                ("time_grain", models.CharField(max_length=16)),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_value", models.CharField(max_length=64)),
                ("prompt_set_json", models.JSONField(blank=True, default=list)),
                (
                    "source_theme_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "source_mood_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "generation_method",
                    models.CharField(db_default="template", default="template", max_length=32),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "community_prompt_sets",
                "indexes": [
                    models.Index(
                        fields=["bucket_date", "time_grain", "scope_type", "scope_value"],
                        name="idx_cps_bucket_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_date", "time_grain", "scope_type", "scope_value"),
                        name="uniq_community_prompt_set",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunitySummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bucket_date", models.DateField()),
                ("time_grain", models.CharField(max_length=16)),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_value", models.CharField(max_length=64)),
                ("summary_text", models.TextField()),
                (
                    "source_theme_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "source_mood_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "generation_method",
                    models.CharField(db_default="template", default="template", max_length=32),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "community_summaries",
                "indexes": [
                    models.Index(
                        fields=["bucket_date", "time_grain", "scope_type", "scope_value"],
                        name="idx_cs_bucket_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket_date", "time_grain", "scope_type", "scope_value"),
                        name="uniq_community_summary",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityThemeRollup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bucket_date", models.DateField()),
                ("time_grain", models.CharField(max_length=16)),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_value", models.CharField(max_length=64)),
                ("theme_name", models.CharField(max_length=100)),
                ("entry_count", models.IntegerField()),
                ("unique_user_count", models.IntegerField()),
                ("rank", models.IntegerField()),
                (
                    "delta_vs_previous",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "community_theme_rollups",
                "indexes": [
                    models.Index(
                        fields=["bucket_date", "time_grain", "scope_type", "scope_value"],
                        name="idx_ctr_bucket_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "bucket_date",
                            "time_grain",
                            "scope_type",
                            "scope_value",
                            "theme_name",
                        ),
                        name="uniq_community_theme_rollup",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalCommunityProjection",
            fields=[
                (
                    "journal",
                    models.OneToOneField(
                        db_column="journal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.journal",
                    ),
                ),
                ("eligible_for_community", models.BooleanField(db_default=False, default=False)),
                ("entry_local_date", models.DateField(blank=True, null=True)),
                ("primary_mood", models.CharField(blank=True, max_length=32, null=True)),
                ("primary_sentiment", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "theme_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=8, null=True)),
                ("region_code", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "analysis_version",
                    models.CharField(db_default="v1", default="v1", max_length=64),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "journal_community_projections",
                "indexes": [
                    models.Index(
                        fields=["eligible_for_community", "entry_local_date"],
                        name="idx_jcp_eligible_date",
                    ),
                    models.Index(
                        fields=["region_code", "entry_local_date"], name="idx_jcp_region_date"
                    ),
                ],
            },
        ),
    ]
