# Generated by Django 5.2.9 on 2026-04-18 19:33

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_seed_sales_outreach_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionWatermark",
            fields=[
                (
                    "source_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("watermark_at", models.DateTimeField()),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("last_run_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ingestion_watermarks",
                "ordering": ["source_name"],
            },
        ),
        migrations.CreateModel(
            name="ExampleApiRecord",
            fields=[
                ("source_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("payload", models.JSONField(default=dict)),
                ("modified_at", models.DateTimeField()),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "example_api_records",
                "ordering": ["-modified_at", "source_id"],
                "indexes": [
                    models.Index(fields=["modified_at"], name="idx_example_api_modified_at")
                ],
            },
        ),
    ]
