# Generated by Django 5.2.9 on 2026-04-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_ingestionwatermark_exampleapirecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleApiUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "example_api_users",
                "ordering": ["id"],
            },
        ),
    ]
