# Generated by Django 5.2.9 on 2026-06-27 22:35

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_add_example_api_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesData",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("total_sales", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "db_table": "sales_data",
                "ordering": ["-date", "id"],
            },
        ),
    ]
