FROM golang:1.25-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE 8080 50051

# we need go toolchain for air to rebuild and enable hot reloading
# so we cant use scratch or get much slimmer here.
CMD ["air", "-c", ".air.toml"]
