from dagster import AssetExecutionContext, asset

from dagster_project.dbt_config import DBT_PROJECT_DIR, dbt_project
from dagster_project.resources.openmetadata import OpenMetadataResource

POSTGRES_SERVICE_NAME = "lotus_postgres"


@asset(group_name="catalog")
def openmetadata_postgres_sync(
    context: AssetExecutionContext, openmetadata_resource: OpenMetadataResource
) -> None:
    """Ingest source/silver/gold schemas into OpenMetadata as a Database
    Service; the dbt sync attaches lineage onto the tables this creates."""
    openmetadata_resource.run_ingestion(
        context=context,
        source_config={
            "type": "postgres",
            "serviceName": POSTGRES_SERVICE_NAME,
            "serviceConnection": {
                "config": {
                    "type": "Postgres",
                    "username": "postgres",
                    "authType": {"password": "postgres"},
                    "hostPort": "postgres:5432",
                    "database": "postgres",
                }
            },
            "sourceConfig": {
                "config": {
                    "type": "DatabaseMetadata",
                    "schemaFilterPattern": {"includes": ["source", "silver", "gold"]},
                }
            },
        },
    )


@asset(group_name="catalog", deps=[openmetadata_postgres_sync])
def openmetadata_dbt_sync(
    context: AssetExecutionContext, openmetadata_resource: OpenMetadataResource
) -> None:
    """Parse the dbt manifest/run_results and push lineage, descriptions, and
    test results onto the tables from the postgres sync. catalog.json isn't
    generated by this project's dbt build/test steps (only `dbt docs
    generate` produces it) — omitted, it's optional in OpenMetadata's schema
    (only dbtManifestFilePath is required)."""
    if dbt_project is None:
        context.log.warning("dbt project not mounted, skipping OpenMetadata dbt sync")
        return

    target_dir = DBT_PROJECT_DIR / "target"
    openmetadata_resource.run_ingestion(
        context=context,
        source_config={
            "type": "dbt",
            "serviceName": POSTGRES_SERVICE_NAME,
            "sourceConfig": {
                "config": {
                    "type": "DBT",
                    "dbtConfigSource": {
                        "dbtConfigType": "local",
                        "dbtManifestFilePath": str(target_dir / "manifest.json"),
                        "dbtRunResultsFilePath": str(target_dir / "run_results.json"),
                    },
                }
            },
        },
    )
