// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/jyablonski/lotus/internal/inject"
	"net/http"
	"sync"
)

// Ensure, that HTTPDoerMock does implement inject.HTTPDoer.
// If this is not the case, regenerate this file with moq.
var _ inject.HTTPDoer = &HTTPDoerMock{}

// HTTPDoerMock is a mock implementation of inject.HTTPDoer.
//
//	func TestSomethingThatUsesHTTPDoer(t *testing.T) {
//
//		// make and configure a mocked inject.HTTPDoer
//		mockedHTTPDoer := &HTTPDoerMock{
//			DoFunc: func(req *http.Request) (*http.Response, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedHTTPDoer in code that requires inject.HTTPDoer
//		// and then make assertions.
//
//	}
type HTTPDoerMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *HTTPDoerMock) Do(req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("HTTPDoerMock.DoFunc: method is nil but HTTPDoer.Do was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedHTTPDoer.DoCalls())
func (mock *HTTPDoerMock) DoCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
