// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/jyablonski/lotus/internal/db"
	"sync"
)

// Ensure, that QuerierMock does implement db.Querier.
// If this is not the case, regenerate this file with moq.
var _ db.Querier = &QuerierMock{}

// QuerierMock is a mock implementation of db.Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked db.Querier
//		mockedQuerier := &QuerierMock{
//			CreateJournalFunc: func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
//				panic("mock out the CreateJournal method")
//			},
//			CreateUserFunc: func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
//				panic("mock out the CreateUser method")
//			},
//			CreateUserOauthFunc: func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
//				panic("mock out the CreateUserOauth method")
//			},
//			GetActiveFeatureFlagsFunc: func(ctx context.Context) ([]db.SourceWaffleFlag, error) {
//				panic("mock out the GetActiveFeatureFlags method")
//			},
//			GetActiveMLModelFunc: func(ctx context.Context, mlModel string) (bool, error) {
//				panic("mock out the GetActiveMLModel method")
//			},
//			GetFeatureFlagByNameFunc: func(ctx context.Context, name string) (db.SourceWaffleFlag, error) {
//				panic("mock out the GetFeatureFlagByName method")
//			},
//			GetInvoiceClientByNameFunc: func(ctx context.Context, name string) (uuid.UUID, error) {
//				panic("mock out the GetInvoiceClientByName method")
//			},
//			GetInvoicePaymentByCheckPayableFunc: func(ctx context.Context, checkPayableTo string) (uuid.UUID, error) {
//				panic("mock out the GetInvoicePaymentByCheckPayable method")
//			},
//			GetInvoiceSenderByNameEmailFunc: func(ctx context.Context, arg db.GetInvoiceSenderByNameEmailParams) (uuid.UUID, error) {
//				panic("mock out the GetInvoiceSenderByNameEmail method")
//			},
//			GetJournalByIdFunc: func(ctx context.Context, id int32) (db.SourceJournal, error) {
//				panic("mock out the GetJournalById method")
//			},
//			GetJournalCountByUserIdFunc: func(ctx context.Context, userID uuid.UUID) (int64, error) {
//				panic("mock out the GetJournalCountByUserId method")
//			},
//			GetJournalsByUserIdFunc: func(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserId method")
//			},
//			GetJournalsByUserIdPaginatedFunc: func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserIdPaginated method")
//			},
//			GetRuntimeConfigByKeyFunc: func(ctx context.Context, key string) (db.SourceRuntimeConfig, error) {
//				panic("mock out the GetRuntimeConfigByKey method")
//			},
//			GetTopicsByJournalIdsFunc: func(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error) {
//				panic("mock out the GetTopicsByJournalIds method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (db.SourceUser, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIdFunc: func(ctx context.Context, id uuid.UUID) (db.SourceUser, error) {
//				panic("mock out the GetUserById method")
//			},
//			GetUserGameBalanceFunc: func(ctx context.Context, userID uuid.UUID) (db.SourceUserGameBalance, error) {
//				panic("mock out the GetUserGameBalance method")
//			},
//			GetUserGameBetsFunc: func(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error) {
//				panic("mock out the GetUserGameBets method")
//			},
//			GetUserJournalSummaryByUserIdFunc: func(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error) {
//				panic("mock out the GetUserJournalSummaryByUserId method")
//			},
//			InsertInvoiceFunc: func(ctx context.Context, arg db.InsertInvoiceParams) (uuid.UUID, error) {
//				panic("mock out the InsertInvoice method")
//			},
//			InsertInvoiceClientFunc: func(ctx context.Context, arg db.InsertInvoiceClientParams) (uuid.UUID, error) {
//				panic("mock out the InsertInvoiceClient method")
//			},
//			InsertInvoiceLineItemFunc: func(ctx context.Context, arg db.InsertInvoiceLineItemParams) error {
//				panic("mock out the InsertInvoiceLineItem method")
//			},
//			InsertInvoicePaymentFunc: func(ctx context.Context, arg db.InsertInvoicePaymentParams) (uuid.UUID, error) {
//				panic("mock out the InsertInvoicePayment method")
//			},
//			InsertInvoiceSenderFunc: func(ctx context.Context, arg db.InsertInvoiceSenderParams) (uuid.UUID, error) {
//				panic("mock out the InsertInvoiceSender method")
//			},
//			InsertUserGameBetFunc: func(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error) {
//				panic("mock out the InsertUserGameBet method")
//			},
//			ListInvoiceClientsFunc: func(ctx context.Context) ([]db.SourceInvoiceClient, error) {
//				panic("mock out the ListInvoiceClients method")
//			},
//			ListInvoicePaymentInfoFunc: func(ctx context.Context) ([]db.SourceInvoicePaymentInfo, error) {
//				panic("mock out the ListInvoicePaymentInfo method")
//			},
//			ListInvoiceSendersFunc: func(ctx context.Context) ([]db.SourceInvoiceSender, error) {
//				panic("mock out the ListInvoiceSenders method")
//			},
//			UpdateUserTimezoneFunc: func(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error) {
//				panic("mock out the UpdateUserTimezone method")
//			},
//			UpsertRuntimeConfigValueFunc: func(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error) {
//				panic("mock out the UpsertRuntimeConfigValue method")
//			},
//			UpsertUserGameBalanceFunc: func(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error) {
//				panic("mock out the UpsertUserGameBalance method")
//			},
//		}
//
//		// use mockedQuerier in code that requires db.Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CreateJournalFunc mocks the CreateJournal method.
	CreateJournalFunc func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error)

	// CreateUserOauthFunc mocks the CreateUserOauth method.
	CreateUserOauthFunc func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error)

	// GetActiveFeatureFlagsFunc mocks the GetActiveFeatureFlags method.
	GetActiveFeatureFlagsFunc func(ctx context.Context) ([]db.SourceWaffleFlag, error)

	// GetActiveMLModelFunc mocks the GetActiveMLModel method.
	GetActiveMLModelFunc func(ctx context.Context, mlModel string) (bool, error)

	// GetFeatureFlagByNameFunc mocks the GetFeatureFlagByName method.
	GetFeatureFlagByNameFunc func(ctx context.Context, name string) (db.SourceWaffleFlag, error)

	// GetInvoiceClientByNameFunc mocks the GetInvoiceClientByName method.
	GetInvoiceClientByNameFunc func(ctx context.Context, name string) (uuid.UUID, error)

	// GetInvoicePaymentByCheckPayableFunc mocks the GetInvoicePaymentByCheckPayable method.
	GetInvoicePaymentByCheckPayableFunc func(ctx context.Context, checkPayableTo string) (uuid.UUID, error)

	// GetInvoiceSenderByNameEmailFunc mocks the GetInvoiceSenderByNameEmail method.
	GetInvoiceSenderByNameEmailFunc func(ctx context.Context, arg db.GetInvoiceSenderByNameEmailParams) (uuid.UUID, error)

	// GetJournalByIdFunc mocks the GetJournalById method.
	GetJournalByIdFunc func(ctx context.Context, id int32) (db.SourceJournal, error)

	// GetJournalCountByUserIdFunc mocks the GetJournalCountByUserId method.
	GetJournalCountByUserIdFunc func(ctx context.Context, userID uuid.UUID) (int64, error)

	// GetJournalsByUserIdFunc mocks the GetJournalsByUserId method.
	GetJournalsByUserIdFunc func(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error)

	// GetJournalsByUserIdPaginatedFunc mocks the GetJournalsByUserIdPaginated method.
	GetJournalsByUserIdPaginatedFunc func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error)

	// GetRuntimeConfigByKeyFunc mocks the GetRuntimeConfigByKey method.
	GetRuntimeConfigByKeyFunc func(ctx context.Context, key string) (db.SourceRuntimeConfig, error)

	// GetTopicsByJournalIdsFunc mocks the GetTopicsByJournalIds method.
	GetTopicsByJournalIdsFunc func(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (db.SourceUser, error)

	// GetUserByIdFunc mocks the GetUserById method.
	GetUserByIdFunc func(ctx context.Context, id uuid.UUID) (db.SourceUser, error)

	// GetUserGameBalanceFunc mocks the GetUserGameBalance method.
	GetUserGameBalanceFunc func(ctx context.Context, userID uuid.UUID) (db.SourceUserGameBalance, error)

	// GetUserGameBetsFunc mocks the GetUserGameBets method.
	GetUserGameBetsFunc func(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error)

	// GetUserJournalSummaryByUserIdFunc mocks the GetUserJournalSummaryByUserId method.
	GetUserJournalSummaryByUserIdFunc func(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error)

	// InsertInvoiceFunc mocks the InsertInvoice method.
	InsertInvoiceFunc func(ctx context.Context, arg db.InsertInvoiceParams) (uuid.UUID, error)

	// InsertInvoiceClientFunc mocks the InsertInvoiceClient method.
	InsertInvoiceClientFunc func(ctx context.Context, arg db.InsertInvoiceClientParams) (uuid.UUID, error)

	// InsertInvoiceLineItemFunc mocks the InsertInvoiceLineItem method.
	InsertInvoiceLineItemFunc func(ctx context.Context, arg db.InsertInvoiceLineItemParams) error

	// InsertInvoicePaymentFunc mocks the InsertInvoicePayment method.
	InsertInvoicePaymentFunc func(ctx context.Context, arg db.InsertInvoicePaymentParams) (uuid.UUID, error)

	// InsertInvoiceSenderFunc mocks the InsertInvoiceSender method.
	InsertInvoiceSenderFunc func(ctx context.Context, arg db.InsertInvoiceSenderParams) (uuid.UUID, error)

	// InsertUserGameBetFunc mocks the InsertUserGameBet method.
	InsertUserGameBetFunc func(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error)

	// ListInvoiceClientsFunc mocks the ListInvoiceClients method.
	ListInvoiceClientsFunc func(ctx context.Context) ([]db.SourceInvoiceClient, error)

	// ListInvoicePaymentInfoFunc mocks the ListInvoicePaymentInfo method.
	ListInvoicePaymentInfoFunc func(ctx context.Context) ([]db.SourceInvoicePaymentInfo, error)

	// ListInvoiceSendersFunc mocks the ListInvoiceSenders method.
	ListInvoiceSendersFunc func(ctx context.Context) ([]db.SourceInvoiceSender, error)

	// UpdateUserTimezoneFunc mocks the UpdateUserTimezone method.
	UpdateUserTimezoneFunc func(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error)

	// UpsertRuntimeConfigValueFunc mocks the UpsertRuntimeConfigValue method.
	UpsertRuntimeConfigValueFunc func(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error)

	// UpsertUserGameBalanceFunc mocks the UpsertUserGameBalance method.
	UpsertUserGameBalanceFunc func(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateJournal holds details about calls to the CreateJournal method.
		CreateJournal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateJournalParams
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserParams
		}
		// CreateUserOauth holds details about calls to the CreateUserOauth method.
		CreateUserOauth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserOauthParams
		}
		// GetActiveFeatureFlags holds details about calls to the GetActiveFeatureFlags method.
		GetActiveFeatureFlags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetActiveMLModel holds details about calls to the GetActiveMLModel method.
		GetActiveMLModel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MlModel is the mlModel argument value.
			MlModel string
		}
		// GetFeatureFlagByName holds details about calls to the GetFeatureFlagByName method.
		GetFeatureFlagByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetInvoiceClientByName holds details about calls to the GetInvoiceClientByName method.
		GetInvoiceClientByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetInvoicePaymentByCheckPayable holds details about calls to the GetInvoicePaymentByCheckPayable method.
		GetInvoicePaymentByCheckPayable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CheckPayableTo is the checkPayableTo argument value.
			CheckPayableTo string
		}
		// GetInvoiceSenderByNameEmail holds details about calls to the GetInvoiceSenderByNameEmail method.
		GetInvoiceSenderByNameEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetInvoiceSenderByNameEmailParams
		}
		// GetJournalById holds details about calls to the GetJournalById method.
		GetJournalById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int32
		}
		// GetJournalCountByUserId holds details about calls to the GetJournalCountByUserId method.
		GetJournalCountByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetJournalsByUserId holds details about calls to the GetJournalsByUserId method.
		GetJournalsByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetJournalsByUserIdPaginated holds details about calls to the GetJournalsByUserIdPaginated method.
		GetJournalsByUserIdPaginated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetJournalsByUserIdPaginatedParams
		}
		// GetRuntimeConfigByKey holds details about calls to the GetRuntimeConfigByKey method.
		GetRuntimeConfigByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetTopicsByJournalIds holds details about calls to the GetTopicsByJournalIds method.
		GetTopicsByJournalIds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dollar_1 is the dollar_1 argument value.
			Dollar_1 []int32
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserById holds details about calls to the GetUserById method.
		GetUserById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetUserGameBalance holds details about calls to the GetUserGameBalance method.
		GetUserGameBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetUserGameBets holds details about calls to the GetUserGameBets method.
		GetUserGameBets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetUserGameBetsParams
		}
		// GetUserJournalSummaryByUserId holds details about calls to the GetUserJournalSummaryByUserId method.
		GetUserJournalSummaryByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// InsertInvoice holds details about calls to the InsertInvoice method.
		InsertInvoice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertInvoiceParams
		}
		// InsertInvoiceClient holds details about calls to the InsertInvoiceClient method.
		InsertInvoiceClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertInvoiceClientParams
		}
		// InsertInvoiceLineItem holds details about calls to the InsertInvoiceLineItem method.
		InsertInvoiceLineItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertInvoiceLineItemParams
		}
		// InsertInvoicePayment holds details about calls to the InsertInvoicePayment method.
		InsertInvoicePayment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertInvoicePaymentParams
		}
		// InsertInvoiceSender holds details about calls to the InsertInvoiceSender method.
		InsertInvoiceSender []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertInvoiceSenderParams
		}
		// InsertUserGameBet holds details about calls to the InsertUserGameBet method.
		InsertUserGameBet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertUserGameBetParams
		}
		// ListInvoiceClients holds details about calls to the ListInvoiceClients method.
		ListInvoiceClients []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListInvoicePaymentInfo holds details about calls to the ListInvoicePaymentInfo method.
		ListInvoicePaymentInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListInvoiceSenders holds details about calls to the ListInvoiceSenders method.
		ListInvoiceSenders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateUserTimezone holds details about calls to the UpdateUserTimezone method.
		UpdateUserTimezone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateUserTimezoneParams
		}
		// UpsertRuntimeConfigValue holds details about calls to the UpsertRuntimeConfigValue method.
		UpsertRuntimeConfigValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertRuntimeConfigValueParams
		}
		// UpsertUserGameBalance holds details about calls to the UpsertUserGameBalance method.
		UpsertUserGameBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertUserGameBalanceParams
		}
	}
	lockCreateJournal                   sync.RWMutex
	lockCreateUser                      sync.RWMutex
	lockCreateUserOauth                 sync.RWMutex
	lockGetActiveFeatureFlags           sync.RWMutex
	lockGetActiveMLModel                sync.RWMutex
	lockGetFeatureFlagByName            sync.RWMutex
	lockGetInvoiceClientByName          sync.RWMutex
	lockGetInvoicePaymentByCheckPayable sync.RWMutex
	lockGetInvoiceSenderByNameEmail     sync.RWMutex
	lockGetJournalById                  sync.RWMutex
	lockGetJournalCountByUserId         sync.RWMutex
	lockGetJournalsByUserId             sync.RWMutex
	lockGetJournalsByUserIdPaginated    sync.RWMutex
	lockGetRuntimeConfigByKey           sync.RWMutex
	lockGetTopicsByJournalIds           sync.RWMutex
	lockGetUserByEmail                  sync.RWMutex
	lockGetUserById                     sync.RWMutex
	lockGetUserGameBalance              sync.RWMutex
	lockGetUserGameBets                 sync.RWMutex
	lockGetUserJournalSummaryByUserId   sync.RWMutex
	lockInsertInvoice                   sync.RWMutex
	lockInsertInvoiceClient             sync.RWMutex
	lockInsertInvoiceLineItem           sync.RWMutex
	lockInsertInvoicePayment            sync.RWMutex
	lockInsertInvoiceSender             sync.RWMutex
	lockInsertUserGameBet               sync.RWMutex
	lockListInvoiceClients              sync.RWMutex
	lockListInvoicePaymentInfo          sync.RWMutex
	lockListInvoiceSenders              sync.RWMutex
	lockUpdateUserTimezone              sync.RWMutex
	lockUpsertRuntimeConfigValue        sync.RWMutex
	lockUpsertUserGameBalance           sync.RWMutex
}

// CreateJournal calls CreateJournalFunc.
func (mock *QuerierMock) CreateJournal(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
	if mock.CreateJournalFunc == nil {
		panic("QuerierMock.CreateJournalFunc: method is nil but Querier.CreateJournal was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateJournal.Lock()
	mock.calls.CreateJournal = append(mock.calls.CreateJournal, callInfo)
	mock.lockCreateJournal.Unlock()
	return mock.CreateJournalFunc(ctx, arg)
}

// CreateJournalCalls gets all the calls that were made to CreateJournal.
// Check the length with:
//
//	len(mockedQuerier.CreateJournalCalls())
func (mock *QuerierMock) CreateJournalCalls() []struct {
	Ctx context.Context
	Arg db.CreateJournalParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}
	mock.lockCreateJournal.RLock()
	calls = mock.calls.CreateJournal
	mock.lockCreateJournal.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *QuerierMock) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
	if mock.CreateUserFunc == nil {
		panic("QuerierMock.CreateUserFunc: method is nil but Querier.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, arg)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedQuerier.CreateUserCalls())
func (mock *QuerierMock) CreateUserCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// CreateUserOauth calls CreateUserOauthFunc.
func (mock *QuerierMock) CreateUserOauth(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
	if mock.CreateUserOauthFunc == nil {
		panic("QuerierMock.CreateUserOauthFunc: method is nil but Querier.CreateUserOauth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUserOauth.Lock()
	mock.calls.CreateUserOauth = append(mock.calls.CreateUserOauth, callInfo)
	mock.lockCreateUserOauth.Unlock()
	return mock.CreateUserOauthFunc(ctx, arg)
}

// CreateUserOauthCalls gets all the calls that were made to CreateUserOauth.
// Check the length with:
//
//	len(mockedQuerier.CreateUserOauthCalls())
func (mock *QuerierMock) CreateUserOauthCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserOauthParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}
	mock.lockCreateUserOauth.RLock()
	calls = mock.calls.CreateUserOauth
	mock.lockCreateUserOauth.RUnlock()
	return calls
}

// GetActiveFeatureFlags calls GetActiveFeatureFlagsFunc.
func (mock *QuerierMock) GetActiveFeatureFlags(ctx context.Context) ([]db.SourceWaffleFlag, error) {
	if mock.GetActiveFeatureFlagsFunc == nil {
		panic("QuerierMock.GetActiveFeatureFlagsFunc: method is nil but Querier.GetActiveFeatureFlags was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetActiveFeatureFlags.Lock()
	mock.calls.GetActiveFeatureFlags = append(mock.calls.GetActiveFeatureFlags, callInfo)
	mock.lockGetActiveFeatureFlags.Unlock()
	return mock.GetActiveFeatureFlagsFunc(ctx)
}

// GetActiveFeatureFlagsCalls gets all the calls that were made to GetActiveFeatureFlags.
// Check the length with:
//
//	len(mockedQuerier.GetActiveFeatureFlagsCalls())
func (mock *QuerierMock) GetActiveFeatureFlagsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetActiveFeatureFlags.RLock()
	calls = mock.calls.GetActiveFeatureFlags
	mock.lockGetActiveFeatureFlags.RUnlock()
	return calls
}

// GetActiveMLModel calls GetActiveMLModelFunc.
func (mock *QuerierMock) GetActiveMLModel(ctx context.Context, mlModel string) (bool, error) {
	if mock.GetActiveMLModelFunc == nil {
		panic("QuerierMock.GetActiveMLModelFunc: method is nil but Querier.GetActiveMLModel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		MlModel string
	}{
		Ctx:     ctx,
		MlModel: mlModel,
	}
	mock.lockGetActiveMLModel.Lock()
	mock.calls.GetActiveMLModel = append(mock.calls.GetActiveMLModel, callInfo)
	mock.lockGetActiveMLModel.Unlock()
	return mock.GetActiveMLModelFunc(ctx, mlModel)
}

// GetActiveMLModelCalls gets all the calls that were made to GetActiveMLModel.
// Check the length with:
//
//	len(mockedQuerier.GetActiveMLModelCalls())
func (mock *QuerierMock) GetActiveMLModelCalls() []struct {
	Ctx     context.Context
	MlModel string
} {
	var calls []struct {
		Ctx     context.Context
		MlModel string
	}
	mock.lockGetActiveMLModel.RLock()
	calls = mock.calls.GetActiveMLModel
	mock.lockGetActiveMLModel.RUnlock()
	return calls
}

// GetFeatureFlagByName calls GetFeatureFlagByNameFunc.
func (mock *QuerierMock) GetFeatureFlagByName(ctx context.Context, name string) (db.SourceWaffleFlag, error) {
	if mock.GetFeatureFlagByNameFunc == nil {
		panic("QuerierMock.GetFeatureFlagByNameFunc: method is nil but Querier.GetFeatureFlagByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetFeatureFlagByName.Lock()
	mock.calls.GetFeatureFlagByName = append(mock.calls.GetFeatureFlagByName, callInfo)
	mock.lockGetFeatureFlagByName.Unlock()
	return mock.GetFeatureFlagByNameFunc(ctx, name)
}

// GetFeatureFlagByNameCalls gets all the calls that were made to GetFeatureFlagByName.
// Check the length with:
//
//	len(mockedQuerier.GetFeatureFlagByNameCalls())
func (mock *QuerierMock) GetFeatureFlagByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetFeatureFlagByName.RLock()
	calls = mock.calls.GetFeatureFlagByName
	mock.lockGetFeatureFlagByName.RUnlock()
	return calls
}

// GetInvoiceClientByName calls GetInvoiceClientByNameFunc.
func (mock *QuerierMock) GetInvoiceClientByName(ctx context.Context, name string) (uuid.UUID, error) {
	if mock.GetInvoiceClientByNameFunc == nil {
		panic("QuerierMock.GetInvoiceClientByNameFunc: method is nil but Querier.GetInvoiceClientByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetInvoiceClientByName.Lock()
	mock.calls.GetInvoiceClientByName = append(mock.calls.GetInvoiceClientByName, callInfo)
	mock.lockGetInvoiceClientByName.Unlock()
	return mock.GetInvoiceClientByNameFunc(ctx, name)
}

// GetInvoiceClientByNameCalls gets all the calls that were made to GetInvoiceClientByName.
// Check the length with:
//
//	len(mockedQuerier.GetInvoiceClientByNameCalls())
func (mock *QuerierMock) GetInvoiceClientByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetInvoiceClientByName.RLock()
	calls = mock.calls.GetInvoiceClientByName
	mock.lockGetInvoiceClientByName.RUnlock()
	return calls
}

// GetInvoicePaymentByCheckPayable calls GetInvoicePaymentByCheckPayableFunc.
func (mock *QuerierMock) GetInvoicePaymentByCheckPayable(ctx context.Context, checkPayableTo string) (uuid.UUID, error) {
	if mock.GetInvoicePaymentByCheckPayableFunc == nil {
		panic("QuerierMock.GetInvoicePaymentByCheckPayableFunc: method is nil but Querier.GetInvoicePaymentByCheckPayable was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CheckPayableTo string
	}{
		Ctx:            ctx,
		CheckPayableTo: checkPayableTo,
	}
	mock.lockGetInvoicePaymentByCheckPayable.Lock()
	mock.calls.GetInvoicePaymentByCheckPayable = append(mock.calls.GetInvoicePaymentByCheckPayable, callInfo)
	mock.lockGetInvoicePaymentByCheckPayable.Unlock()
	return mock.GetInvoicePaymentByCheckPayableFunc(ctx, checkPayableTo)
}

// GetInvoicePaymentByCheckPayableCalls gets all the calls that were made to GetInvoicePaymentByCheckPayable.
// Check the length with:
//
//	len(mockedQuerier.GetInvoicePaymentByCheckPayableCalls())
func (mock *QuerierMock) GetInvoicePaymentByCheckPayableCalls() []struct {
	Ctx            context.Context
	CheckPayableTo string
} {
	var calls []struct {
		Ctx            context.Context
		CheckPayableTo string
	}
	mock.lockGetInvoicePaymentByCheckPayable.RLock()
	calls = mock.calls.GetInvoicePaymentByCheckPayable
	mock.lockGetInvoicePaymentByCheckPayable.RUnlock()
	return calls
}

// GetInvoiceSenderByNameEmail calls GetInvoiceSenderByNameEmailFunc.
func (mock *QuerierMock) GetInvoiceSenderByNameEmail(ctx context.Context, arg db.GetInvoiceSenderByNameEmailParams) (uuid.UUID, error) {
	if mock.GetInvoiceSenderByNameEmailFunc == nil {
		panic("QuerierMock.GetInvoiceSenderByNameEmailFunc: method is nil but Querier.GetInvoiceSenderByNameEmail was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetInvoiceSenderByNameEmailParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetInvoiceSenderByNameEmail.Lock()
	mock.calls.GetInvoiceSenderByNameEmail = append(mock.calls.GetInvoiceSenderByNameEmail, callInfo)
	mock.lockGetInvoiceSenderByNameEmail.Unlock()
	return mock.GetInvoiceSenderByNameEmailFunc(ctx, arg)
}

// GetInvoiceSenderByNameEmailCalls gets all the calls that were made to GetInvoiceSenderByNameEmail.
// Check the length with:
//
//	len(mockedQuerier.GetInvoiceSenderByNameEmailCalls())
func (mock *QuerierMock) GetInvoiceSenderByNameEmailCalls() []struct {
	Ctx context.Context
	Arg db.GetInvoiceSenderByNameEmailParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetInvoiceSenderByNameEmailParams
	}
	mock.lockGetInvoiceSenderByNameEmail.RLock()
	calls = mock.calls.GetInvoiceSenderByNameEmail
	mock.lockGetInvoiceSenderByNameEmail.RUnlock()
	return calls
}

// GetJournalById calls GetJournalByIdFunc.
func (mock *QuerierMock) GetJournalById(ctx context.Context, id int32) (db.SourceJournal, error) {
	if mock.GetJournalByIdFunc == nil {
		panic("QuerierMock.GetJournalByIdFunc: method is nil but Querier.GetJournalById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int32
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJournalById.Lock()
	mock.calls.GetJournalById = append(mock.calls.GetJournalById, callInfo)
	mock.lockGetJournalById.Unlock()
	return mock.GetJournalByIdFunc(ctx, id)
}

// GetJournalByIdCalls gets all the calls that were made to GetJournalById.
// Check the length with:
//
//	len(mockedQuerier.GetJournalByIdCalls())
func (mock *QuerierMock) GetJournalByIdCalls() []struct {
	Ctx context.Context
	ID  int32
} {
	var calls []struct {
		Ctx context.Context
		ID  int32
	}
	mock.lockGetJournalById.RLock()
	calls = mock.calls.GetJournalById
	mock.lockGetJournalById.RUnlock()
	return calls
}

// GetJournalCountByUserId calls GetJournalCountByUserIdFunc.
func (mock *QuerierMock) GetJournalCountByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	if mock.GetJournalCountByUserIdFunc == nil {
		panic("QuerierMock.GetJournalCountByUserIdFunc: method is nil but Querier.GetJournalCountByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalCountByUserId.Lock()
	mock.calls.GetJournalCountByUserId = append(mock.calls.GetJournalCountByUserId, callInfo)
	mock.lockGetJournalCountByUserId.Unlock()
	return mock.GetJournalCountByUserIdFunc(ctx, userID)
}

// GetJournalCountByUserIdCalls gets all the calls that were made to GetJournalCountByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalCountByUserIdCalls())
func (mock *QuerierMock) GetJournalCountByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetJournalCountByUserId.RLock()
	calls = mock.calls.GetJournalCountByUserId
	mock.lockGetJournalCountByUserId.RUnlock()
	return calls
}

// GetJournalsByUserId calls GetJournalsByUserIdFunc.
func (mock *QuerierMock) GetJournalsByUserId(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdFunc: method is nil but Querier.GetJournalsByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalsByUserId.Lock()
	mock.calls.GetJournalsByUserId = append(mock.calls.GetJournalsByUserId, callInfo)
	mock.lockGetJournalsByUserId.Unlock()
	return mock.GetJournalsByUserIdFunc(ctx, userID)
}

// GetJournalsByUserIdCalls gets all the calls that were made to GetJournalsByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdCalls())
func (mock *QuerierMock) GetJournalsByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetJournalsByUserId.RLock()
	calls = mock.calls.GetJournalsByUserId
	mock.lockGetJournalsByUserId.RUnlock()
	return calls
}

// GetJournalsByUserIdPaginated calls GetJournalsByUserIdPaginatedFunc.
func (mock *QuerierMock) GetJournalsByUserIdPaginated(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdPaginatedFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdPaginatedFunc: method is nil but Querier.GetJournalsByUserIdPaginated was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetJournalsByUserIdPaginated.Lock()
	mock.calls.GetJournalsByUserIdPaginated = append(mock.calls.GetJournalsByUserIdPaginated, callInfo)
	mock.lockGetJournalsByUserIdPaginated.Unlock()
	return mock.GetJournalsByUserIdPaginatedFunc(ctx, arg)
}

// GetJournalsByUserIdPaginatedCalls gets all the calls that were made to GetJournalsByUserIdPaginated.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdPaginatedCalls())
func (mock *QuerierMock) GetJournalsByUserIdPaginatedCalls() []struct {
	Ctx context.Context
	Arg db.GetJournalsByUserIdPaginatedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}
	mock.lockGetJournalsByUserIdPaginated.RLock()
	calls = mock.calls.GetJournalsByUserIdPaginated
	mock.lockGetJournalsByUserIdPaginated.RUnlock()
	return calls
}

// GetRuntimeConfigByKey calls GetRuntimeConfigByKeyFunc.
func (mock *QuerierMock) GetRuntimeConfigByKey(ctx context.Context, key string) (db.SourceRuntimeConfig, error) {
	if mock.GetRuntimeConfigByKeyFunc == nil {
		panic("QuerierMock.GetRuntimeConfigByKeyFunc: method is nil but Querier.GetRuntimeConfigByKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetRuntimeConfigByKey.Lock()
	mock.calls.GetRuntimeConfigByKey = append(mock.calls.GetRuntimeConfigByKey, callInfo)
	mock.lockGetRuntimeConfigByKey.Unlock()
	return mock.GetRuntimeConfigByKeyFunc(ctx, key)
}

// GetRuntimeConfigByKeyCalls gets all the calls that were made to GetRuntimeConfigByKey.
// Check the length with:
//
//	len(mockedQuerier.GetRuntimeConfigByKeyCalls())
func (mock *QuerierMock) GetRuntimeConfigByKeyCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetRuntimeConfigByKey.RLock()
	calls = mock.calls.GetRuntimeConfigByKey
	mock.lockGetRuntimeConfigByKey.RUnlock()
	return calls
}

// GetTopicsByJournalIds calls GetTopicsByJournalIdsFunc.
func (mock *QuerierMock) GetTopicsByJournalIds(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error) {
	if mock.GetTopicsByJournalIdsFunc == nil {
		panic("QuerierMock.GetTopicsByJournalIdsFunc: method is nil but Querier.GetTopicsByJournalIds was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Dollar_1 []int32
	}{
		Ctx:      ctx,
		Dollar_1: dollar_1,
	}
	mock.lockGetTopicsByJournalIds.Lock()
	mock.calls.GetTopicsByJournalIds = append(mock.calls.GetTopicsByJournalIds, callInfo)
	mock.lockGetTopicsByJournalIds.Unlock()
	return mock.GetTopicsByJournalIdsFunc(ctx, dollar_1)
}

// GetTopicsByJournalIdsCalls gets all the calls that were made to GetTopicsByJournalIds.
// Check the length with:
//
//	len(mockedQuerier.GetTopicsByJournalIdsCalls())
func (mock *QuerierMock) GetTopicsByJournalIdsCalls() []struct {
	Ctx      context.Context
	Dollar_1 []int32
} {
	var calls []struct {
		Ctx      context.Context
		Dollar_1 []int32
	}
	mock.lockGetTopicsByJournalIds.RLock()
	calls = mock.calls.GetTopicsByJournalIds
	mock.lockGetTopicsByJournalIds.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *QuerierMock) GetUserByEmail(ctx context.Context, email string) (db.SourceUser, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("QuerierMock.GetUserByEmailFunc: method is nil but Querier.GetUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedQuerier.GetUserByEmailCalls())
func (mock *QuerierMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserById calls GetUserByIdFunc.
func (mock *QuerierMock) GetUserById(ctx context.Context, id uuid.UUID) (db.SourceUser, error) {
	if mock.GetUserByIdFunc == nil {
		panic("QuerierMock.GetUserByIdFunc: method is nil but Querier.GetUserById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserById.Lock()
	mock.calls.GetUserById = append(mock.calls.GetUserById, callInfo)
	mock.lockGetUserById.Unlock()
	return mock.GetUserByIdFunc(ctx, id)
}

// GetUserByIdCalls gets all the calls that were made to GetUserById.
// Check the length with:
//
//	len(mockedQuerier.GetUserByIdCalls())
func (mock *QuerierMock) GetUserByIdCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserById.RLock()
	calls = mock.calls.GetUserById
	mock.lockGetUserById.RUnlock()
	return calls
}

// GetUserGameBalance calls GetUserGameBalanceFunc.
func (mock *QuerierMock) GetUserGameBalance(ctx context.Context, userID uuid.UUID) (db.SourceUserGameBalance, error) {
	if mock.GetUserGameBalanceFunc == nil {
		panic("QuerierMock.GetUserGameBalanceFunc: method is nil but Querier.GetUserGameBalance was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserGameBalance.Lock()
	mock.calls.GetUserGameBalance = append(mock.calls.GetUserGameBalance, callInfo)
	mock.lockGetUserGameBalance.Unlock()
	return mock.GetUserGameBalanceFunc(ctx, userID)
}

// GetUserGameBalanceCalls gets all the calls that were made to GetUserGameBalance.
// Check the length with:
//
//	len(mockedQuerier.GetUserGameBalanceCalls())
func (mock *QuerierMock) GetUserGameBalanceCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetUserGameBalance.RLock()
	calls = mock.calls.GetUserGameBalance
	mock.lockGetUserGameBalance.RUnlock()
	return calls
}

// GetUserGameBets calls GetUserGameBetsFunc.
func (mock *QuerierMock) GetUserGameBets(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error) {
	if mock.GetUserGameBetsFunc == nil {
		panic("QuerierMock.GetUserGameBetsFunc: method is nil but Querier.GetUserGameBets was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetUserGameBetsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetUserGameBets.Lock()
	mock.calls.GetUserGameBets = append(mock.calls.GetUserGameBets, callInfo)
	mock.lockGetUserGameBets.Unlock()
	return mock.GetUserGameBetsFunc(ctx, arg)
}

// GetUserGameBetsCalls gets all the calls that were made to GetUserGameBets.
// Check the length with:
//
//	len(mockedQuerier.GetUserGameBetsCalls())
func (mock *QuerierMock) GetUserGameBetsCalls() []struct {
	Ctx context.Context
	Arg db.GetUserGameBetsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetUserGameBetsParams
	}
	mock.lockGetUserGameBets.RLock()
	calls = mock.calls.GetUserGameBets
	mock.lockGetUserGameBets.RUnlock()
	return calls
}

// GetUserJournalSummaryByUserId calls GetUserJournalSummaryByUserIdFunc.
func (mock *QuerierMock) GetUserJournalSummaryByUserId(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error) {
	if mock.GetUserJournalSummaryByUserIdFunc == nil {
		panic("QuerierMock.GetUserJournalSummaryByUserIdFunc: method is nil but Querier.GetUserJournalSummaryByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserJournalSummaryByUserId.Lock()
	mock.calls.GetUserJournalSummaryByUserId = append(mock.calls.GetUserJournalSummaryByUserId, callInfo)
	mock.lockGetUserJournalSummaryByUserId.Unlock()
	return mock.GetUserJournalSummaryByUserIdFunc(ctx, userID)
}

// GetUserJournalSummaryByUserIdCalls gets all the calls that were made to GetUserJournalSummaryByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetUserJournalSummaryByUserIdCalls())
func (mock *QuerierMock) GetUserJournalSummaryByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetUserJournalSummaryByUserId.RLock()
	calls = mock.calls.GetUserJournalSummaryByUserId
	mock.lockGetUserJournalSummaryByUserId.RUnlock()
	return calls
}

// InsertInvoice calls InsertInvoiceFunc.
func (mock *QuerierMock) InsertInvoice(ctx context.Context, arg db.InsertInvoiceParams) (uuid.UUID, error) {
	if mock.InsertInvoiceFunc == nil {
		panic("QuerierMock.InsertInvoiceFunc: method is nil but Querier.InsertInvoice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertInvoiceParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertInvoice.Lock()
	mock.calls.InsertInvoice = append(mock.calls.InsertInvoice, callInfo)
	mock.lockInsertInvoice.Unlock()
	return mock.InsertInvoiceFunc(ctx, arg)
}

// InsertInvoiceCalls gets all the calls that were made to InsertInvoice.
// Check the length with:
//
//	len(mockedQuerier.InsertInvoiceCalls())
func (mock *QuerierMock) InsertInvoiceCalls() []struct {
	Ctx context.Context
	Arg db.InsertInvoiceParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertInvoiceParams
	}
	mock.lockInsertInvoice.RLock()
	calls = mock.calls.InsertInvoice
	mock.lockInsertInvoice.RUnlock()
	return calls
}

// InsertInvoiceClient calls InsertInvoiceClientFunc.
func (mock *QuerierMock) InsertInvoiceClient(ctx context.Context, arg db.InsertInvoiceClientParams) (uuid.UUID, error) {
	if mock.InsertInvoiceClientFunc == nil {
		panic("QuerierMock.InsertInvoiceClientFunc: method is nil but Querier.InsertInvoiceClient was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertInvoiceClientParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertInvoiceClient.Lock()
	mock.calls.InsertInvoiceClient = append(mock.calls.InsertInvoiceClient, callInfo)
	mock.lockInsertInvoiceClient.Unlock()
	return mock.InsertInvoiceClientFunc(ctx, arg)
}

// InsertInvoiceClientCalls gets all the calls that were made to InsertInvoiceClient.
// Check the length with:
//
//	len(mockedQuerier.InsertInvoiceClientCalls())
func (mock *QuerierMock) InsertInvoiceClientCalls() []struct {
	Ctx context.Context
	Arg db.InsertInvoiceClientParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertInvoiceClientParams
	}
	mock.lockInsertInvoiceClient.RLock()
	calls = mock.calls.InsertInvoiceClient
	mock.lockInsertInvoiceClient.RUnlock()
	return calls
}

// InsertInvoiceLineItem calls InsertInvoiceLineItemFunc.
func (mock *QuerierMock) InsertInvoiceLineItem(ctx context.Context, arg db.InsertInvoiceLineItemParams) error {
	if mock.InsertInvoiceLineItemFunc == nil {
		panic("QuerierMock.InsertInvoiceLineItemFunc: method is nil but Querier.InsertInvoiceLineItem was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertInvoiceLineItemParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertInvoiceLineItem.Lock()
	mock.calls.InsertInvoiceLineItem = append(mock.calls.InsertInvoiceLineItem, callInfo)
	mock.lockInsertInvoiceLineItem.Unlock()
	return mock.InsertInvoiceLineItemFunc(ctx, arg)
}

// InsertInvoiceLineItemCalls gets all the calls that were made to InsertInvoiceLineItem.
// Check the length with:
//
//	len(mockedQuerier.InsertInvoiceLineItemCalls())
func (mock *QuerierMock) InsertInvoiceLineItemCalls() []struct {
	Ctx context.Context
	Arg db.InsertInvoiceLineItemParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertInvoiceLineItemParams
	}
	mock.lockInsertInvoiceLineItem.RLock()
	calls = mock.calls.InsertInvoiceLineItem
	mock.lockInsertInvoiceLineItem.RUnlock()
	return calls
}

// InsertInvoicePayment calls InsertInvoicePaymentFunc.
func (mock *QuerierMock) InsertInvoicePayment(ctx context.Context, arg db.InsertInvoicePaymentParams) (uuid.UUID, error) {
	if mock.InsertInvoicePaymentFunc == nil {
		panic("QuerierMock.InsertInvoicePaymentFunc: method is nil but Querier.InsertInvoicePayment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertInvoicePaymentParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertInvoicePayment.Lock()
	mock.calls.InsertInvoicePayment = append(mock.calls.InsertInvoicePayment, callInfo)
	mock.lockInsertInvoicePayment.Unlock()
	return mock.InsertInvoicePaymentFunc(ctx, arg)
}

// InsertInvoicePaymentCalls gets all the calls that were made to InsertInvoicePayment.
// Check the length with:
//
//	len(mockedQuerier.InsertInvoicePaymentCalls())
func (mock *QuerierMock) InsertInvoicePaymentCalls() []struct {
	Ctx context.Context
	Arg db.InsertInvoicePaymentParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertInvoicePaymentParams
	}
	mock.lockInsertInvoicePayment.RLock()
	calls = mock.calls.InsertInvoicePayment
	mock.lockInsertInvoicePayment.RUnlock()
	return calls
}

// InsertInvoiceSender calls InsertInvoiceSenderFunc.
func (mock *QuerierMock) InsertInvoiceSender(ctx context.Context, arg db.InsertInvoiceSenderParams) (uuid.UUID, error) {
	if mock.InsertInvoiceSenderFunc == nil {
		panic("QuerierMock.InsertInvoiceSenderFunc: method is nil but Querier.InsertInvoiceSender was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertInvoiceSenderParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertInvoiceSender.Lock()
	mock.calls.InsertInvoiceSender = append(mock.calls.InsertInvoiceSender, callInfo)
	mock.lockInsertInvoiceSender.Unlock()
	return mock.InsertInvoiceSenderFunc(ctx, arg)
}

// InsertInvoiceSenderCalls gets all the calls that were made to InsertInvoiceSender.
// Check the length with:
//
//	len(mockedQuerier.InsertInvoiceSenderCalls())
func (mock *QuerierMock) InsertInvoiceSenderCalls() []struct {
	Ctx context.Context
	Arg db.InsertInvoiceSenderParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertInvoiceSenderParams
	}
	mock.lockInsertInvoiceSender.RLock()
	calls = mock.calls.InsertInvoiceSender
	mock.lockInsertInvoiceSender.RUnlock()
	return calls
}

// InsertUserGameBet calls InsertUserGameBetFunc.
func (mock *QuerierMock) InsertUserGameBet(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error) {
	if mock.InsertUserGameBetFunc == nil {
		panic("QuerierMock.InsertUserGameBetFunc: method is nil but Querier.InsertUserGameBet was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertUserGameBetParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertUserGameBet.Lock()
	mock.calls.InsertUserGameBet = append(mock.calls.InsertUserGameBet, callInfo)
	mock.lockInsertUserGameBet.Unlock()
	return mock.InsertUserGameBetFunc(ctx, arg)
}

// InsertUserGameBetCalls gets all the calls that were made to InsertUserGameBet.
// Check the length with:
//
//	len(mockedQuerier.InsertUserGameBetCalls())
func (mock *QuerierMock) InsertUserGameBetCalls() []struct {
	Ctx context.Context
	Arg db.InsertUserGameBetParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertUserGameBetParams
	}
	mock.lockInsertUserGameBet.RLock()
	calls = mock.calls.InsertUserGameBet
	mock.lockInsertUserGameBet.RUnlock()
	return calls
}

// ListInvoiceClients calls ListInvoiceClientsFunc.
func (mock *QuerierMock) ListInvoiceClients(ctx context.Context) ([]db.SourceInvoiceClient, error) {
	if mock.ListInvoiceClientsFunc == nil {
		panic("QuerierMock.ListInvoiceClientsFunc: method is nil but Querier.ListInvoiceClients was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListInvoiceClients.Lock()
	mock.calls.ListInvoiceClients = append(mock.calls.ListInvoiceClients, callInfo)
	mock.lockListInvoiceClients.Unlock()
	return mock.ListInvoiceClientsFunc(ctx)
}

// ListInvoiceClientsCalls gets all the calls that were made to ListInvoiceClients.
// Check the length with:
//
//	len(mockedQuerier.ListInvoiceClientsCalls())
func (mock *QuerierMock) ListInvoiceClientsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListInvoiceClients.RLock()
	calls = mock.calls.ListInvoiceClients
	mock.lockListInvoiceClients.RUnlock()
	return calls
}

// ListInvoicePaymentInfo calls ListInvoicePaymentInfoFunc.
func (mock *QuerierMock) ListInvoicePaymentInfo(ctx context.Context) ([]db.SourceInvoicePaymentInfo, error) {
	if mock.ListInvoicePaymentInfoFunc == nil {
		panic("QuerierMock.ListInvoicePaymentInfoFunc: method is nil but Querier.ListInvoicePaymentInfo was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListInvoicePaymentInfo.Lock()
	mock.calls.ListInvoicePaymentInfo = append(mock.calls.ListInvoicePaymentInfo, callInfo)
	mock.lockListInvoicePaymentInfo.Unlock()
	return mock.ListInvoicePaymentInfoFunc(ctx)
}

// ListInvoicePaymentInfoCalls gets all the calls that were made to ListInvoicePaymentInfo.
// Check the length with:
//
//	len(mockedQuerier.ListInvoicePaymentInfoCalls())
func (mock *QuerierMock) ListInvoicePaymentInfoCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListInvoicePaymentInfo.RLock()
	calls = mock.calls.ListInvoicePaymentInfo
	mock.lockListInvoicePaymentInfo.RUnlock()
	return calls
}

// ListInvoiceSenders calls ListInvoiceSendersFunc.
func (mock *QuerierMock) ListInvoiceSenders(ctx context.Context) ([]db.SourceInvoiceSender, error) {
	if mock.ListInvoiceSendersFunc == nil {
		panic("QuerierMock.ListInvoiceSendersFunc: method is nil but Querier.ListInvoiceSenders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListInvoiceSenders.Lock()
	mock.calls.ListInvoiceSenders = append(mock.calls.ListInvoiceSenders, callInfo)
	mock.lockListInvoiceSenders.Unlock()
	return mock.ListInvoiceSendersFunc(ctx)
}

// ListInvoiceSendersCalls gets all the calls that were made to ListInvoiceSenders.
// Check the length with:
//
//	len(mockedQuerier.ListInvoiceSendersCalls())
func (mock *QuerierMock) ListInvoiceSendersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListInvoiceSenders.RLock()
	calls = mock.calls.ListInvoiceSenders
	mock.lockListInvoiceSenders.RUnlock()
	return calls
}

// UpdateUserTimezone calls UpdateUserTimezoneFunc.
func (mock *QuerierMock) UpdateUserTimezone(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error) {
	if mock.UpdateUserTimezoneFunc == nil {
		panic("QuerierMock.UpdateUserTimezoneFunc: method is nil but Querier.UpdateUserTimezone was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateUserTimezoneParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateUserTimezone.Lock()
	mock.calls.UpdateUserTimezone = append(mock.calls.UpdateUserTimezone, callInfo)
	mock.lockUpdateUserTimezone.Unlock()
	return mock.UpdateUserTimezoneFunc(ctx, arg)
}

// UpdateUserTimezoneCalls gets all the calls that were made to UpdateUserTimezone.
// Check the length with:
//
//	len(mockedQuerier.UpdateUserTimezoneCalls())
func (mock *QuerierMock) UpdateUserTimezoneCalls() []struct {
	Ctx context.Context
	Arg db.UpdateUserTimezoneParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateUserTimezoneParams
	}
	mock.lockUpdateUserTimezone.RLock()
	calls = mock.calls.UpdateUserTimezone
	mock.lockUpdateUserTimezone.RUnlock()
	return calls
}

// UpsertRuntimeConfigValue calls UpsertRuntimeConfigValueFunc.
func (mock *QuerierMock) UpsertRuntimeConfigValue(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error) {
	if mock.UpsertRuntimeConfigValueFunc == nil {
		panic("QuerierMock.UpsertRuntimeConfigValueFunc: method is nil but Querier.UpsertRuntimeConfigValue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertRuntimeConfigValueParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertRuntimeConfigValue.Lock()
	mock.calls.UpsertRuntimeConfigValue = append(mock.calls.UpsertRuntimeConfigValue, callInfo)
	mock.lockUpsertRuntimeConfigValue.Unlock()
	return mock.UpsertRuntimeConfigValueFunc(ctx, arg)
}

// UpsertRuntimeConfigValueCalls gets all the calls that were made to UpsertRuntimeConfigValue.
// Check the length with:
//
//	len(mockedQuerier.UpsertRuntimeConfigValueCalls())
func (mock *QuerierMock) UpsertRuntimeConfigValueCalls() []struct {
	Ctx context.Context
	Arg db.UpsertRuntimeConfigValueParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertRuntimeConfigValueParams
	}
	mock.lockUpsertRuntimeConfigValue.RLock()
	calls = mock.calls.UpsertRuntimeConfigValue
	mock.lockUpsertRuntimeConfigValue.RUnlock()
	return calls
}

// UpsertUserGameBalance calls UpsertUserGameBalanceFunc.
func (mock *QuerierMock) UpsertUserGameBalance(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error) {
	if mock.UpsertUserGameBalanceFunc == nil {
		panic("QuerierMock.UpsertUserGameBalanceFunc: method is nil but Querier.UpsertUserGameBalance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertUserGameBalanceParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertUserGameBalance.Lock()
	mock.calls.UpsertUserGameBalance = append(mock.calls.UpsertUserGameBalance, callInfo)
	mock.lockUpsertUserGameBalance.Unlock()
	return mock.UpsertUserGameBalanceFunc(ctx, arg)
}

// UpsertUserGameBalanceCalls gets all the calls that were made to UpsertUserGameBalance.
// Check the length with:
//
//	len(mockedQuerier.UpsertUserGameBalanceCalls())
func (mock *QuerierMock) UpsertUserGameBalanceCalls() []struct {
	Ctx context.Context
	Arg db.UpsertUserGameBalanceParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertUserGameBalanceParams
	}
	mock.lockUpsertUserGameBalance.RLock()
	calls = mock.calls.UpsertUserGameBalance
	mock.lockUpsertUserGameBalance.RUnlock()
	return calls
}
