// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/jyablonski/lotus/internal/db"
	"sync"
)

// Ensure, that QuerierMock does implement db.Querier.
// If this is not the case, regenerate this file with moq.
var _ db.Querier = &QuerierMock{}

// QuerierMock is a mock implementation of db.Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked db.Querier
//		mockedQuerier := &QuerierMock{
//			CreateJournalFunc: func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
//				panic("mock out the CreateJournal method")
//			},
//			CreateUserFunc: func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
//				panic("mock out the CreateUser method")
//			},
//			CreateUserOauthFunc: func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
//				panic("mock out the CreateUserOauth method")
//			},
//			GetJournalByIdFunc: func(ctx context.Context, id int32) (db.SourceJournal, error) {
//				panic("mock out the GetJournalById method")
//			},
//			GetJournalCountByUserIdFunc: func(ctx context.Context, userID uuid.UUID) (int64, error) {
//				panic("mock out the GetJournalCountByUserId method")
//			},
//			GetJournalsByUserIdFunc: func(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserId method")
//			},
//			GetJournalsByUserIdPaginatedFunc: func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserIdPaginated method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (db.SourceUser, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIdFunc: func(ctx context.Context, id uuid.UUID) (db.SourceUser, error) {
//				panic("mock out the GetUserById method")
//			},
//			GetUserJournalSummaryByUserIdFunc: func(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error) {
//				panic("mock out the GetUserJournalSummaryByUserId method")
//			},
//		}
//
//		// use mockedQuerier in code that requires db.Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CreateJournalFunc mocks the CreateJournal method.
	CreateJournalFunc func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error)

	// CreateUserOauthFunc mocks the CreateUserOauth method.
	CreateUserOauthFunc func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error)

	// GetJournalByIdFunc mocks the GetJournalById method.
	GetJournalByIdFunc func(ctx context.Context, id int32) (db.SourceJournal, error)

	// GetJournalCountByUserIdFunc mocks the GetJournalCountByUserId method.
	GetJournalCountByUserIdFunc func(ctx context.Context, userID uuid.UUID) (int64, error)

	// GetJournalsByUserIdFunc mocks the GetJournalsByUserId method.
	GetJournalsByUserIdFunc func(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error)

	// GetJournalsByUserIdPaginatedFunc mocks the GetJournalsByUserIdPaginated method.
	GetJournalsByUserIdPaginatedFunc func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (db.SourceUser, error)

	// GetUserByIdFunc mocks the GetUserById method.
	GetUserByIdFunc func(ctx context.Context, id uuid.UUID) (db.SourceUser, error)

	// GetUserJournalSummaryByUserIdFunc mocks the GetUserJournalSummaryByUserId method.
	GetUserJournalSummaryByUserIdFunc func(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateJournal holds details about calls to the CreateJournal method.
		CreateJournal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateJournalParams
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserParams
		}
		// CreateUserOauth holds details about calls to the CreateUserOauth method.
		CreateUserOauth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserOauthParams
		}
		// GetJournalById holds details about calls to the GetJournalById method.
		GetJournalById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int32
		}
		// GetJournalCountByUserId holds details about calls to the GetJournalCountByUserId method.
		GetJournalCountByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetJournalsByUserId holds details about calls to the GetJournalsByUserId method.
		GetJournalsByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetJournalsByUserIdPaginated holds details about calls to the GetJournalsByUserIdPaginated method.
		GetJournalsByUserIdPaginated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetJournalsByUserIdPaginatedParams
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserById holds details about calls to the GetUserById method.
		GetUserById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetUserJournalSummaryByUserId holds details about calls to the GetUserJournalSummaryByUserId method.
		GetUserJournalSummaryByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockCreateJournal                 sync.RWMutex
	lockCreateUser                    sync.RWMutex
	lockCreateUserOauth               sync.RWMutex
	lockGetJournalById                sync.RWMutex
	lockGetJournalCountByUserId       sync.RWMutex
	lockGetJournalsByUserId           sync.RWMutex
	lockGetJournalsByUserIdPaginated  sync.RWMutex
	lockGetUserByEmail                sync.RWMutex
	lockGetUserById                   sync.RWMutex
	lockGetUserJournalSummaryByUserId sync.RWMutex
}

// CreateJournal calls CreateJournalFunc.
func (mock *QuerierMock) CreateJournal(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
	if mock.CreateJournalFunc == nil {
		panic("QuerierMock.CreateJournalFunc: method is nil but Querier.CreateJournal was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateJournal.Lock()
	mock.calls.CreateJournal = append(mock.calls.CreateJournal, callInfo)
	mock.lockCreateJournal.Unlock()
	return mock.CreateJournalFunc(ctx, arg)
}

// CreateJournalCalls gets all the calls that were made to CreateJournal.
// Check the length with:
//
//	len(mockedQuerier.CreateJournalCalls())
func (mock *QuerierMock) CreateJournalCalls() []struct {
	Ctx context.Context
	Arg db.CreateJournalParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}
	mock.lockCreateJournal.RLock()
	calls = mock.calls.CreateJournal
	mock.lockCreateJournal.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *QuerierMock) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
	if mock.CreateUserFunc == nil {
		panic("QuerierMock.CreateUserFunc: method is nil but Querier.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, arg)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedQuerier.CreateUserCalls())
func (mock *QuerierMock) CreateUserCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// CreateUserOauth calls CreateUserOauthFunc.
func (mock *QuerierMock) CreateUserOauth(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
	if mock.CreateUserOauthFunc == nil {
		panic("QuerierMock.CreateUserOauthFunc: method is nil but Querier.CreateUserOauth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUserOauth.Lock()
	mock.calls.CreateUserOauth = append(mock.calls.CreateUserOauth, callInfo)
	mock.lockCreateUserOauth.Unlock()
	return mock.CreateUserOauthFunc(ctx, arg)
}

// CreateUserOauthCalls gets all the calls that were made to CreateUserOauth.
// Check the length with:
//
//	len(mockedQuerier.CreateUserOauthCalls())
func (mock *QuerierMock) CreateUserOauthCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserOauthParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}
	mock.lockCreateUserOauth.RLock()
	calls = mock.calls.CreateUserOauth
	mock.lockCreateUserOauth.RUnlock()
	return calls
}

// GetJournalById calls GetJournalByIdFunc.
func (mock *QuerierMock) GetJournalById(ctx context.Context, id int32) (db.SourceJournal, error) {
	if mock.GetJournalByIdFunc == nil {
		panic("QuerierMock.GetJournalByIdFunc: method is nil but Querier.GetJournalById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int32
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJournalById.Lock()
	mock.calls.GetJournalById = append(mock.calls.GetJournalById, callInfo)
	mock.lockGetJournalById.Unlock()
	return mock.GetJournalByIdFunc(ctx, id)
}

// GetJournalByIdCalls gets all the calls that were made to GetJournalById.
// Check the length with:
//
//	len(mockedQuerier.GetJournalByIdCalls())
func (mock *QuerierMock) GetJournalByIdCalls() []struct {
	Ctx context.Context
	ID  int32
} {
	var calls []struct {
		Ctx context.Context
		ID  int32
	}
	mock.lockGetJournalById.RLock()
	calls = mock.calls.GetJournalById
	mock.lockGetJournalById.RUnlock()
	return calls
}

// GetJournalCountByUserId calls GetJournalCountByUserIdFunc.
func (mock *QuerierMock) GetJournalCountByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	if mock.GetJournalCountByUserIdFunc == nil {
		panic("QuerierMock.GetJournalCountByUserIdFunc: method is nil but Querier.GetJournalCountByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalCountByUserId.Lock()
	mock.calls.GetJournalCountByUserId = append(mock.calls.GetJournalCountByUserId, callInfo)
	mock.lockGetJournalCountByUserId.Unlock()
	return mock.GetJournalCountByUserIdFunc(ctx, userID)
}

// GetJournalCountByUserIdCalls gets all the calls that were made to GetJournalCountByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalCountByUserIdCalls())
func (mock *QuerierMock) GetJournalCountByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetJournalCountByUserId.RLock()
	calls = mock.calls.GetJournalCountByUserId
	mock.lockGetJournalCountByUserId.RUnlock()
	return calls
}

// GetJournalsByUserId calls GetJournalsByUserIdFunc.
func (mock *QuerierMock) GetJournalsByUserId(ctx context.Context, userID uuid.UUID) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdFunc: method is nil but Querier.GetJournalsByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalsByUserId.Lock()
	mock.calls.GetJournalsByUserId = append(mock.calls.GetJournalsByUserId, callInfo)
	mock.lockGetJournalsByUserId.Unlock()
	return mock.GetJournalsByUserIdFunc(ctx, userID)
}

// GetJournalsByUserIdCalls gets all the calls that were made to GetJournalsByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdCalls())
func (mock *QuerierMock) GetJournalsByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetJournalsByUserId.RLock()
	calls = mock.calls.GetJournalsByUserId
	mock.lockGetJournalsByUserId.RUnlock()
	return calls
}

// GetJournalsByUserIdPaginated calls GetJournalsByUserIdPaginatedFunc.
func (mock *QuerierMock) GetJournalsByUserIdPaginated(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdPaginatedFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdPaginatedFunc: method is nil but Querier.GetJournalsByUserIdPaginated was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetJournalsByUserIdPaginated.Lock()
	mock.calls.GetJournalsByUserIdPaginated = append(mock.calls.GetJournalsByUserIdPaginated, callInfo)
	mock.lockGetJournalsByUserIdPaginated.Unlock()
	return mock.GetJournalsByUserIdPaginatedFunc(ctx, arg)
}

// GetJournalsByUserIdPaginatedCalls gets all the calls that were made to GetJournalsByUserIdPaginated.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdPaginatedCalls())
func (mock *QuerierMock) GetJournalsByUserIdPaginatedCalls() []struct {
	Ctx context.Context
	Arg db.GetJournalsByUserIdPaginatedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}
	mock.lockGetJournalsByUserIdPaginated.RLock()
	calls = mock.calls.GetJournalsByUserIdPaginated
	mock.lockGetJournalsByUserIdPaginated.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *QuerierMock) GetUserByEmail(ctx context.Context, email string) (db.SourceUser, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("QuerierMock.GetUserByEmailFunc: method is nil but Querier.GetUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedQuerier.GetUserByEmailCalls())
func (mock *QuerierMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserById calls GetUserByIdFunc.
func (mock *QuerierMock) GetUserById(ctx context.Context, id uuid.UUID) (db.SourceUser, error) {
	if mock.GetUserByIdFunc == nil {
		panic("QuerierMock.GetUserByIdFunc: method is nil but Querier.GetUserById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserById.Lock()
	mock.calls.GetUserById = append(mock.calls.GetUserById, callInfo)
	mock.lockGetUserById.Unlock()
	return mock.GetUserByIdFunc(ctx, id)
}

// GetUserByIdCalls gets all the calls that were made to GetUserById.
// Check the length with:
//
//	len(mockedQuerier.GetUserByIdCalls())
func (mock *QuerierMock) GetUserByIdCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserById.RLock()
	calls = mock.calls.GetUserById
	mock.lockGetUserById.RUnlock()
	return calls
}

// GetUserJournalSummaryByUserId calls GetUserJournalSummaryByUserIdFunc.
func (mock *QuerierMock) GetUserJournalSummaryByUserId(ctx context.Context, userID uuid.UUID) (db.GoldUserJournalSummary, error) {
	if mock.GetUserJournalSummaryByUserIdFunc == nil {
		panic("QuerierMock.GetUserJournalSummaryByUserIdFunc: method is nil but Querier.GetUserJournalSummaryByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserJournalSummaryByUserId.Lock()
	mock.calls.GetUserJournalSummaryByUserId = append(mock.calls.GetUserJournalSummaryByUserId, callInfo)
	mock.lockGetUserJournalSummaryByUserId.Unlock()
	return mock.GetUserJournalSummaryByUserIdFunc(ctx, userID)
}

// GetUserJournalSummaryByUserIdCalls gets all the calls that were made to GetUserJournalSummaryByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetUserJournalSummaryByUserIdCalls())
func (mock *QuerierMock) GetUserJournalSummaryByUserIdCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetUserJournalSummaryByUserId.RLock()
	calls = mock.calls.GetUserJournalSummaryByUserId
	mock.lockGetUserJournalSummaryByUserId.RUnlock()
	return calls
}
