// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jyablonski/lotus/internal/db"
	"sync"
)

// Ensure, that QuerierMock does implement db.Querier.
// If this is not the case, regenerate this file with moq.
var _ db.Querier = &QuerierMock{}

// QuerierMock is a mock implementation of db.Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked db.Querier
//		mockedQuerier := &QuerierMock{
//			CreateJournalFunc: func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
//				panic("mock out the CreateJournal method")
//			},
//			CreateJournalExportFunc: func(ctx context.Context, arg db.CreateJournalExportParams) (db.SourceJournalExport, error) {
//				panic("mock out the CreateJournalExport method")
//			},
//			CreateUserFunc: func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
//				panic("mock out the CreateUser method")
//			},
//			CreateUserOauthFunc: func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
//				panic("mock out the CreateUserOauth method")
//			},
//			DeleteCommunityMoodRollupsForBucketFunc: func(ctx context.Context, arg db.DeleteCommunityMoodRollupsForBucketParams) error {
//				panic("mock out the DeleteCommunityMoodRollupsForBucket method")
//			},
//			DeleteCommunityPromptSetsForBucketFunc: func(ctx context.Context, arg db.DeleteCommunityPromptSetsForBucketParams) error {
//				panic("mock out the DeleteCommunityPromptSetsForBucket method")
//			},
//			DeleteCommunitySummariesForBucketFunc: func(ctx context.Context, arg db.DeleteCommunitySummariesForBucketParams) error {
//				panic("mock out the DeleteCommunitySummariesForBucket method")
//			},
//			DeleteCommunityThemeRollupsForBucketFunc: func(ctx context.Context, arg db.DeleteCommunityThemeRollupsForBucketParams) error {
//				panic("mock out the DeleteCommunityThemeRollupsForBucket method")
//			},
//			DeleteJournalForUserFunc: func(ctx context.Context, arg db.DeleteJournalForUserParams) (int64, error) {
//				panic("mock out the DeleteJournalForUser method")
//			},
//			DeleteUserByIdFunc: func(ctx context.Context, id pgtype.UUID) error {
//				panic("mock out the DeleteUserById method")
//			},
//			GetActiveFeatureFlagsFunc: func(ctx context.Context) ([]db.SourceWaffleFlag, error) {
//				panic("mock out the GetActiveFeatureFlags method")
//			},
//			GetActiveMLModelFunc: func(ctx context.Context, mlModel string) (bool, error) {
//				panic("mock out the GetActiveMLModel method")
//			},
//			GetCommunityProjectionSourceByJournalIdFunc: func(ctx context.Context, id int32) (db.GetCommunityProjectionSourceByJournalIdRow, error) {
//				panic("mock out the GetCommunityProjectionSourceByJournalId method")
//			},
//			GetCommunityPromptSetByBucketAndScopeFunc: func(ctx context.Context, arg db.GetCommunityPromptSetByBucketAndScopeParams) (db.SourceCommunityPromptSet, error) {
//				panic("mock out the GetCommunityPromptSetByBucketAndScope method")
//			},
//			GetCommunitySettingsByUserIdFunc: func(ctx context.Context, id pgtype.UUID) (db.GetCommunitySettingsByUserIdRow, error) {
//				panic("mock out the GetCommunitySettingsByUserId method")
//			},
//			GetCommunitySummaryByBucketAndScopeFunc: func(ctx context.Context, arg db.GetCommunitySummaryByBucketAndScopeParams) (db.SourceCommunitySummary, error) {
//				panic("mock out the GetCommunitySummaryByBucketAndScope method")
//			},
//			GetFeatureFlagByNameFunc: func(ctx context.Context, name string) (db.SourceWaffleFlag, error) {
//				panic("mock out the GetFeatureFlagByName method")
//			},
//			GetJournalByIdFunc: func(ctx context.Context, id int32) (db.SourceJournal, error) {
//				panic("mock out the GetJournalById method")
//			},
//			GetJournalCommunityProjectionByJournalIdFunc: func(ctx context.Context, journalID int32) (db.SourceJournalCommunityProjection, error) {
//				panic("mock out the GetJournalCommunityProjectionByJournalId method")
//			},
//			GetJournalCountByUserIdFunc: func(ctx context.Context, userID pgtype.UUID) (int64, error) {
//				panic("mock out the GetJournalCountByUserId method")
//			},
//			GetJournalExportFunc: func(ctx context.Context, arg db.GetJournalExportParams) (db.SourceJournalExport, error) {
//				panic("mock out the GetJournalExport method")
//			},
//			GetJournalsByUserIdFunc: func(ctx context.Context, userID pgtype.UUID) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserId method")
//			},
//			GetJournalsByUserIdPaginatedFunc: func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
//				panic("mock out the GetJournalsByUserIdPaginated method")
//			},
//			GetMoodRollupsByBucketAndScopeFunc: func(ctx context.Context, arg db.GetMoodRollupsByBucketAndScopeParams) ([]db.SourceCommunityMoodRollup, error) {
//				panic("mock out the GetMoodRollupsByBucketAndScope method")
//			},
//			GetRuntimeConfigByKeyFunc: func(ctx context.Context, key string) (db.SourceRuntimeConfig, error) {
//				panic("mock out the GetRuntimeConfigByKey method")
//			},
//			GetThemeRollupsByBucketAndScopeFunc: func(ctx context.Context, arg db.GetThemeRollupsByBucketAndScopeParams) ([]db.SourceCommunityThemeRollup, error) {
//				panic("mock out the GetThemeRollupsByBucketAndScope method")
//			},
//			GetTopicsByJournalIdsFunc: func(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error) {
//				panic("mock out the GetTopicsByJournalIds method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (db.SourceUser, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIdFunc: func(ctx context.Context, id pgtype.UUID) (db.SourceUser, error) {
//				panic("mock out the GetUserById method")
//			},
//			GetUserGameBalanceFunc: func(ctx context.Context, userID pgtype.UUID) (db.SourceUserGameBalance, error) {
//				panic("mock out the GetUserGameBalance method")
//			},
//			GetUserGameBetsFunc: func(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error) {
//				panic("mock out the GetUserGameBets method")
//			},
//			GetUserJournalSummaryByUserIdFunc: func(ctx context.Context, userID pgtype.UUID) (db.GoldUserJournalSummary, error) {
//				panic("mock out the GetUserJournalSummaryByUserId method")
//			},
//			InsertUserGameBetFunc: func(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error) {
//				panic("mock out the InsertUserGameBet method")
//			},
//			ListCommunityRepairJournalIdsFunc: func(ctx context.Context, createdAt pgtype.Timestamp) ([]int32, error) {
//				panic("mock out the ListCommunityRepairJournalIds method")
//			},
//			ListEligibleCommunityProjectionsByDateRangeFunc: func(ctx context.Context, arg db.ListEligibleCommunityProjectionsByDateRangeParams) ([]db.SourceJournalCommunityProjection, error) {
//				panic("mock out the ListEligibleCommunityProjectionsByDateRange method")
//			},
//			SearchJournalsKeywordFunc: func(ctx context.Context, arg db.SearchJournalsKeywordParams) ([]db.SearchJournalsKeywordRow, error) {
//				panic("mock out the SearchJournalsKeyword method")
//			},
//			SearchJournalsSemanticFunc: func(ctx context.Context, arg db.SearchJournalsSemanticParams) ([]db.SearchJournalsSemanticRow, error) {
//				panic("mock out the SearchJournalsSemantic method")
//			},
//			UpdateCommunitySettingsByUserIdFunc: func(ctx context.Context, arg db.UpdateCommunitySettingsByUserIdParams) (db.SourceUser, error) {
//				panic("mock out the UpdateCommunitySettingsByUserId method")
//			},
//			UpdateJournalExportCompleteFunc: func(ctx context.Context, arg db.UpdateJournalExportCompleteParams) (db.SourceJournalExport, error) {
//				panic("mock out the UpdateJournalExportComplete method")
//			},
//			UpdateJournalExportFailedFunc: func(ctx context.Context, arg db.UpdateJournalExportFailedParams) (db.SourceJournalExport, error) {
//				panic("mock out the UpdateJournalExportFailed method")
//			},
//			UpdateJournalExportProcessingFunc: func(ctx context.Context, id pgtype.UUID) (db.SourceJournalExport, error) {
//				panic("mock out the UpdateJournalExportProcessing method")
//			},
//			UpdateJournalForUserFunc: func(ctx context.Context, arg db.UpdateJournalForUserParams) (int64, error) {
//				panic("mock out the UpdateJournalForUser method")
//			},
//			UpdateUserTimezoneFunc: func(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error) {
//				panic("mock out the UpdateUserTimezone method")
//			},
//			UpsertCommunityMoodRollupFunc: func(ctx context.Context, arg db.UpsertCommunityMoodRollupParams) (db.SourceCommunityMoodRollup, error) {
//				panic("mock out the UpsertCommunityMoodRollup method")
//			},
//			UpsertCommunityPromptSetFunc: func(ctx context.Context, arg db.UpsertCommunityPromptSetParams) (db.SourceCommunityPromptSet, error) {
//				panic("mock out the UpsertCommunityPromptSet method")
//			},
//			UpsertCommunitySummaryFunc: func(ctx context.Context, arg db.UpsertCommunitySummaryParams) (db.SourceCommunitySummary, error) {
//				panic("mock out the UpsertCommunitySummary method")
//			},
//			UpsertCommunityThemeRollupFunc: func(ctx context.Context, arg db.UpsertCommunityThemeRollupParams) (db.SourceCommunityThemeRollup, error) {
//				panic("mock out the UpsertCommunityThemeRollup method")
//			},
//			UpsertJournalCommunityProjectionFunc: func(ctx context.Context, arg db.UpsertJournalCommunityProjectionParams) (db.SourceJournalCommunityProjection, error) {
//				panic("mock out the UpsertJournalCommunityProjection method")
//			},
//			UpsertRuntimeConfigValueFunc: func(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error) {
//				panic("mock out the UpsertRuntimeConfigValue method")
//			},
//			UpsertUserGameBalanceFunc: func(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error) {
//				panic("mock out the UpsertUserGameBalance method")
//			},
//		}
//
//		// use mockedQuerier in code that requires db.Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CreateJournalFunc mocks the CreateJournal method.
	CreateJournalFunc func(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error)

	// CreateJournalExportFunc mocks the CreateJournalExport method.
	CreateJournalExportFunc func(ctx context.Context, arg db.CreateJournalExportParams) (db.SourceJournalExport, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error)

	// CreateUserOauthFunc mocks the CreateUserOauth method.
	CreateUserOauthFunc func(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error)

	// DeleteCommunityMoodRollupsForBucketFunc mocks the DeleteCommunityMoodRollupsForBucket method.
	DeleteCommunityMoodRollupsForBucketFunc func(ctx context.Context, arg db.DeleteCommunityMoodRollupsForBucketParams) error

	// DeleteCommunityPromptSetsForBucketFunc mocks the DeleteCommunityPromptSetsForBucket method.
	DeleteCommunityPromptSetsForBucketFunc func(ctx context.Context, arg db.DeleteCommunityPromptSetsForBucketParams) error

	// DeleteCommunitySummariesForBucketFunc mocks the DeleteCommunitySummariesForBucket method.
	DeleteCommunitySummariesForBucketFunc func(ctx context.Context, arg db.DeleteCommunitySummariesForBucketParams) error

	// DeleteCommunityThemeRollupsForBucketFunc mocks the DeleteCommunityThemeRollupsForBucket method.
	DeleteCommunityThemeRollupsForBucketFunc func(ctx context.Context, arg db.DeleteCommunityThemeRollupsForBucketParams) error

	// DeleteJournalForUserFunc mocks the DeleteJournalForUser method.
	DeleteJournalForUserFunc func(ctx context.Context, arg db.DeleteJournalForUserParams) (int64, error)

	// DeleteUserByIdFunc mocks the DeleteUserById method.
	DeleteUserByIdFunc func(ctx context.Context, id pgtype.UUID) error

	// GetActiveFeatureFlagsFunc mocks the GetActiveFeatureFlags method.
	GetActiveFeatureFlagsFunc func(ctx context.Context) ([]db.SourceWaffleFlag, error)

	// GetActiveMLModelFunc mocks the GetActiveMLModel method.
	GetActiveMLModelFunc func(ctx context.Context, mlModel string) (bool, error)

	// GetCommunityProjectionSourceByJournalIdFunc mocks the GetCommunityProjectionSourceByJournalId method.
	GetCommunityProjectionSourceByJournalIdFunc func(ctx context.Context, id int32) (db.GetCommunityProjectionSourceByJournalIdRow, error)

	// GetCommunityPromptSetByBucketAndScopeFunc mocks the GetCommunityPromptSetByBucketAndScope method.
	GetCommunityPromptSetByBucketAndScopeFunc func(ctx context.Context, arg db.GetCommunityPromptSetByBucketAndScopeParams) (db.SourceCommunityPromptSet, error)

	// GetCommunitySettingsByUserIdFunc mocks the GetCommunitySettingsByUserId method.
	GetCommunitySettingsByUserIdFunc func(ctx context.Context, id pgtype.UUID) (db.GetCommunitySettingsByUserIdRow, error)

	// GetCommunitySummaryByBucketAndScopeFunc mocks the GetCommunitySummaryByBucketAndScope method.
	GetCommunitySummaryByBucketAndScopeFunc func(ctx context.Context, arg db.GetCommunitySummaryByBucketAndScopeParams) (db.SourceCommunitySummary, error)

	// GetFeatureFlagByNameFunc mocks the GetFeatureFlagByName method.
	GetFeatureFlagByNameFunc func(ctx context.Context, name string) (db.SourceWaffleFlag, error)

	// GetJournalByIdFunc mocks the GetJournalById method.
	GetJournalByIdFunc func(ctx context.Context, id int32) (db.SourceJournal, error)

	// GetJournalCommunityProjectionByJournalIdFunc mocks the GetJournalCommunityProjectionByJournalId method.
	GetJournalCommunityProjectionByJournalIdFunc func(ctx context.Context, journalID int32) (db.SourceJournalCommunityProjection, error)

	// GetJournalCountByUserIdFunc mocks the GetJournalCountByUserId method.
	GetJournalCountByUserIdFunc func(ctx context.Context, userID pgtype.UUID) (int64, error)

	// GetJournalExportFunc mocks the GetJournalExport method.
	GetJournalExportFunc func(ctx context.Context, arg db.GetJournalExportParams) (db.SourceJournalExport, error)

	// GetJournalsByUserIdFunc mocks the GetJournalsByUserId method.
	GetJournalsByUserIdFunc func(ctx context.Context, userID pgtype.UUID) ([]db.SourceJournal, error)

	// GetJournalsByUserIdPaginatedFunc mocks the GetJournalsByUserIdPaginated method.
	GetJournalsByUserIdPaginatedFunc func(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error)

	// GetMoodRollupsByBucketAndScopeFunc mocks the GetMoodRollupsByBucketAndScope method.
	GetMoodRollupsByBucketAndScopeFunc func(ctx context.Context, arg db.GetMoodRollupsByBucketAndScopeParams) ([]db.SourceCommunityMoodRollup, error)

	// GetRuntimeConfigByKeyFunc mocks the GetRuntimeConfigByKey method.
	GetRuntimeConfigByKeyFunc func(ctx context.Context, key string) (db.SourceRuntimeConfig, error)

	// GetThemeRollupsByBucketAndScopeFunc mocks the GetThemeRollupsByBucketAndScope method.
	GetThemeRollupsByBucketAndScopeFunc func(ctx context.Context, arg db.GetThemeRollupsByBucketAndScopeParams) ([]db.SourceCommunityThemeRollup, error)

	// GetTopicsByJournalIdsFunc mocks the GetTopicsByJournalIds method.
	GetTopicsByJournalIdsFunc func(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (db.SourceUser, error)

	// GetUserByIdFunc mocks the GetUserById method.
	GetUserByIdFunc func(ctx context.Context, id pgtype.UUID) (db.SourceUser, error)

	// GetUserGameBalanceFunc mocks the GetUserGameBalance method.
	GetUserGameBalanceFunc func(ctx context.Context, userID pgtype.UUID) (db.SourceUserGameBalance, error)

	// GetUserGameBetsFunc mocks the GetUserGameBets method.
	GetUserGameBetsFunc func(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error)

	// GetUserJournalSummaryByUserIdFunc mocks the GetUserJournalSummaryByUserId method.
	GetUserJournalSummaryByUserIdFunc func(ctx context.Context, userID pgtype.UUID) (db.GoldUserJournalSummary, error)

	// InsertUserGameBetFunc mocks the InsertUserGameBet method.
	InsertUserGameBetFunc func(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error)

	// ListCommunityRepairJournalIdsFunc mocks the ListCommunityRepairJournalIds method.
	ListCommunityRepairJournalIdsFunc func(ctx context.Context, createdAt pgtype.Timestamp) ([]int32, error)

	// ListEligibleCommunityProjectionsByDateRangeFunc mocks the ListEligibleCommunityProjectionsByDateRange method.
	ListEligibleCommunityProjectionsByDateRangeFunc func(ctx context.Context, arg db.ListEligibleCommunityProjectionsByDateRangeParams) ([]db.SourceJournalCommunityProjection, error)

	// SearchJournalsKeywordFunc mocks the SearchJournalsKeyword method.
	SearchJournalsKeywordFunc func(ctx context.Context, arg db.SearchJournalsKeywordParams) ([]db.SearchJournalsKeywordRow, error)

	// SearchJournalsSemanticFunc mocks the SearchJournalsSemantic method.
	SearchJournalsSemanticFunc func(ctx context.Context, arg db.SearchJournalsSemanticParams) ([]db.SearchJournalsSemanticRow, error)

	// UpdateCommunitySettingsByUserIdFunc mocks the UpdateCommunitySettingsByUserId method.
	UpdateCommunitySettingsByUserIdFunc func(ctx context.Context, arg db.UpdateCommunitySettingsByUserIdParams) (db.SourceUser, error)

	// UpdateJournalExportCompleteFunc mocks the UpdateJournalExportComplete method.
	UpdateJournalExportCompleteFunc func(ctx context.Context, arg db.UpdateJournalExportCompleteParams) (db.SourceJournalExport, error)

	// UpdateJournalExportFailedFunc mocks the UpdateJournalExportFailed method.
	UpdateJournalExportFailedFunc func(ctx context.Context, arg db.UpdateJournalExportFailedParams) (db.SourceJournalExport, error)

	// UpdateJournalExportProcessingFunc mocks the UpdateJournalExportProcessing method.
	UpdateJournalExportProcessingFunc func(ctx context.Context, id pgtype.UUID) (db.SourceJournalExport, error)

	// UpdateJournalForUserFunc mocks the UpdateJournalForUser method.
	UpdateJournalForUserFunc func(ctx context.Context, arg db.UpdateJournalForUserParams) (int64, error)

	// UpdateUserTimezoneFunc mocks the UpdateUserTimezone method.
	UpdateUserTimezoneFunc func(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error)

	// UpsertCommunityMoodRollupFunc mocks the UpsertCommunityMoodRollup method.
	UpsertCommunityMoodRollupFunc func(ctx context.Context, arg db.UpsertCommunityMoodRollupParams) (db.SourceCommunityMoodRollup, error)

	// UpsertCommunityPromptSetFunc mocks the UpsertCommunityPromptSet method.
	UpsertCommunityPromptSetFunc func(ctx context.Context, arg db.UpsertCommunityPromptSetParams) (db.SourceCommunityPromptSet, error)

	// UpsertCommunitySummaryFunc mocks the UpsertCommunitySummary method.
	UpsertCommunitySummaryFunc func(ctx context.Context, arg db.UpsertCommunitySummaryParams) (db.SourceCommunitySummary, error)

	// UpsertCommunityThemeRollupFunc mocks the UpsertCommunityThemeRollup method.
	UpsertCommunityThemeRollupFunc func(ctx context.Context, arg db.UpsertCommunityThemeRollupParams) (db.SourceCommunityThemeRollup, error)

	// UpsertJournalCommunityProjectionFunc mocks the UpsertJournalCommunityProjection method.
	UpsertJournalCommunityProjectionFunc func(ctx context.Context, arg db.UpsertJournalCommunityProjectionParams) (db.SourceJournalCommunityProjection, error)

	// UpsertRuntimeConfigValueFunc mocks the UpsertRuntimeConfigValue method.
	UpsertRuntimeConfigValueFunc func(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error)

	// UpsertUserGameBalanceFunc mocks the UpsertUserGameBalance method.
	UpsertUserGameBalanceFunc func(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateJournal holds details about calls to the CreateJournal method.
		CreateJournal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateJournalParams
		}
		// CreateJournalExport holds details about calls to the CreateJournalExport method.
		CreateJournalExport []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateJournalExportParams
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserParams
		}
		// CreateUserOauth holds details about calls to the CreateUserOauth method.
		CreateUserOauth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.CreateUserOauthParams
		}
		// DeleteCommunityMoodRollupsForBucket holds details about calls to the DeleteCommunityMoodRollupsForBucket method.
		DeleteCommunityMoodRollupsForBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteCommunityMoodRollupsForBucketParams
		}
		// DeleteCommunityPromptSetsForBucket holds details about calls to the DeleteCommunityPromptSetsForBucket method.
		DeleteCommunityPromptSetsForBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteCommunityPromptSetsForBucketParams
		}
		// DeleteCommunitySummariesForBucket holds details about calls to the DeleteCommunitySummariesForBucket method.
		DeleteCommunitySummariesForBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteCommunitySummariesForBucketParams
		}
		// DeleteCommunityThemeRollupsForBucket holds details about calls to the DeleteCommunityThemeRollupsForBucket method.
		DeleteCommunityThemeRollupsForBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteCommunityThemeRollupsForBucketParams
		}
		// DeleteJournalForUser holds details about calls to the DeleteJournalForUser method.
		DeleteJournalForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteJournalForUserParams
		}
		// DeleteUserById holds details about calls to the DeleteUserById method.
		DeleteUserById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetActiveFeatureFlags holds details about calls to the GetActiveFeatureFlags method.
		GetActiveFeatureFlags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetActiveMLModel holds details about calls to the GetActiveMLModel method.
		GetActiveMLModel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MlModel is the mlModel argument value.
			MlModel string
		}
		// GetCommunityProjectionSourceByJournalId holds details about calls to the GetCommunityProjectionSourceByJournalId method.
		GetCommunityProjectionSourceByJournalId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int32
		}
		// GetCommunityPromptSetByBucketAndScope holds details about calls to the GetCommunityPromptSetByBucketAndScope method.
		GetCommunityPromptSetByBucketAndScope []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetCommunityPromptSetByBucketAndScopeParams
		}
		// GetCommunitySettingsByUserId holds details about calls to the GetCommunitySettingsByUserId method.
		GetCommunitySettingsByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetCommunitySummaryByBucketAndScope holds details about calls to the GetCommunitySummaryByBucketAndScope method.
		GetCommunitySummaryByBucketAndScope []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetCommunitySummaryByBucketAndScopeParams
		}
		// GetFeatureFlagByName holds details about calls to the GetFeatureFlagByName method.
		GetFeatureFlagByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetJournalById holds details about calls to the GetJournalById method.
		GetJournalById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int32
		}
		// GetJournalCommunityProjectionByJournalId holds details about calls to the GetJournalCommunityProjectionByJournalId method.
		GetJournalCommunityProjectionByJournalId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JournalID is the journalID argument value.
			JournalID int32
		}
		// GetJournalCountByUserId holds details about calls to the GetJournalCountByUserId method.
		GetJournalCountByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID pgtype.UUID
		}
		// GetJournalExport holds details about calls to the GetJournalExport method.
		GetJournalExport []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetJournalExportParams
		}
		// GetJournalsByUserId holds details about calls to the GetJournalsByUserId method.
		GetJournalsByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID pgtype.UUID
		}
		// GetJournalsByUserIdPaginated holds details about calls to the GetJournalsByUserIdPaginated method.
		GetJournalsByUserIdPaginated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetJournalsByUserIdPaginatedParams
		}
		// GetMoodRollupsByBucketAndScope holds details about calls to the GetMoodRollupsByBucketAndScope method.
		GetMoodRollupsByBucketAndScope []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetMoodRollupsByBucketAndScopeParams
		}
		// GetRuntimeConfigByKey holds details about calls to the GetRuntimeConfigByKey method.
		GetRuntimeConfigByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetThemeRollupsByBucketAndScope holds details about calls to the GetThemeRollupsByBucketAndScope method.
		GetThemeRollupsByBucketAndScope []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetThemeRollupsByBucketAndScopeParams
		}
		// GetTopicsByJournalIds holds details about calls to the GetTopicsByJournalIds method.
		GetTopicsByJournalIds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dollar_1 is the dollar_1 argument value.
			Dollar_1 []int32
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserById holds details about calls to the GetUserById method.
		GetUserById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetUserGameBalance holds details about calls to the GetUserGameBalance method.
		GetUserGameBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID pgtype.UUID
		}
		// GetUserGameBets holds details about calls to the GetUserGameBets method.
		GetUserGameBets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.GetUserGameBetsParams
		}
		// GetUserJournalSummaryByUserId holds details about calls to the GetUserJournalSummaryByUserId method.
		GetUserJournalSummaryByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID pgtype.UUID
		}
		// InsertUserGameBet holds details about calls to the InsertUserGameBet method.
		InsertUserGameBet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertUserGameBetParams
		}
		// ListCommunityRepairJournalIds holds details about calls to the ListCommunityRepairJournalIds method.
		ListCommunityRepairJournalIds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CreatedAt is the createdAt argument value.
			CreatedAt pgtype.Timestamp
		}
		// ListEligibleCommunityProjectionsByDateRange holds details about calls to the ListEligibleCommunityProjectionsByDateRange method.
		ListEligibleCommunityProjectionsByDateRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.ListEligibleCommunityProjectionsByDateRangeParams
		}
		// SearchJournalsKeyword holds details about calls to the SearchJournalsKeyword method.
		SearchJournalsKeyword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.SearchJournalsKeywordParams
		}
		// SearchJournalsSemantic holds details about calls to the SearchJournalsSemantic method.
		SearchJournalsSemantic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.SearchJournalsSemanticParams
		}
		// UpdateCommunitySettingsByUserId holds details about calls to the UpdateCommunitySettingsByUserId method.
		UpdateCommunitySettingsByUserId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateCommunitySettingsByUserIdParams
		}
		// UpdateJournalExportComplete holds details about calls to the UpdateJournalExportComplete method.
		UpdateJournalExportComplete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateJournalExportCompleteParams
		}
		// UpdateJournalExportFailed holds details about calls to the UpdateJournalExportFailed method.
		UpdateJournalExportFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateJournalExportFailedParams
		}
		// UpdateJournalExportProcessing holds details about calls to the UpdateJournalExportProcessing method.
		UpdateJournalExportProcessing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// UpdateJournalForUser holds details about calls to the UpdateJournalForUser method.
		UpdateJournalForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateJournalForUserParams
		}
		// UpdateUserTimezone holds details about calls to the UpdateUserTimezone method.
		UpdateUserTimezone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateUserTimezoneParams
		}
		// UpsertCommunityMoodRollup holds details about calls to the UpsertCommunityMoodRollup method.
		UpsertCommunityMoodRollup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertCommunityMoodRollupParams
		}
		// UpsertCommunityPromptSet holds details about calls to the UpsertCommunityPromptSet method.
		UpsertCommunityPromptSet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertCommunityPromptSetParams
		}
		// UpsertCommunitySummary holds details about calls to the UpsertCommunitySummary method.
		UpsertCommunitySummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertCommunitySummaryParams
		}
		// UpsertCommunityThemeRollup holds details about calls to the UpsertCommunityThemeRollup method.
		UpsertCommunityThemeRollup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertCommunityThemeRollupParams
		}
		// UpsertJournalCommunityProjection holds details about calls to the UpsertJournalCommunityProjection method.
		UpsertJournalCommunityProjection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertJournalCommunityProjectionParams
		}
		// UpsertRuntimeConfigValue holds details about calls to the UpsertRuntimeConfigValue method.
		UpsertRuntimeConfigValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertRuntimeConfigValueParams
		}
		// UpsertUserGameBalance holds details about calls to the UpsertUserGameBalance method.
		UpsertUserGameBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertUserGameBalanceParams
		}
	}
	lockCreateJournal                               sync.RWMutex
	lockCreateJournalExport                         sync.RWMutex
	lockCreateUser                                  sync.RWMutex
	lockCreateUserOauth                             sync.RWMutex
	lockDeleteCommunityMoodRollupsForBucket         sync.RWMutex
	lockDeleteCommunityPromptSetsForBucket          sync.RWMutex
	lockDeleteCommunitySummariesForBucket           sync.RWMutex
	lockDeleteCommunityThemeRollupsForBucket        sync.RWMutex
	lockDeleteJournalForUser                        sync.RWMutex
	lockDeleteUserById                              sync.RWMutex
	lockGetActiveFeatureFlags                       sync.RWMutex
	lockGetActiveMLModel                            sync.RWMutex
	lockGetCommunityProjectionSourceByJournalId     sync.RWMutex
	lockGetCommunityPromptSetByBucketAndScope       sync.RWMutex
	lockGetCommunitySettingsByUserId                sync.RWMutex
	lockGetCommunitySummaryByBucketAndScope         sync.RWMutex
	lockGetFeatureFlagByName                        sync.RWMutex
	lockGetJournalById                              sync.RWMutex
	lockGetJournalCommunityProjectionByJournalId    sync.RWMutex
	lockGetJournalCountByUserId                     sync.RWMutex
	lockGetJournalExport                            sync.RWMutex
	lockGetJournalsByUserId                         sync.RWMutex
	lockGetJournalsByUserIdPaginated                sync.RWMutex
	lockGetMoodRollupsByBucketAndScope              sync.RWMutex
	lockGetRuntimeConfigByKey                       sync.RWMutex
	lockGetThemeRollupsByBucketAndScope             sync.RWMutex
	lockGetTopicsByJournalIds                       sync.RWMutex
	lockGetUserByEmail                              sync.RWMutex
	lockGetUserById                                 sync.RWMutex
	lockGetUserGameBalance                          sync.RWMutex
	lockGetUserGameBets                             sync.RWMutex
	lockGetUserJournalSummaryByUserId               sync.RWMutex
	lockInsertUserGameBet                           sync.RWMutex
	lockListCommunityRepairJournalIds               sync.RWMutex
	lockListEligibleCommunityProjectionsByDateRange sync.RWMutex
	lockSearchJournalsKeyword                       sync.RWMutex
	lockSearchJournalsSemantic                      sync.RWMutex
	lockUpdateCommunitySettingsByUserId             sync.RWMutex
	lockUpdateJournalExportComplete                 sync.RWMutex
	lockUpdateJournalExportFailed                   sync.RWMutex
	lockUpdateJournalExportProcessing               sync.RWMutex
	lockUpdateJournalForUser                        sync.RWMutex
	lockUpdateUserTimezone                          sync.RWMutex
	lockUpsertCommunityMoodRollup                   sync.RWMutex
	lockUpsertCommunityPromptSet                    sync.RWMutex
	lockUpsertCommunitySummary                      sync.RWMutex
	lockUpsertCommunityThemeRollup                  sync.RWMutex
	lockUpsertJournalCommunityProjection            sync.RWMutex
	lockUpsertRuntimeConfigValue                    sync.RWMutex
	lockUpsertUserGameBalance                       sync.RWMutex
}

// CreateJournal calls CreateJournalFunc.
func (mock *QuerierMock) CreateJournal(ctx context.Context, arg db.CreateJournalParams) (db.SourceJournal, error) {
	if mock.CreateJournalFunc == nil {
		panic("QuerierMock.CreateJournalFunc: method is nil but Querier.CreateJournal was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateJournal.Lock()
	mock.calls.CreateJournal = append(mock.calls.CreateJournal, callInfo)
	mock.lockCreateJournal.Unlock()
	return mock.CreateJournalFunc(ctx, arg)
}

// CreateJournalCalls gets all the calls that were made to CreateJournal.
// Check the length with:
//
//	len(mockedQuerier.CreateJournalCalls())
func (mock *QuerierMock) CreateJournalCalls() []struct {
	Ctx context.Context
	Arg db.CreateJournalParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateJournalParams
	}
	mock.lockCreateJournal.RLock()
	calls = mock.calls.CreateJournal
	mock.lockCreateJournal.RUnlock()
	return calls
}

// CreateJournalExport calls CreateJournalExportFunc.
func (mock *QuerierMock) CreateJournalExport(ctx context.Context, arg db.CreateJournalExportParams) (db.SourceJournalExport, error) {
	if mock.CreateJournalExportFunc == nil {
		panic("QuerierMock.CreateJournalExportFunc: method is nil but Querier.CreateJournalExport was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateJournalExportParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateJournalExport.Lock()
	mock.calls.CreateJournalExport = append(mock.calls.CreateJournalExport, callInfo)
	mock.lockCreateJournalExport.Unlock()
	return mock.CreateJournalExportFunc(ctx, arg)
}

// CreateJournalExportCalls gets all the calls that were made to CreateJournalExport.
// Check the length with:
//
//	len(mockedQuerier.CreateJournalExportCalls())
func (mock *QuerierMock) CreateJournalExportCalls() []struct {
	Ctx context.Context
	Arg db.CreateJournalExportParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateJournalExportParams
	}
	mock.lockCreateJournalExport.RLock()
	calls = mock.calls.CreateJournalExport
	mock.lockCreateJournalExport.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *QuerierMock) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.SourceUser, error) {
	if mock.CreateUserFunc == nil {
		panic("QuerierMock.CreateUserFunc: method is nil but Querier.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, arg)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedQuerier.CreateUserCalls())
func (mock *QuerierMock) CreateUserCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserParams
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// CreateUserOauth calls CreateUserOauthFunc.
func (mock *QuerierMock) CreateUserOauth(ctx context.Context, arg db.CreateUserOauthParams) (db.SourceUser, error) {
	if mock.CreateUserOauthFunc == nil {
		panic("QuerierMock.CreateUserOauthFunc: method is nil but Querier.CreateUserOauth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUserOauth.Lock()
	mock.calls.CreateUserOauth = append(mock.calls.CreateUserOauth, callInfo)
	mock.lockCreateUserOauth.Unlock()
	return mock.CreateUserOauthFunc(ctx, arg)
}

// CreateUserOauthCalls gets all the calls that were made to CreateUserOauth.
// Check the length with:
//
//	len(mockedQuerier.CreateUserOauthCalls())
func (mock *QuerierMock) CreateUserOauthCalls() []struct {
	Ctx context.Context
	Arg db.CreateUserOauthParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.CreateUserOauthParams
	}
	mock.lockCreateUserOauth.RLock()
	calls = mock.calls.CreateUserOauth
	mock.lockCreateUserOauth.RUnlock()
	return calls
}

// DeleteCommunityMoodRollupsForBucket calls DeleteCommunityMoodRollupsForBucketFunc.
func (mock *QuerierMock) DeleteCommunityMoodRollupsForBucket(ctx context.Context, arg db.DeleteCommunityMoodRollupsForBucketParams) error {
	if mock.DeleteCommunityMoodRollupsForBucketFunc == nil {
		panic("QuerierMock.DeleteCommunityMoodRollupsForBucketFunc: method is nil but Querier.DeleteCommunityMoodRollupsForBucket was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteCommunityMoodRollupsForBucketParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteCommunityMoodRollupsForBucket.Lock()
	mock.calls.DeleteCommunityMoodRollupsForBucket = append(mock.calls.DeleteCommunityMoodRollupsForBucket, callInfo)
	mock.lockDeleteCommunityMoodRollupsForBucket.Unlock()
	return mock.DeleteCommunityMoodRollupsForBucketFunc(ctx, arg)
}

// DeleteCommunityMoodRollupsForBucketCalls gets all the calls that were made to DeleteCommunityMoodRollupsForBucket.
// Check the length with:
//
//	len(mockedQuerier.DeleteCommunityMoodRollupsForBucketCalls())
func (mock *QuerierMock) DeleteCommunityMoodRollupsForBucketCalls() []struct {
	Ctx context.Context
	Arg db.DeleteCommunityMoodRollupsForBucketParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteCommunityMoodRollupsForBucketParams
	}
	mock.lockDeleteCommunityMoodRollupsForBucket.RLock()
	calls = mock.calls.DeleteCommunityMoodRollupsForBucket
	mock.lockDeleteCommunityMoodRollupsForBucket.RUnlock()
	return calls
}

// DeleteCommunityPromptSetsForBucket calls DeleteCommunityPromptSetsForBucketFunc.
func (mock *QuerierMock) DeleteCommunityPromptSetsForBucket(ctx context.Context, arg db.DeleteCommunityPromptSetsForBucketParams) error {
	if mock.DeleteCommunityPromptSetsForBucketFunc == nil {
		panic("QuerierMock.DeleteCommunityPromptSetsForBucketFunc: method is nil but Querier.DeleteCommunityPromptSetsForBucket was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteCommunityPromptSetsForBucketParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteCommunityPromptSetsForBucket.Lock()
	mock.calls.DeleteCommunityPromptSetsForBucket = append(mock.calls.DeleteCommunityPromptSetsForBucket, callInfo)
	mock.lockDeleteCommunityPromptSetsForBucket.Unlock()
	return mock.DeleteCommunityPromptSetsForBucketFunc(ctx, arg)
}

// DeleteCommunityPromptSetsForBucketCalls gets all the calls that were made to DeleteCommunityPromptSetsForBucket.
// Check the length with:
//
//	len(mockedQuerier.DeleteCommunityPromptSetsForBucketCalls())
func (mock *QuerierMock) DeleteCommunityPromptSetsForBucketCalls() []struct {
	Ctx context.Context
	Arg db.DeleteCommunityPromptSetsForBucketParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteCommunityPromptSetsForBucketParams
	}
	mock.lockDeleteCommunityPromptSetsForBucket.RLock()
	calls = mock.calls.DeleteCommunityPromptSetsForBucket
	mock.lockDeleteCommunityPromptSetsForBucket.RUnlock()
	return calls
}

// DeleteCommunitySummariesForBucket calls DeleteCommunitySummariesForBucketFunc.
func (mock *QuerierMock) DeleteCommunitySummariesForBucket(ctx context.Context, arg db.DeleteCommunitySummariesForBucketParams) error {
	if mock.DeleteCommunitySummariesForBucketFunc == nil {
		panic("QuerierMock.DeleteCommunitySummariesForBucketFunc: method is nil but Querier.DeleteCommunitySummariesForBucket was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteCommunitySummariesForBucketParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteCommunitySummariesForBucket.Lock()
	mock.calls.DeleteCommunitySummariesForBucket = append(mock.calls.DeleteCommunitySummariesForBucket, callInfo)
	mock.lockDeleteCommunitySummariesForBucket.Unlock()
	return mock.DeleteCommunitySummariesForBucketFunc(ctx, arg)
}

// DeleteCommunitySummariesForBucketCalls gets all the calls that were made to DeleteCommunitySummariesForBucket.
// Check the length with:
//
//	len(mockedQuerier.DeleteCommunitySummariesForBucketCalls())
func (mock *QuerierMock) DeleteCommunitySummariesForBucketCalls() []struct {
	Ctx context.Context
	Arg db.DeleteCommunitySummariesForBucketParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteCommunitySummariesForBucketParams
	}
	mock.lockDeleteCommunitySummariesForBucket.RLock()
	calls = mock.calls.DeleteCommunitySummariesForBucket
	mock.lockDeleteCommunitySummariesForBucket.RUnlock()
	return calls
}

// DeleteCommunityThemeRollupsForBucket calls DeleteCommunityThemeRollupsForBucketFunc.
func (mock *QuerierMock) DeleteCommunityThemeRollupsForBucket(ctx context.Context, arg db.DeleteCommunityThemeRollupsForBucketParams) error {
	if mock.DeleteCommunityThemeRollupsForBucketFunc == nil {
		panic("QuerierMock.DeleteCommunityThemeRollupsForBucketFunc: method is nil but Querier.DeleteCommunityThemeRollupsForBucket was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteCommunityThemeRollupsForBucketParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteCommunityThemeRollupsForBucket.Lock()
	mock.calls.DeleteCommunityThemeRollupsForBucket = append(mock.calls.DeleteCommunityThemeRollupsForBucket, callInfo)
	mock.lockDeleteCommunityThemeRollupsForBucket.Unlock()
	return mock.DeleteCommunityThemeRollupsForBucketFunc(ctx, arg)
}

// DeleteCommunityThemeRollupsForBucketCalls gets all the calls that were made to DeleteCommunityThemeRollupsForBucket.
// Check the length with:
//
//	len(mockedQuerier.DeleteCommunityThemeRollupsForBucketCalls())
func (mock *QuerierMock) DeleteCommunityThemeRollupsForBucketCalls() []struct {
	Ctx context.Context
	Arg db.DeleteCommunityThemeRollupsForBucketParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteCommunityThemeRollupsForBucketParams
	}
	mock.lockDeleteCommunityThemeRollupsForBucket.RLock()
	calls = mock.calls.DeleteCommunityThemeRollupsForBucket
	mock.lockDeleteCommunityThemeRollupsForBucket.RUnlock()
	return calls
}

// DeleteJournalForUser calls DeleteJournalForUserFunc.
func (mock *QuerierMock) DeleteJournalForUser(ctx context.Context, arg db.DeleteJournalForUserParams) (int64, error) {
	if mock.DeleteJournalForUserFunc == nil {
		panic("QuerierMock.DeleteJournalForUserFunc: method is nil but Querier.DeleteJournalForUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteJournalForUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteJournalForUser.Lock()
	mock.calls.DeleteJournalForUser = append(mock.calls.DeleteJournalForUser, callInfo)
	mock.lockDeleteJournalForUser.Unlock()
	return mock.DeleteJournalForUserFunc(ctx, arg)
}

// DeleteJournalForUserCalls gets all the calls that were made to DeleteJournalForUser.
// Check the length with:
//
//	len(mockedQuerier.DeleteJournalForUserCalls())
func (mock *QuerierMock) DeleteJournalForUserCalls() []struct {
	Ctx context.Context
	Arg db.DeleteJournalForUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteJournalForUserParams
	}
	mock.lockDeleteJournalForUser.RLock()
	calls = mock.calls.DeleteJournalForUser
	mock.lockDeleteJournalForUser.RUnlock()
	return calls
}

// DeleteUserById calls DeleteUserByIdFunc.
func (mock *QuerierMock) DeleteUserById(ctx context.Context, id pgtype.UUID) error {
	if mock.DeleteUserByIdFunc == nil {
		panic("QuerierMock.DeleteUserByIdFunc: method is nil but Querier.DeleteUserById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteUserById.Lock()
	mock.calls.DeleteUserById = append(mock.calls.DeleteUserById, callInfo)
	mock.lockDeleteUserById.Unlock()
	return mock.DeleteUserByIdFunc(ctx, id)
}

// DeleteUserByIdCalls gets all the calls that were made to DeleteUserById.
// Check the length with:
//
//	len(mockedQuerier.DeleteUserByIdCalls())
func (mock *QuerierMock) DeleteUserByIdCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockDeleteUserById.RLock()
	calls = mock.calls.DeleteUserById
	mock.lockDeleteUserById.RUnlock()
	return calls
}

// GetActiveFeatureFlags calls GetActiveFeatureFlagsFunc.
func (mock *QuerierMock) GetActiveFeatureFlags(ctx context.Context) ([]db.SourceWaffleFlag, error) {
	if mock.GetActiveFeatureFlagsFunc == nil {
		panic("QuerierMock.GetActiveFeatureFlagsFunc: method is nil but Querier.GetActiveFeatureFlags was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetActiveFeatureFlags.Lock()
	mock.calls.GetActiveFeatureFlags = append(mock.calls.GetActiveFeatureFlags, callInfo)
	mock.lockGetActiveFeatureFlags.Unlock()
	return mock.GetActiveFeatureFlagsFunc(ctx)
}

// GetActiveFeatureFlagsCalls gets all the calls that were made to GetActiveFeatureFlags.
// Check the length with:
//
//	len(mockedQuerier.GetActiveFeatureFlagsCalls())
func (mock *QuerierMock) GetActiveFeatureFlagsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetActiveFeatureFlags.RLock()
	calls = mock.calls.GetActiveFeatureFlags
	mock.lockGetActiveFeatureFlags.RUnlock()
	return calls
}

// GetActiveMLModel calls GetActiveMLModelFunc.
func (mock *QuerierMock) GetActiveMLModel(ctx context.Context, mlModel string) (bool, error) {
	if mock.GetActiveMLModelFunc == nil {
		panic("QuerierMock.GetActiveMLModelFunc: method is nil but Querier.GetActiveMLModel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		MlModel string
	}{
		Ctx:     ctx,
		MlModel: mlModel,
	}
	mock.lockGetActiveMLModel.Lock()
	mock.calls.GetActiveMLModel = append(mock.calls.GetActiveMLModel, callInfo)
	mock.lockGetActiveMLModel.Unlock()
	return mock.GetActiveMLModelFunc(ctx, mlModel)
}

// GetActiveMLModelCalls gets all the calls that were made to GetActiveMLModel.
// Check the length with:
//
//	len(mockedQuerier.GetActiveMLModelCalls())
func (mock *QuerierMock) GetActiveMLModelCalls() []struct {
	Ctx     context.Context
	MlModel string
} {
	var calls []struct {
		Ctx     context.Context
		MlModel string
	}
	mock.lockGetActiveMLModel.RLock()
	calls = mock.calls.GetActiveMLModel
	mock.lockGetActiveMLModel.RUnlock()
	return calls
}

// GetCommunityProjectionSourceByJournalId calls GetCommunityProjectionSourceByJournalIdFunc.
func (mock *QuerierMock) GetCommunityProjectionSourceByJournalId(ctx context.Context, id int32) (db.GetCommunityProjectionSourceByJournalIdRow, error) {
	if mock.GetCommunityProjectionSourceByJournalIdFunc == nil {
		panic("QuerierMock.GetCommunityProjectionSourceByJournalIdFunc: method is nil but Querier.GetCommunityProjectionSourceByJournalId was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int32
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetCommunityProjectionSourceByJournalId.Lock()
	mock.calls.GetCommunityProjectionSourceByJournalId = append(mock.calls.GetCommunityProjectionSourceByJournalId, callInfo)
	mock.lockGetCommunityProjectionSourceByJournalId.Unlock()
	return mock.GetCommunityProjectionSourceByJournalIdFunc(ctx, id)
}

// GetCommunityProjectionSourceByJournalIdCalls gets all the calls that were made to GetCommunityProjectionSourceByJournalId.
// Check the length with:
//
//	len(mockedQuerier.GetCommunityProjectionSourceByJournalIdCalls())
func (mock *QuerierMock) GetCommunityProjectionSourceByJournalIdCalls() []struct {
	Ctx context.Context
	ID  int32
} {
	var calls []struct {
		Ctx context.Context
		ID  int32
	}
	mock.lockGetCommunityProjectionSourceByJournalId.RLock()
	calls = mock.calls.GetCommunityProjectionSourceByJournalId
	mock.lockGetCommunityProjectionSourceByJournalId.RUnlock()
	return calls
}

// GetCommunityPromptSetByBucketAndScope calls GetCommunityPromptSetByBucketAndScopeFunc.
func (mock *QuerierMock) GetCommunityPromptSetByBucketAndScope(ctx context.Context, arg db.GetCommunityPromptSetByBucketAndScopeParams) (db.SourceCommunityPromptSet, error) {
	if mock.GetCommunityPromptSetByBucketAndScopeFunc == nil {
		panic("QuerierMock.GetCommunityPromptSetByBucketAndScopeFunc: method is nil but Querier.GetCommunityPromptSetByBucketAndScope was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetCommunityPromptSetByBucketAndScopeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetCommunityPromptSetByBucketAndScope.Lock()
	mock.calls.GetCommunityPromptSetByBucketAndScope = append(mock.calls.GetCommunityPromptSetByBucketAndScope, callInfo)
	mock.lockGetCommunityPromptSetByBucketAndScope.Unlock()
	return mock.GetCommunityPromptSetByBucketAndScopeFunc(ctx, arg)
}

// GetCommunityPromptSetByBucketAndScopeCalls gets all the calls that were made to GetCommunityPromptSetByBucketAndScope.
// Check the length with:
//
//	len(mockedQuerier.GetCommunityPromptSetByBucketAndScopeCalls())
func (mock *QuerierMock) GetCommunityPromptSetByBucketAndScopeCalls() []struct {
	Ctx context.Context
	Arg db.GetCommunityPromptSetByBucketAndScopeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetCommunityPromptSetByBucketAndScopeParams
	}
	mock.lockGetCommunityPromptSetByBucketAndScope.RLock()
	calls = mock.calls.GetCommunityPromptSetByBucketAndScope
	mock.lockGetCommunityPromptSetByBucketAndScope.RUnlock()
	return calls
}

// GetCommunitySettingsByUserId calls GetCommunitySettingsByUserIdFunc.
func (mock *QuerierMock) GetCommunitySettingsByUserId(ctx context.Context, id pgtype.UUID) (db.GetCommunitySettingsByUserIdRow, error) {
	if mock.GetCommunitySettingsByUserIdFunc == nil {
		panic("QuerierMock.GetCommunitySettingsByUserIdFunc: method is nil but Querier.GetCommunitySettingsByUserId was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetCommunitySettingsByUserId.Lock()
	mock.calls.GetCommunitySettingsByUserId = append(mock.calls.GetCommunitySettingsByUserId, callInfo)
	mock.lockGetCommunitySettingsByUserId.Unlock()
	return mock.GetCommunitySettingsByUserIdFunc(ctx, id)
}

// GetCommunitySettingsByUserIdCalls gets all the calls that were made to GetCommunitySettingsByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetCommunitySettingsByUserIdCalls())
func (mock *QuerierMock) GetCommunitySettingsByUserIdCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetCommunitySettingsByUserId.RLock()
	calls = mock.calls.GetCommunitySettingsByUserId
	mock.lockGetCommunitySettingsByUserId.RUnlock()
	return calls
}

// GetCommunitySummaryByBucketAndScope calls GetCommunitySummaryByBucketAndScopeFunc.
func (mock *QuerierMock) GetCommunitySummaryByBucketAndScope(ctx context.Context, arg db.GetCommunitySummaryByBucketAndScopeParams) (db.SourceCommunitySummary, error) {
	if mock.GetCommunitySummaryByBucketAndScopeFunc == nil {
		panic("QuerierMock.GetCommunitySummaryByBucketAndScopeFunc: method is nil but Querier.GetCommunitySummaryByBucketAndScope was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetCommunitySummaryByBucketAndScopeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetCommunitySummaryByBucketAndScope.Lock()
	mock.calls.GetCommunitySummaryByBucketAndScope = append(mock.calls.GetCommunitySummaryByBucketAndScope, callInfo)
	mock.lockGetCommunitySummaryByBucketAndScope.Unlock()
	return mock.GetCommunitySummaryByBucketAndScopeFunc(ctx, arg)
}

// GetCommunitySummaryByBucketAndScopeCalls gets all the calls that were made to GetCommunitySummaryByBucketAndScope.
// Check the length with:
//
//	len(mockedQuerier.GetCommunitySummaryByBucketAndScopeCalls())
func (mock *QuerierMock) GetCommunitySummaryByBucketAndScopeCalls() []struct {
	Ctx context.Context
	Arg db.GetCommunitySummaryByBucketAndScopeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetCommunitySummaryByBucketAndScopeParams
	}
	mock.lockGetCommunitySummaryByBucketAndScope.RLock()
	calls = mock.calls.GetCommunitySummaryByBucketAndScope
	mock.lockGetCommunitySummaryByBucketAndScope.RUnlock()
	return calls
}

// GetFeatureFlagByName calls GetFeatureFlagByNameFunc.
func (mock *QuerierMock) GetFeatureFlagByName(ctx context.Context, name string) (db.SourceWaffleFlag, error) {
	if mock.GetFeatureFlagByNameFunc == nil {
		panic("QuerierMock.GetFeatureFlagByNameFunc: method is nil but Querier.GetFeatureFlagByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetFeatureFlagByName.Lock()
	mock.calls.GetFeatureFlagByName = append(mock.calls.GetFeatureFlagByName, callInfo)
	mock.lockGetFeatureFlagByName.Unlock()
	return mock.GetFeatureFlagByNameFunc(ctx, name)
}

// GetFeatureFlagByNameCalls gets all the calls that were made to GetFeatureFlagByName.
// Check the length with:
//
//	len(mockedQuerier.GetFeatureFlagByNameCalls())
func (mock *QuerierMock) GetFeatureFlagByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetFeatureFlagByName.RLock()
	calls = mock.calls.GetFeatureFlagByName
	mock.lockGetFeatureFlagByName.RUnlock()
	return calls
}

// GetJournalById calls GetJournalByIdFunc.
func (mock *QuerierMock) GetJournalById(ctx context.Context, id int32) (db.SourceJournal, error) {
	if mock.GetJournalByIdFunc == nil {
		panic("QuerierMock.GetJournalByIdFunc: method is nil but Querier.GetJournalById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int32
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJournalById.Lock()
	mock.calls.GetJournalById = append(mock.calls.GetJournalById, callInfo)
	mock.lockGetJournalById.Unlock()
	return mock.GetJournalByIdFunc(ctx, id)
}

// GetJournalByIdCalls gets all the calls that were made to GetJournalById.
// Check the length with:
//
//	len(mockedQuerier.GetJournalByIdCalls())
func (mock *QuerierMock) GetJournalByIdCalls() []struct {
	Ctx context.Context
	ID  int32
} {
	var calls []struct {
		Ctx context.Context
		ID  int32
	}
	mock.lockGetJournalById.RLock()
	calls = mock.calls.GetJournalById
	mock.lockGetJournalById.RUnlock()
	return calls
}

// GetJournalCommunityProjectionByJournalId calls GetJournalCommunityProjectionByJournalIdFunc.
func (mock *QuerierMock) GetJournalCommunityProjectionByJournalId(ctx context.Context, journalID int32) (db.SourceJournalCommunityProjection, error) {
	if mock.GetJournalCommunityProjectionByJournalIdFunc == nil {
		panic("QuerierMock.GetJournalCommunityProjectionByJournalIdFunc: method is nil but Querier.GetJournalCommunityProjectionByJournalId was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JournalID int32
	}{
		Ctx:       ctx,
		JournalID: journalID,
	}
	mock.lockGetJournalCommunityProjectionByJournalId.Lock()
	mock.calls.GetJournalCommunityProjectionByJournalId = append(mock.calls.GetJournalCommunityProjectionByJournalId, callInfo)
	mock.lockGetJournalCommunityProjectionByJournalId.Unlock()
	return mock.GetJournalCommunityProjectionByJournalIdFunc(ctx, journalID)
}

// GetJournalCommunityProjectionByJournalIdCalls gets all the calls that were made to GetJournalCommunityProjectionByJournalId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalCommunityProjectionByJournalIdCalls())
func (mock *QuerierMock) GetJournalCommunityProjectionByJournalIdCalls() []struct {
	Ctx       context.Context
	JournalID int32
} {
	var calls []struct {
		Ctx       context.Context
		JournalID int32
	}
	mock.lockGetJournalCommunityProjectionByJournalId.RLock()
	calls = mock.calls.GetJournalCommunityProjectionByJournalId
	mock.lockGetJournalCommunityProjectionByJournalId.RUnlock()
	return calls
}

// GetJournalCountByUserId calls GetJournalCountByUserIdFunc.
func (mock *QuerierMock) GetJournalCountByUserId(ctx context.Context, userID pgtype.UUID) (int64, error) {
	if mock.GetJournalCountByUserIdFunc == nil {
		panic("QuerierMock.GetJournalCountByUserIdFunc: method is nil but Querier.GetJournalCountByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalCountByUserId.Lock()
	mock.calls.GetJournalCountByUserId = append(mock.calls.GetJournalCountByUserId, callInfo)
	mock.lockGetJournalCountByUserId.Unlock()
	return mock.GetJournalCountByUserIdFunc(ctx, userID)
}

// GetJournalCountByUserIdCalls gets all the calls that were made to GetJournalCountByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalCountByUserIdCalls())
func (mock *QuerierMock) GetJournalCountByUserIdCalls() []struct {
	Ctx    context.Context
	UserID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}
	mock.lockGetJournalCountByUserId.RLock()
	calls = mock.calls.GetJournalCountByUserId
	mock.lockGetJournalCountByUserId.RUnlock()
	return calls
}

// GetJournalExport calls GetJournalExportFunc.
func (mock *QuerierMock) GetJournalExport(ctx context.Context, arg db.GetJournalExportParams) (db.SourceJournalExport, error) {
	if mock.GetJournalExportFunc == nil {
		panic("QuerierMock.GetJournalExportFunc: method is nil but Querier.GetJournalExport was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetJournalExportParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetJournalExport.Lock()
	mock.calls.GetJournalExport = append(mock.calls.GetJournalExport, callInfo)
	mock.lockGetJournalExport.Unlock()
	return mock.GetJournalExportFunc(ctx, arg)
}

// GetJournalExportCalls gets all the calls that were made to GetJournalExport.
// Check the length with:
//
//	len(mockedQuerier.GetJournalExportCalls())
func (mock *QuerierMock) GetJournalExportCalls() []struct {
	Ctx context.Context
	Arg db.GetJournalExportParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetJournalExportParams
	}
	mock.lockGetJournalExport.RLock()
	calls = mock.calls.GetJournalExport
	mock.lockGetJournalExport.RUnlock()
	return calls
}

// GetJournalsByUserId calls GetJournalsByUserIdFunc.
func (mock *QuerierMock) GetJournalsByUserId(ctx context.Context, userID pgtype.UUID) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdFunc: method is nil but Querier.GetJournalsByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetJournalsByUserId.Lock()
	mock.calls.GetJournalsByUserId = append(mock.calls.GetJournalsByUserId, callInfo)
	mock.lockGetJournalsByUserId.Unlock()
	return mock.GetJournalsByUserIdFunc(ctx, userID)
}

// GetJournalsByUserIdCalls gets all the calls that were made to GetJournalsByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdCalls())
func (mock *QuerierMock) GetJournalsByUserIdCalls() []struct {
	Ctx    context.Context
	UserID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}
	mock.lockGetJournalsByUserId.RLock()
	calls = mock.calls.GetJournalsByUserId
	mock.lockGetJournalsByUserId.RUnlock()
	return calls
}

// GetJournalsByUserIdPaginated calls GetJournalsByUserIdPaginatedFunc.
func (mock *QuerierMock) GetJournalsByUserIdPaginated(ctx context.Context, arg db.GetJournalsByUserIdPaginatedParams) ([]db.SourceJournal, error) {
	if mock.GetJournalsByUserIdPaginatedFunc == nil {
		panic("QuerierMock.GetJournalsByUserIdPaginatedFunc: method is nil but Querier.GetJournalsByUserIdPaginated was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetJournalsByUserIdPaginated.Lock()
	mock.calls.GetJournalsByUserIdPaginated = append(mock.calls.GetJournalsByUserIdPaginated, callInfo)
	mock.lockGetJournalsByUserIdPaginated.Unlock()
	return mock.GetJournalsByUserIdPaginatedFunc(ctx, arg)
}

// GetJournalsByUserIdPaginatedCalls gets all the calls that were made to GetJournalsByUserIdPaginated.
// Check the length with:
//
//	len(mockedQuerier.GetJournalsByUserIdPaginatedCalls())
func (mock *QuerierMock) GetJournalsByUserIdPaginatedCalls() []struct {
	Ctx context.Context
	Arg db.GetJournalsByUserIdPaginatedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetJournalsByUserIdPaginatedParams
	}
	mock.lockGetJournalsByUserIdPaginated.RLock()
	calls = mock.calls.GetJournalsByUserIdPaginated
	mock.lockGetJournalsByUserIdPaginated.RUnlock()
	return calls
}

// GetMoodRollupsByBucketAndScope calls GetMoodRollupsByBucketAndScopeFunc.
func (mock *QuerierMock) GetMoodRollupsByBucketAndScope(ctx context.Context, arg db.GetMoodRollupsByBucketAndScopeParams) ([]db.SourceCommunityMoodRollup, error) {
	if mock.GetMoodRollupsByBucketAndScopeFunc == nil {
		panic("QuerierMock.GetMoodRollupsByBucketAndScopeFunc: method is nil but Querier.GetMoodRollupsByBucketAndScope was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetMoodRollupsByBucketAndScopeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetMoodRollupsByBucketAndScope.Lock()
	mock.calls.GetMoodRollupsByBucketAndScope = append(mock.calls.GetMoodRollupsByBucketAndScope, callInfo)
	mock.lockGetMoodRollupsByBucketAndScope.Unlock()
	return mock.GetMoodRollupsByBucketAndScopeFunc(ctx, arg)
}

// GetMoodRollupsByBucketAndScopeCalls gets all the calls that were made to GetMoodRollupsByBucketAndScope.
// Check the length with:
//
//	len(mockedQuerier.GetMoodRollupsByBucketAndScopeCalls())
func (mock *QuerierMock) GetMoodRollupsByBucketAndScopeCalls() []struct {
	Ctx context.Context
	Arg db.GetMoodRollupsByBucketAndScopeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetMoodRollupsByBucketAndScopeParams
	}
	mock.lockGetMoodRollupsByBucketAndScope.RLock()
	calls = mock.calls.GetMoodRollupsByBucketAndScope
	mock.lockGetMoodRollupsByBucketAndScope.RUnlock()
	return calls
}

// GetRuntimeConfigByKey calls GetRuntimeConfigByKeyFunc.
func (mock *QuerierMock) GetRuntimeConfigByKey(ctx context.Context, key string) (db.SourceRuntimeConfig, error) {
	if mock.GetRuntimeConfigByKeyFunc == nil {
		panic("QuerierMock.GetRuntimeConfigByKeyFunc: method is nil but Querier.GetRuntimeConfigByKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetRuntimeConfigByKey.Lock()
	mock.calls.GetRuntimeConfigByKey = append(mock.calls.GetRuntimeConfigByKey, callInfo)
	mock.lockGetRuntimeConfigByKey.Unlock()
	return mock.GetRuntimeConfigByKeyFunc(ctx, key)
}

// GetRuntimeConfigByKeyCalls gets all the calls that were made to GetRuntimeConfigByKey.
// Check the length with:
//
//	len(mockedQuerier.GetRuntimeConfigByKeyCalls())
func (mock *QuerierMock) GetRuntimeConfigByKeyCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetRuntimeConfigByKey.RLock()
	calls = mock.calls.GetRuntimeConfigByKey
	mock.lockGetRuntimeConfigByKey.RUnlock()
	return calls
}

// GetThemeRollupsByBucketAndScope calls GetThemeRollupsByBucketAndScopeFunc.
func (mock *QuerierMock) GetThemeRollupsByBucketAndScope(ctx context.Context, arg db.GetThemeRollupsByBucketAndScopeParams) ([]db.SourceCommunityThemeRollup, error) {
	if mock.GetThemeRollupsByBucketAndScopeFunc == nil {
		panic("QuerierMock.GetThemeRollupsByBucketAndScopeFunc: method is nil but Querier.GetThemeRollupsByBucketAndScope was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetThemeRollupsByBucketAndScopeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetThemeRollupsByBucketAndScope.Lock()
	mock.calls.GetThemeRollupsByBucketAndScope = append(mock.calls.GetThemeRollupsByBucketAndScope, callInfo)
	mock.lockGetThemeRollupsByBucketAndScope.Unlock()
	return mock.GetThemeRollupsByBucketAndScopeFunc(ctx, arg)
}

// GetThemeRollupsByBucketAndScopeCalls gets all the calls that were made to GetThemeRollupsByBucketAndScope.
// Check the length with:
//
//	len(mockedQuerier.GetThemeRollupsByBucketAndScopeCalls())
func (mock *QuerierMock) GetThemeRollupsByBucketAndScopeCalls() []struct {
	Ctx context.Context
	Arg db.GetThemeRollupsByBucketAndScopeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetThemeRollupsByBucketAndScopeParams
	}
	mock.lockGetThemeRollupsByBucketAndScope.RLock()
	calls = mock.calls.GetThemeRollupsByBucketAndScope
	mock.lockGetThemeRollupsByBucketAndScope.RUnlock()
	return calls
}

// GetTopicsByJournalIds calls GetTopicsByJournalIdsFunc.
func (mock *QuerierMock) GetTopicsByJournalIds(ctx context.Context, dollar_1 []int32) ([]db.GetTopicsByJournalIdsRow, error) {
	if mock.GetTopicsByJournalIdsFunc == nil {
		panic("QuerierMock.GetTopicsByJournalIdsFunc: method is nil but Querier.GetTopicsByJournalIds was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Dollar_1 []int32
	}{
		Ctx:      ctx,
		Dollar_1: dollar_1,
	}
	mock.lockGetTopicsByJournalIds.Lock()
	mock.calls.GetTopicsByJournalIds = append(mock.calls.GetTopicsByJournalIds, callInfo)
	mock.lockGetTopicsByJournalIds.Unlock()
	return mock.GetTopicsByJournalIdsFunc(ctx, dollar_1)
}

// GetTopicsByJournalIdsCalls gets all the calls that were made to GetTopicsByJournalIds.
// Check the length with:
//
//	len(mockedQuerier.GetTopicsByJournalIdsCalls())
func (mock *QuerierMock) GetTopicsByJournalIdsCalls() []struct {
	Ctx      context.Context
	Dollar_1 []int32
} {
	var calls []struct {
		Ctx      context.Context
		Dollar_1 []int32
	}
	mock.lockGetTopicsByJournalIds.RLock()
	calls = mock.calls.GetTopicsByJournalIds
	mock.lockGetTopicsByJournalIds.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *QuerierMock) GetUserByEmail(ctx context.Context, email string) (db.SourceUser, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("QuerierMock.GetUserByEmailFunc: method is nil but Querier.GetUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedQuerier.GetUserByEmailCalls())
func (mock *QuerierMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserById calls GetUserByIdFunc.
func (mock *QuerierMock) GetUserById(ctx context.Context, id pgtype.UUID) (db.SourceUser, error) {
	if mock.GetUserByIdFunc == nil {
		panic("QuerierMock.GetUserByIdFunc: method is nil but Querier.GetUserById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserById.Lock()
	mock.calls.GetUserById = append(mock.calls.GetUserById, callInfo)
	mock.lockGetUserById.Unlock()
	return mock.GetUserByIdFunc(ctx, id)
}

// GetUserByIdCalls gets all the calls that were made to GetUserById.
// Check the length with:
//
//	len(mockedQuerier.GetUserByIdCalls())
func (mock *QuerierMock) GetUserByIdCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetUserById.RLock()
	calls = mock.calls.GetUserById
	mock.lockGetUserById.RUnlock()
	return calls
}

// GetUserGameBalance calls GetUserGameBalanceFunc.
func (mock *QuerierMock) GetUserGameBalance(ctx context.Context, userID pgtype.UUID) (db.SourceUserGameBalance, error) {
	if mock.GetUserGameBalanceFunc == nil {
		panic("QuerierMock.GetUserGameBalanceFunc: method is nil but Querier.GetUserGameBalance was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserGameBalance.Lock()
	mock.calls.GetUserGameBalance = append(mock.calls.GetUserGameBalance, callInfo)
	mock.lockGetUserGameBalance.Unlock()
	return mock.GetUserGameBalanceFunc(ctx, userID)
}

// GetUserGameBalanceCalls gets all the calls that were made to GetUserGameBalance.
// Check the length with:
//
//	len(mockedQuerier.GetUserGameBalanceCalls())
func (mock *QuerierMock) GetUserGameBalanceCalls() []struct {
	Ctx    context.Context
	UserID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}
	mock.lockGetUserGameBalance.RLock()
	calls = mock.calls.GetUserGameBalance
	mock.lockGetUserGameBalance.RUnlock()
	return calls
}

// GetUserGameBets calls GetUserGameBetsFunc.
func (mock *QuerierMock) GetUserGameBets(ctx context.Context, arg db.GetUserGameBetsParams) ([]db.SourceUserGameBet, error) {
	if mock.GetUserGameBetsFunc == nil {
		panic("QuerierMock.GetUserGameBetsFunc: method is nil but Querier.GetUserGameBets was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.GetUserGameBetsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetUserGameBets.Lock()
	mock.calls.GetUserGameBets = append(mock.calls.GetUserGameBets, callInfo)
	mock.lockGetUserGameBets.Unlock()
	return mock.GetUserGameBetsFunc(ctx, arg)
}

// GetUserGameBetsCalls gets all the calls that were made to GetUserGameBets.
// Check the length with:
//
//	len(mockedQuerier.GetUserGameBetsCalls())
func (mock *QuerierMock) GetUserGameBetsCalls() []struct {
	Ctx context.Context
	Arg db.GetUserGameBetsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.GetUserGameBetsParams
	}
	mock.lockGetUserGameBets.RLock()
	calls = mock.calls.GetUserGameBets
	mock.lockGetUserGameBets.RUnlock()
	return calls
}

// GetUserJournalSummaryByUserId calls GetUserJournalSummaryByUserIdFunc.
func (mock *QuerierMock) GetUserJournalSummaryByUserId(ctx context.Context, userID pgtype.UUID) (db.GoldUserJournalSummary, error) {
	if mock.GetUserJournalSummaryByUserIdFunc == nil {
		panic("QuerierMock.GetUserJournalSummaryByUserIdFunc: method is nil but Querier.GetUserJournalSummaryByUserId was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserJournalSummaryByUserId.Lock()
	mock.calls.GetUserJournalSummaryByUserId = append(mock.calls.GetUserJournalSummaryByUserId, callInfo)
	mock.lockGetUserJournalSummaryByUserId.Unlock()
	return mock.GetUserJournalSummaryByUserIdFunc(ctx, userID)
}

// GetUserJournalSummaryByUserIdCalls gets all the calls that were made to GetUserJournalSummaryByUserId.
// Check the length with:
//
//	len(mockedQuerier.GetUserJournalSummaryByUserIdCalls())
func (mock *QuerierMock) GetUserJournalSummaryByUserIdCalls() []struct {
	Ctx    context.Context
	UserID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID pgtype.UUID
	}
	mock.lockGetUserJournalSummaryByUserId.RLock()
	calls = mock.calls.GetUserJournalSummaryByUserId
	mock.lockGetUserJournalSummaryByUserId.RUnlock()
	return calls
}

// InsertUserGameBet calls InsertUserGameBetFunc.
func (mock *QuerierMock) InsertUserGameBet(ctx context.Context, arg db.InsertUserGameBetParams) (db.SourceUserGameBet, error) {
	if mock.InsertUserGameBetFunc == nil {
		panic("QuerierMock.InsertUserGameBetFunc: method is nil but Querier.InsertUserGameBet was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertUserGameBetParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertUserGameBet.Lock()
	mock.calls.InsertUserGameBet = append(mock.calls.InsertUserGameBet, callInfo)
	mock.lockInsertUserGameBet.Unlock()
	return mock.InsertUserGameBetFunc(ctx, arg)
}

// InsertUserGameBetCalls gets all the calls that were made to InsertUserGameBet.
// Check the length with:
//
//	len(mockedQuerier.InsertUserGameBetCalls())
func (mock *QuerierMock) InsertUserGameBetCalls() []struct {
	Ctx context.Context
	Arg db.InsertUserGameBetParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertUserGameBetParams
	}
	mock.lockInsertUserGameBet.RLock()
	calls = mock.calls.InsertUserGameBet
	mock.lockInsertUserGameBet.RUnlock()
	return calls
}

// ListCommunityRepairJournalIds calls ListCommunityRepairJournalIdsFunc.
func (mock *QuerierMock) ListCommunityRepairJournalIds(ctx context.Context, createdAt pgtype.Timestamp) ([]int32, error) {
	if mock.ListCommunityRepairJournalIdsFunc == nil {
		panic("QuerierMock.ListCommunityRepairJournalIdsFunc: method is nil but Querier.ListCommunityRepairJournalIds was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		CreatedAt pgtype.Timestamp
	}{
		Ctx:       ctx,
		CreatedAt: createdAt,
	}
	mock.lockListCommunityRepairJournalIds.Lock()
	mock.calls.ListCommunityRepairJournalIds = append(mock.calls.ListCommunityRepairJournalIds, callInfo)
	mock.lockListCommunityRepairJournalIds.Unlock()
	return mock.ListCommunityRepairJournalIdsFunc(ctx, createdAt)
}

// ListCommunityRepairJournalIdsCalls gets all the calls that were made to ListCommunityRepairJournalIds.
// Check the length with:
//
//	len(mockedQuerier.ListCommunityRepairJournalIdsCalls())
func (mock *QuerierMock) ListCommunityRepairJournalIdsCalls() []struct {
	Ctx       context.Context
	CreatedAt pgtype.Timestamp
} {
	var calls []struct {
		Ctx       context.Context
		CreatedAt pgtype.Timestamp
	}
	mock.lockListCommunityRepairJournalIds.RLock()
	calls = mock.calls.ListCommunityRepairJournalIds
	mock.lockListCommunityRepairJournalIds.RUnlock()
	return calls
}

// ListEligibleCommunityProjectionsByDateRange calls ListEligibleCommunityProjectionsByDateRangeFunc.
func (mock *QuerierMock) ListEligibleCommunityProjectionsByDateRange(ctx context.Context, arg db.ListEligibleCommunityProjectionsByDateRangeParams) ([]db.SourceJournalCommunityProjection, error) {
	if mock.ListEligibleCommunityProjectionsByDateRangeFunc == nil {
		panic("QuerierMock.ListEligibleCommunityProjectionsByDateRangeFunc: method is nil but Querier.ListEligibleCommunityProjectionsByDateRange was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.ListEligibleCommunityProjectionsByDateRangeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockListEligibleCommunityProjectionsByDateRange.Lock()
	mock.calls.ListEligibleCommunityProjectionsByDateRange = append(mock.calls.ListEligibleCommunityProjectionsByDateRange, callInfo)
	mock.lockListEligibleCommunityProjectionsByDateRange.Unlock()
	return mock.ListEligibleCommunityProjectionsByDateRangeFunc(ctx, arg)
}

// ListEligibleCommunityProjectionsByDateRangeCalls gets all the calls that were made to ListEligibleCommunityProjectionsByDateRange.
// Check the length with:
//
//	len(mockedQuerier.ListEligibleCommunityProjectionsByDateRangeCalls())
func (mock *QuerierMock) ListEligibleCommunityProjectionsByDateRangeCalls() []struct {
	Ctx context.Context
	Arg db.ListEligibleCommunityProjectionsByDateRangeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.ListEligibleCommunityProjectionsByDateRangeParams
	}
	mock.lockListEligibleCommunityProjectionsByDateRange.RLock()
	calls = mock.calls.ListEligibleCommunityProjectionsByDateRange
	mock.lockListEligibleCommunityProjectionsByDateRange.RUnlock()
	return calls
}

// SearchJournalsKeyword calls SearchJournalsKeywordFunc.
func (mock *QuerierMock) SearchJournalsKeyword(ctx context.Context, arg db.SearchJournalsKeywordParams) ([]db.SearchJournalsKeywordRow, error) {
	if mock.SearchJournalsKeywordFunc == nil {
		panic("QuerierMock.SearchJournalsKeywordFunc: method is nil but Querier.SearchJournalsKeyword was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.SearchJournalsKeywordParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSearchJournalsKeyword.Lock()
	mock.calls.SearchJournalsKeyword = append(mock.calls.SearchJournalsKeyword, callInfo)
	mock.lockSearchJournalsKeyword.Unlock()
	return mock.SearchJournalsKeywordFunc(ctx, arg)
}

// SearchJournalsKeywordCalls gets all the calls that were made to SearchJournalsKeyword.
// Check the length with:
//
//	len(mockedQuerier.SearchJournalsKeywordCalls())
func (mock *QuerierMock) SearchJournalsKeywordCalls() []struct {
	Ctx context.Context
	Arg db.SearchJournalsKeywordParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.SearchJournalsKeywordParams
	}
	mock.lockSearchJournalsKeyword.RLock()
	calls = mock.calls.SearchJournalsKeyword
	mock.lockSearchJournalsKeyword.RUnlock()
	return calls
}

// SearchJournalsSemantic calls SearchJournalsSemanticFunc.
func (mock *QuerierMock) SearchJournalsSemantic(ctx context.Context, arg db.SearchJournalsSemanticParams) ([]db.SearchJournalsSemanticRow, error) {
	if mock.SearchJournalsSemanticFunc == nil {
		panic("QuerierMock.SearchJournalsSemanticFunc: method is nil but Querier.SearchJournalsSemantic was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.SearchJournalsSemanticParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSearchJournalsSemantic.Lock()
	mock.calls.SearchJournalsSemantic = append(mock.calls.SearchJournalsSemantic, callInfo)
	mock.lockSearchJournalsSemantic.Unlock()
	return mock.SearchJournalsSemanticFunc(ctx, arg)
}

// SearchJournalsSemanticCalls gets all the calls that were made to SearchJournalsSemantic.
// Check the length with:
//
//	len(mockedQuerier.SearchJournalsSemanticCalls())
func (mock *QuerierMock) SearchJournalsSemanticCalls() []struct {
	Ctx context.Context
	Arg db.SearchJournalsSemanticParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.SearchJournalsSemanticParams
	}
	mock.lockSearchJournalsSemantic.RLock()
	calls = mock.calls.SearchJournalsSemantic
	mock.lockSearchJournalsSemantic.RUnlock()
	return calls
}

// UpdateCommunitySettingsByUserId calls UpdateCommunitySettingsByUserIdFunc.
func (mock *QuerierMock) UpdateCommunitySettingsByUserId(ctx context.Context, arg db.UpdateCommunitySettingsByUserIdParams) (db.SourceUser, error) {
	if mock.UpdateCommunitySettingsByUserIdFunc == nil {
		panic("QuerierMock.UpdateCommunitySettingsByUserIdFunc: method is nil but Querier.UpdateCommunitySettingsByUserId was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateCommunitySettingsByUserIdParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateCommunitySettingsByUserId.Lock()
	mock.calls.UpdateCommunitySettingsByUserId = append(mock.calls.UpdateCommunitySettingsByUserId, callInfo)
	mock.lockUpdateCommunitySettingsByUserId.Unlock()
	return mock.UpdateCommunitySettingsByUserIdFunc(ctx, arg)
}

// UpdateCommunitySettingsByUserIdCalls gets all the calls that were made to UpdateCommunitySettingsByUserId.
// Check the length with:
//
//	len(mockedQuerier.UpdateCommunitySettingsByUserIdCalls())
func (mock *QuerierMock) UpdateCommunitySettingsByUserIdCalls() []struct {
	Ctx context.Context
	Arg db.UpdateCommunitySettingsByUserIdParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateCommunitySettingsByUserIdParams
	}
	mock.lockUpdateCommunitySettingsByUserId.RLock()
	calls = mock.calls.UpdateCommunitySettingsByUserId
	mock.lockUpdateCommunitySettingsByUserId.RUnlock()
	return calls
}

// UpdateJournalExportComplete calls UpdateJournalExportCompleteFunc.
func (mock *QuerierMock) UpdateJournalExportComplete(ctx context.Context, arg db.UpdateJournalExportCompleteParams) (db.SourceJournalExport, error) {
	if mock.UpdateJournalExportCompleteFunc == nil {
		panic("QuerierMock.UpdateJournalExportCompleteFunc: method is nil but Querier.UpdateJournalExportComplete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateJournalExportCompleteParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateJournalExportComplete.Lock()
	mock.calls.UpdateJournalExportComplete = append(mock.calls.UpdateJournalExportComplete, callInfo)
	mock.lockUpdateJournalExportComplete.Unlock()
	return mock.UpdateJournalExportCompleteFunc(ctx, arg)
}

// UpdateJournalExportCompleteCalls gets all the calls that were made to UpdateJournalExportComplete.
// Check the length with:
//
//	len(mockedQuerier.UpdateJournalExportCompleteCalls())
func (mock *QuerierMock) UpdateJournalExportCompleteCalls() []struct {
	Ctx context.Context
	Arg db.UpdateJournalExportCompleteParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateJournalExportCompleteParams
	}
	mock.lockUpdateJournalExportComplete.RLock()
	calls = mock.calls.UpdateJournalExportComplete
	mock.lockUpdateJournalExportComplete.RUnlock()
	return calls
}

// UpdateJournalExportFailed calls UpdateJournalExportFailedFunc.
func (mock *QuerierMock) UpdateJournalExportFailed(ctx context.Context, arg db.UpdateJournalExportFailedParams) (db.SourceJournalExport, error) {
	if mock.UpdateJournalExportFailedFunc == nil {
		panic("QuerierMock.UpdateJournalExportFailedFunc: method is nil but Querier.UpdateJournalExportFailed was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateJournalExportFailedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateJournalExportFailed.Lock()
	mock.calls.UpdateJournalExportFailed = append(mock.calls.UpdateJournalExportFailed, callInfo)
	mock.lockUpdateJournalExportFailed.Unlock()
	return mock.UpdateJournalExportFailedFunc(ctx, arg)
}

// UpdateJournalExportFailedCalls gets all the calls that were made to UpdateJournalExportFailed.
// Check the length with:
//
//	len(mockedQuerier.UpdateJournalExportFailedCalls())
func (mock *QuerierMock) UpdateJournalExportFailedCalls() []struct {
	Ctx context.Context
	Arg db.UpdateJournalExportFailedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateJournalExportFailedParams
	}
	mock.lockUpdateJournalExportFailed.RLock()
	calls = mock.calls.UpdateJournalExportFailed
	mock.lockUpdateJournalExportFailed.RUnlock()
	return calls
}

// UpdateJournalExportProcessing calls UpdateJournalExportProcessingFunc.
func (mock *QuerierMock) UpdateJournalExportProcessing(ctx context.Context, id pgtype.UUID) (db.SourceJournalExport, error) {
	if mock.UpdateJournalExportProcessingFunc == nil {
		panic("QuerierMock.UpdateJournalExportProcessingFunc: method is nil but Querier.UpdateJournalExportProcessing was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockUpdateJournalExportProcessing.Lock()
	mock.calls.UpdateJournalExportProcessing = append(mock.calls.UpdateJournalExportProcessing, callInfo)
	mock.lockUpdateJournalExportProcessing.Unlock()
	return mock.UpdateJournalExportProcessingFunc(ctx, id)
}

// UpdateJournalExportProcessingCalls gets all the calls that were made to UpdateJournalExportProcessing.
// Check the length with:
//
//	len(mockedQuerier.UpdateJournalExportProcessingCalls())
func (mock *QuerierMock) UpdateJournalExportProcessingCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockUpdateJournalExportProcessing.RLock()
	calls = mock.calls.UpdateJournalExportProcessing
	mock.lockUpdateJournalExportProcessing.RUnlock()
	return calls
}

// UpdateJournalForUser calls UpdateJournalForUserFunc.
func (mock *QuerierMock) UpdateJournalForUser(ctx context.Context, arg db.UpdateJournalForUserParams) (int64, error) {
	if mock.UpdateJournalForUserFunc == nil {
		panic("QuerierMock.UpdateJournalForUserFunc: method is nil but Querier.UpdateJournalForUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateJournalForUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateJournalForUser.Lock()
	mock.calls.UpdateJournalForUser = append(mock.calls.UpdateJournalForUser, callInfo)
	mock.lockUpdateJournalForUser.Unlock()
	return mock.UpdateJournalForUserFunc(ctx, arg)
}

// UpdateJournalForUserCalls gets all the calls that were made to UpdateJournalForUser.
// Check the length with:
//
//	len(mockedQuerier.UpdateJournalForUserCalls())
func (mock *QuerierMock) UpdateJournalForUserCalls() []struct {
	Ctx context.Context
	Arg db.UpdateJournalForUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateJournalForUserParams
	}
	mock.lockUpdateJournalForUser.RLock()
	calls = mock.calls.UpdateJournalForUser
	mock.lockUpdateJournalForUser.RUnlock()
	return calls
}

// UpdateUserTimezone calls UpdateUserTimezoneFunc.
func (mock *QuerierMock) UpdateUserTimezone(ctx context.Context, arg db.UpdateUserTimezoneParams) (db.SourceUser, error) {
	if mock.UpdateUserTimezoneFunc == nil {
		panic("QuerierMock.UpdateUserTimezoneFunc: method is nil but Querier.UpdateUserTimezone was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateUserTimezoneParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateUserTimezone.Lock()
	mock.calls.UpdateUserTimezone = append(mock.calls.UpdateUserTimezone, callInfo)
	mock.lockUpdateUserTimezone.Unlock()
	return mock.UpdateUserTimezoneFunc(ctx, arg)
}

// UpdateUserTimezoneCalls gets all the calls that were made to UpdateUserTimezone.
// Check the length with:
//
//	len(mockedQuerier.UpdateUserTimezoneCalls())
func (mock *QuerierMock) UpdateUserTimezoneCalls() []struct {
	Ctx context.Context
	Arg db.UpdateUserTimezoneParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateUserTimezoneParams
	}
	mock.lockUpdateUserTimezone.RLock()
	calls = mock.calls.UpdateUserTimezone
	mock.lockUpdateUserTimezone.RUnlock()
	return calls
}

// UpsertCommunityMoodRollup calls UpsertCommunityMoodRollupFunc.
func (mock *QuerierMock) UpsertCommunityMoodRollup(ctx context.Context, arg db.UpsertCommunityMoodRollupParams) (db.SourceCommunityMoodRollup, error) {
	if mock.UpsertCommunityMoodRollupFunc == nil {
		panic("QuerierMock.UpsertCommunityMoodRollupFunc: method is nil but Querier.UpsertCommunityMoodRollup was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertCommunityMoodRollupParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCommunityMoodRollup.Lock()
	mock.calls.UpsertCommunityMoodRollup = append(mock.calls.UpsertCommunityMoodRollup, callInfo)
	mock.lockUpsertCommunityMoodRollup.Unlock()
	return mock.UpsertCommunityMoodRollupFunc(ctx, arg)
}

// UpsertCommunityMoodRollupCalls gets all the calls that were made to UpsertCommunityMoodRollup.
// Check the length with:
//
//	len(mockedQuerier.UpsertCommunityMoodRollupCalls())
func (mock *QuerierMock) UpsertCommunityMoodRollupCalls() []struct {
	Ctx context.Context
	Arg db.UpsertCommunityMoodRollupParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertCommunityMoodRollupParams
	}
	mock.lockUpsertCommunityMoodRollup.RLock()
	calls = mock.calls.UpsertCommunityMoodRollup
	mock.lockUpsertCommunityMoodRollup.RUnlock()
	return calls
}

// UpsertCommunityPromptSet calls UpsertCommunityPromptSetFunc.
func (mock *QuerierMock) UpsertCommunityPromptSet(ctx context.Context, arg db.UpsertCommunityPromptSetParams) (db.SourceCommunityPromptSet, error) {
	if mock.UpsertCommunityPromptSetFunc == nil {
		panic("QuerierMock.UpsertCommunityPromptSetFunc: method is nil but Querier.UpsertCommunityPromptSet was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertCommunityPromptSetParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCommunityPromptSet.Lock()
	mock.calls.UpsertCommunityPromptSet = append(mock.calls.UpsertCommunityPromptSet, callInfo)
	mock.lockUpsertCommunityPromptSet.Unlock()
	return mock.UpsertCommunityPromptSetFunc(ctx, arg)
}

// UpsertCommunityPromptSetCalls gets all the calls that were made to UpsertCommunityPromptSet.
// Check the length with:
//
//	len(mockedQuerier.UpsertCommunityPromptSetCalls())
func (mock *QuerierMock) UpsertCommunityPromptSetCalls() []struct {
	Ctx context.Context
	Arg db.UpsertCommunityPromptSetParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertCommunityPromptSetParams
	}
	mock.lockUpsertCommunityPromptSet.RLock()
	calls = mock.calls.UpsertCommunityPromptSet
	mock.lockUpsertCommunityPromptSet.RUnlock()
	return calls
}

// UpsertCommunitySummary calls UpsertCommunitySummaryFunc.
func (mock *QuerierMock) UpsertCommunitySummary(ctx context.Context, arg db.UpsertCommunitySummaryParams) (db.SourceCommunitySummary, error) {
	if mock.UpsertCommunitySummaryFunc == nil {
		panic("QuerierMock.UpsertCommunitySummaryFunc: method is nil but Querier.UpsertCommunitySummary was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertCommunitySummaryParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCommunitySummary.Lock()
	mock.calls.UpsertCommunitySummary = append(mock.calls.UpsertCommunitySummary, callInfo)
	mock.lockUpsertCommunitySummary.Unlock()
	return mock.UpsertCommunitySummaryFunc(ctx, arg)
}

// UpsertCommunitySummaryCalls gets all the calls that were made to UpsertCommunitySummary.
// Check the length with:
//
//	len(mockedQuerier.UpsertCommunitySummaryCalls())
func (mock *QuerierMock) UpsertCommunitySummaryCalls() []struct {
	Ctx context.Context
	Arg db.UpsertCommunitySummaryParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertCommunitySummaryParams
	}
	mock.lockUpsertCommunitySummary.RLock()
	calls = mock.calls.UpsertCommunitySummary
	mock.lockUpsertCommunitySummary.RUnlock()
	return calls
}

// UpsertCommunityThemeRollup calls UpsertCommunityThemeRollupFunc.
func (mock *QuerierMock) UpsertCommunityThemeRollup(ctx context.Context, arg db.UpsertCommunityThemeRollupParams) (db.SourceCommunityThemeRollup, error) {
	if mock.UpsertCommunityThemeRollupFunc == nil {
		panic("QuerierMock.UpsertCommunityThemeRollupFunc: method is nil but Querier.UpsertCommunityThemeRollup was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertCommunityThemeRollupParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCommunityThemeRollup.Lock()
	mock.calls.UpsertCommunityThemeRollup = append(mock.calls.UpsertCommunityThemeRollup, callInfo)
	mock.lockUpsertCommunityThemeRollup.Unlock()
	return mock.UpsertCommunityThemeRollupFunc(ctx, arg)
}

// UpsertCommunityThemeRollupCalls gets all the calls that were made to UpsertCommunityThemeRollup.
// Check the length with:
//
//	len(mockedQuerier.UpsertCommunityThemeRollupCalls())
func (mock *QuerierMock) UpsertCommunityThemeRollupCalls() []struct {
	Ctx context.Context
	Arg db.UpsertCommunityThemeRollupParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertCommunityThemeRollupParams
	}
	mock.lockUpsertCommunityThemeRollup.RLock()
	calls = mock.calls.UpsertCommunityThemeRollup
	mock.lockUpsertCommunityThemeRollup.RUnlock()
	return calls
}

// UpsertJournalCommunityProjection calls UpsertJournalCommunityProjectionFunc.
func (mock *QuerierMock) UpsertJournalCommunityProjection(ctx context.Context, arg db.UpsertJournalCommunityProjectionParams) (db.SourceJournalCommunityProjection, error) {
	if mock.UpsertJournalCommunityProjectionFunc == nil {
		panic("QuerierMock.UpsertJournalCommunityProjectionFunc: method is nil but Querier.UpsertJournalCommunityProjection was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertJournalCommunityProjectionParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertJournalCommunityProjection.Lock()
	mock.calls.UpsertJournalCommunityProjection = append(mock.calls.UpsertJournalCommunityProjection, callInfo)
	mock.lockUpsertJournalCommunityProjection.Unlock()
	return mock.UpsertJournalCommunityProjectionFunc(ctx, arg)
}

// UpsertJournalCommunityProjectionCalls gets all the calls that were made to UpsertJournalCommunityProjection.
// Check the length with:
//
//	len(mockedQuerier.UpsertJournalCommunityProjectionCalls())
func (mock *QuerierMock) UpsertJournalCommunityProjectionCalls() []struct {
	Ctx context.Context
	Arg db.UpsertJournalCommunityProjectionParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertJournalCommunityProjectionParams
	}
	mock.lockUpsertJournalCommunityProjection.RLock()
	calls = mock.calls.UpsertJournalCommunityProjection
	mock.lockUpsertJournalCommunityProjection.RUnlock()
	return calls
}

// UpsertRuntimeConfigValue calls UpsertRuntimeConfigValueFunc.
func (mock *QuerierMock) UpsertRuntimeConfigValue(ctx context.Context, arg db.UpsertRuntimeConfigValueParams) (db.SourceRuntimeConfig, error) {
	if mock.UpsertRuntimeConfigValueFunc == nil {
		panic("QuerierMock.UpsertRuntimeConfigValueFunc: method is nil but Querier.UpsertRuntimeConfigValue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertRuntimeConfigValueParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertRuntimeConfigValue.Lock()
	mock.calls.UpsertRuntimeConfigValue = append(mock.calls.UpsertRuntimeConfigValue, callInfo)
	mock.lockUpsertRuntimeConfigValue.Unlock()
	return mock.UpsertRuntimeConfigValueFunc(ctx, arg)
}

// UpsertRuntimeConfigValueCalls gets all the calls that were made to UpsertRuntimeConfigValue.
// Check the length with:
//
//	len(mockedQuerier.UpsertRuntimeConfigValueCalls())
func (mock *QuerierMock) UpsertRuntimeConfigValueCalls() []struct {
	Ctx context.Context
	Arg db.UpsertRuntimeConfigValueParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertRuntimeConfigValueParams
	}
	mock.lockUpsertRuntimeConfigValue.RLock()
	calls = mock.calls.UpsertRuntimeConfigValue
	mock.lockUpsertRuntimeConfigValue.RUnlock()
	return calls
}

// UpsertUserGameBalance calls UpsertUserGameBalanceFunc.
func (mock *QuerierMock) UpsertUserGameBalance(ctx context.Context, arg db.UpsertUserGameBalanceParams) (db.SourceUserGameBalance, error) {
	if mock.UpsertUserGameBalanceFunc == nil {
		panic("QuerierMock.UpsertUserGameBalanceFunc: method is nil but Querier.UpsertUserGameBalance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertUserGameBalanceParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertUserGameBalance.Lock()
	mock.calls.UpsertUserGameBalance = append(mock.calls.UpsertUserGameBalance, callInfo)
	mock.lockUpsertUserGameBalance.Unlock()
	return mock.UpsertUserGameBalanceFunc(ctx, arg)
}

// UpsertUserGameBalanceCalls gets all the calls that were made to UpsertUserGameBalance.
// Check the length with:
//
//	len(mockedQuerier.UpsertUserGameBalanceCalls())
func (mock *QuerierMock) UpsertUserGameBalanceCalls() []struct {
	Ctx context.Context
	Arg db.UpsertUserGameBalanceParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertUserGameBalanceParams
	}
	mock.lockUpsertUserGameBalance.RLock()
	calls = mock.calls.UpsertUserGameBalance
	mock.lockUpsertUserGameBalance.RUnlock()
	return calls
}
