// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/community/community_service.proto

package community_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunityService_GetCommunityPulse_FullMethodName   = "/community.CommunityService/GetCommunityPulse"
	CommunityService_GetTodayTogether_FullMethodName    = "/community.CommunityService/GetTodayTogether"
	CommunityService_GetCommunityPrompts_FullMethodName = "/community.CommunityService/GetCommunityPrompts"
)

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunityServiceClient interface {
	GetCommunityPulse(ctx context.Context, in *GetCommunityPulseRequest, opts ...grpc.CallOption) (*GetCommunityPulseResponse, error)
	GetTodayTogether(ctx context.Context, in *GetTodayTogetherRequest, opts ...grpc.CallOption) (*GetTodayTogetherResponse, error)
	GetCommunityPrompts(ctx context.Context, in *GetCommunityPromptsRequest, opts ...grpc.CallOption) (*GetCommunityPromptsResponse, error)
}

type communityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunityServiceClient(cc grpc.ClientConnInterface) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) GetCommunityPulse(ctx context.Context, in *GetCommunityPulseRequest, opts ...grpc.CallOption) (*GetCommunityPulseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommunityPulseResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetCommunityPulse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetTodayTogether(ctx context.Context, in *GetTodayTogetherRequest, opts ...grpc.CallOption) (*GetTodayTogetherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodayTogetherResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetTodayTogether_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetCommunityPrompts(ctx context.Context, in *GetCommunityPromptsRequest, opts ...grpc.CallOption) (*GetCommunityPromptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommunityPromptsResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetCommunityPrompts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
// All implementations should embed UnimplementedCommunityServiceServer
// for forward compatibility.
type CommunityServiceServer interface {
	GetCommunityPulse(context.Context, *GetCommunityPulseRequest) (*GetCommunityPulseResponse, error)
	GetTodayTogether(context.Context, *GetTodayTogetherRequest) (*GetTodayTogetherResponse, error)
	GetCommunityPrompts(context.Context, *GetCommunityPromptsRequest) (*GetCommunityPromptsResponse, error)
}

// UnimplementedCommunityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunityServiceServer struct{}

func (UnimplementedCommunityServiceServer) GetCommunityPulse(context.Context, *GetCommunityPulseRequest) (*GetCommunityPulseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommunityPulse not implemented")
}
func (UnimplementedCommunityServiceServer) GetTodayTogether(context.Context, *GetTodayTogetherRequest) (*GetTodayTogetherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodayTogether not implemented")
}
func (UnimplementedCommunityServiceServer) GetCommunityPrompts(context.Context, *GetCommunityPromptsRequest) (*GetCommunityPromptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommunityPrompts not implemented")
}
func (UnimplementedCommunityServiceServer) testEmbeddedByValue() {}

// UnsafeCommunityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunityServiceServer will
// result in compilation errors.
type UnsafeCommunityServiceServer interface {
	mustEmbedUnimplementedCommunityServiceServer()
}

func RegisterCommunityServiceServer(s grpc.ServiceRegistrar, srv CommunityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommunityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunityService_ServiceDesc, srv)
}

func _CommunityService_GetCommunityPulse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommunityPulseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetCommunityPulse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetCommunityPulse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetCommunityPulse(ctx, req.(*GetCommunityPulseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetTodayTogether_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayTogetherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetTodayTogether(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetTodayTogether_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetTodayTogether(ctx, req.(*GetTodayTogetherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetCommunityPrompts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommunityPromptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetCommunityPrompts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetCommunityPrompts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetCommunityPrompts(ctx, req.(*GetCommunityPromptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunityService_ServiceDesc is the grpc.ServiceDesc for CommunityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "community.CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommunityPulse",
			Handler:    _CommunityService_GetCommunityPulse_Handler,
		},
		{
			MethodName: "GetTodayTogether",
			Handler:    _CommunityService_GetTodayTogether_Handler,
		},
		{
			MethodName: "GetCommunityPrompts",
			Handler:    _CommunityService_GetCommunityPrompts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/community/community_service.proto",
}
