// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/util/util_service.proto

package util_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UtilService_GenerateRandomString_FullMethodName = "/util.UtilService/GenerateRandomString"
)

// UtilServiceClient is the client API for UtilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UtilServiceClient interface {
	GenerateRandomString(ctx context.Context, in *GenerateRandomStringRequest, opts ...grpc.CallOption) (*GenerateRandomStringResponse, error)
}

type utilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUtilServiceClient(cc grpc.ClientConnInterface) UtilServiceClient {
	return &utilServiceClient{cc}
}

func (c *utilServiceClient) GenerateRandomString(ctx context.Context, in *GenerateRandomStringRequest, opts ...grpc.CallOption) (*GenerateRandomStringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRandomStringResponse)
	err := c.cc.Invoke(ctx, UtilService_GenerateRandomString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UtilServiceServer is the server API for UtilService service.
// All implementations should embed UnimplementedUtilServiceServer
// for forward compatibility.
type UtilServiceServer interface {
	GenerateRandomString(context.Context, *GenerateRandomStringRequest) (*GenerateRandomStringResponse, error)
}

// UnimplementedUtilServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUtilServiceServer struct{}

func (UnimplementedUtilServiceServer) GenerateRandomString(context.Context, *GenerateRandomStringRequest) (*GenerateRandomStringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRandomString not implemented")
}
func (UnimplementedUtilServiceServer) testEmbeddedByValue() {}

// UnsafeUtilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UtilServiceServer will
// result in compilation errors.
type UnsafeUtilServiceServer interface {
	mustEmbedUnimplementedUtilServiceServer()
}

func RegisterUtilServiceServer(s grpc.ServiceRegistrar, srv UtilServiceServer) {
	// If the following call pancis, it indicates UnimplementedUtilServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UtilService_ServiceDesc, srv)
}

func _UtilService_GenerateRandomString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRandomStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServiceServer).GenerateRandomString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UtilService_GenerateRandomString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServiceServer).GenerateRandomString(ctx, req.(*GenerateRandomStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UtilService_ServiceDesc is the grpc.ServiceDesc for UtilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UtilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "util.UtilService",
	HandlerType: (*UtilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRandomString",
			Handler:    _UtilService_GenerateRandomString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/util/util_service.proto",
}
