// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: proto/util/util.proto

package util_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRandomStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateRandomStringRequest) Reset() {
	*x = GenerateRandomStringRequest{}
	mi := &file_proto_util_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomStringRequest) ProtoMessage() {}

func (x *GenerateRandomStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_util_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomStringRequest.ProtoReflect.Descriptor instead.
func (*GenerateRandomStringRequest) Descriptor() ([]byte, []int) {
	return file_proto_util_util_proto_rawDescGZIP(), []int{0}
}

type GenerateRandomStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomString string `protobuf:"bytes,1,opt,name=random_string,json=randomString,proto3" json:"random_string,omitempty"`
}

func (x *GenerateRandomStringResponse) Reset() {
	*x = GenerateRandomStringResponse{}
	mi := &file_proto_util_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomStringResponse) ProtoMessage() {}

func (x *GenerateRandomStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_util_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomStringResponse.ProtoReflect.Descriptor instead.
func (*GenerateRandomStringResponse) Descriptor() ([]byte, []int) {
	return file_proto_util_util_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRandomStringResponse) GetRandomString() string {
	if x != nil {
		return x.RandomString
	}
	return ""
}

var File_proto_util_util_proto protoreflect.FileDescriptor

var file_proto_util_util_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69, 0x6c, 0x22, 0x1d, 0x0a,
	0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x1c,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x79, 0x61, 0x62, 0x6c, 0x6f, 0x6e, 0x73, 0x6b, 0x69, 0x2f, 0x6c, 0x6f, 0x74, 0x75, 0x73,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x3b, 0x75, 0x74, 0x69, 0x6c, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_util_util_proto_rawDescOnce sync.Once
	file_proto_util_util_proto_rawDescData = file_proto_util_util_proto_rawDesc
)

func file_proto_util_util_proto_rawDescGZIP() []byte {
	file_proto_util_util_proto_rawDescOnce.Do(func() {
		file_proto_util_util_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_util_util_proto_rawDescData)
	})
	return file_proto_util_util_proto_rawDescData
}

var file_proto_util_util_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_util_util_proto_goTypes = []any{
	(*GenerateRandomStringRequest)(nil),  // 0: util.GenerateRandomStringRequest
	(*GenerateRandomStringResponse)(nil), // 1: util.GenerateRandomStringResponse
}
var file_proto_util_util_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_util_util_proto_init() }
func file_proto_util_util_proto_init() {
	if File_proto_util_util_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_util_util_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_util_util_proto_goTypes,
		DependencyIndexes: file_proto_util_util_proto_depIdxs,
		MessageInfos:      file_proto_util_util_proto_msgTypes,
	}.Build()
	File_proto_util_util_proto = out.File
	file_proto_util_util_proto_rawDesc = nil
	file_proto_util_util_proto_goTypes = nil
	file_proto_util_util_proto_depIdxs = nil
}
