name: "analytics"
version: "1.0.0"

profile: "analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +on_schema_change: "sync_all_columns"

  analytics:
    silver:
      staging:
        +group: staging
        +schema: silver
      core:
        +group: core
        +schema: silver

    gold:
      +schema: gold
      analytics:
        +group: analytics

sources:
  analytics:
    +group: sources
