# pasting this here for dagster
analytics:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: dev
