#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/docker/db/ci_source_schema.sql"
TEMP_FILE="${OUTPUT_FILE}.tmp"
TEMP_DB="dbt_schema_gen"

started_postgres=0

cleanup() {
  if [[ "${started_postgres}" -eq 1 ]]; then
    (cd "${ROOT_DIR}" && make stop-postgres >/dev/null 2>&1 || true)
  fi
}

trap cleanup EXIT

if ! docker ps --format '{{.Names}}' | grep -qx "postgres"; then
  (cd "${ROOT_DIR}" && make start-postgres)
  started_postgres=1
fi

until docker exec postgres pg_isready -U postgres -d postgres >/dev/null 2>&1; do
  echo "Waiting for postgres to become ready..."
  sleep 1
done

docker exec -i postgres psql -v ON_ERROR_STOP=1 -U postgres -d postgres <<SQL
DROP DATABASE IF EXISTS ${TEMP_DB};
CREATE DATABASE ${TEMP_DB};
SQL

docker exec -i postgres psql -v ON_ERROR_STOP=1 -U postgres -d "${TEMP_DB}" <<'SQL'
CREATE SCHEMA IF NOT EXISTS source;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector SCHEMA public;
SQL

(
  cd "${ROOT_DIR}/services/django"
  if command -v uv >/dev/null 2>&1; then
    DB_NAME="${TEMP_DB}" \
    DB_USER="postgres" \
    DB_PASSWORD="postgres" \
    DB_HOST="localhost" \
    DB_PORT="5432" \
    uv run python manage.py migrate --noinput
  elif [[ -x ".venv/bin/python" ]]; then
    DB_NAME="${TEMP_DB}" \
    DB_USER="postgres" \
    DB_PASSWORD="postgres" \
    DB_HOST="localhost" \
    DB_PORT="5432" \
    .venv/bin/python manage.py migrate --noinput
  else
    echo "uv is not installed and services/django/.venv/bin/python was not found." >&2
    exit 1
  fi
)

table_args=()
for source_file in "${ROOT_DIR}"/services/dbt/models/sources/application_db/*.yml; do
  table_name="$(basename "${source_file}" .yml)"
  table_args+=(--table="source.${table_name}")
done

docker exec postgres pg_dump \
  -U postgres \
  -d "${TEMP_DB}" \
  --schema-only \
  --no-owner \
  --no-privileges \
  "${table_args[@]}" \
  | sed '/^-- Dumped from database version /d; /^-- Dumped by pg_dump version /d; /^\\restrict /d; /^\\unrestrict /d' \
  > "${TEMP_FILE}"

cat >"${OUTPUT_FILE}" <<'SQL'
-- Generated by scripts/generate-dbt-source-schema.sh
-- Source of truth: Django migrations in services/django/core/migrations
-- Do not hand-edit this file.

SQL

cat "${TEMP_FILE}" >> "${OUTPUT_FILE}"
rm -f "${TEMP_FILE}"

docker exec -i postgres psql -v ON_ERROR_STOP=1 -U postgres -d postgres <<SQL
DROP DATABASE IF EXISTS ${TEMP_DB};
SQL

echo "Generated ${OUTPUT_FILE}"
