// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: proto/journal/journal.proto

package journal_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJournalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JournalText string `protobuf:"bytes,2,opt,name=journal_text,json=journalText,proto3" json:"journal_text,omitempty"`
	UserMood    string `protobuf:"bytes,3,opt,name=user_mood,json=userMood,proto3" json:"user_mood,omitempty"`
}

func (x *CreateJournalRequest) Reset() {
	*x = CreateJournalRequest{}
	mi := &file_proto_journal_journal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJournalRequest) ProtoMessage() {}

func (x *CreateJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJournalRequest.ProtoReflect.Descriptor instead.
func (*CreateJournalRequest) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJournalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateJournalRequest) GetJournalText() string {
	if x != nil {
		return x.JournalText
	}
	return ""
}

func (x *CreateJournalRequest) GetUserMood() string {
	if x != nil {
		return x.UserMood
	}
	return ""
}

type CreateJournalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalId string `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
}

func (x *CreateJournalResponse) Reset() {
	*x = CreateJournalResponse{}
	mi := &file_proto_journal_journal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJournalResponse) ProtoMessage() {}

func (x *CreateJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJournalResponse.ProtoReflect.Descriptor instead.
func (*CreateJournalResponse) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJournalResponse) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

type GetJournalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // optional - defaults to 50 if not provided
	Offset int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // optional - defaults to 0 if not provided
}

func (x *GetJournalsRequest) Reset() {
	*x = GetJournalsRequest{}
	mi := &file_proto_journal_journal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalsRequest) ProtoMessage() {}

func (x *GetJournalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalsRequest.ProtoReflect.Descriptor instead.
func (*GetJournalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{2}
}

func (x *GetJournalsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetJournalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetJournalsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type JournalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalId   string   `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	UserId      string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JournalText string   `protobuf:"bytes,3,opt,name=journal_text,json=journalText,proto3" json:"journal_text,omitempty"`
	UserMood    string   `protobuf:"bytes,4,opt,name=user_mood,json=userMood,proto3" json:"user_mood,omitempty"`
	CreatedAt   string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TopicNames  []string `protobuf:"bytes,6,rep,name=topic_names,json=topicNames,proto3" json:"topic_names,omitempty"` // OpenAI-generated topic tags (async, may be empty)
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_proto_journal_journal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{3}
}

func (x *JournalEntry) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

func (x *JournalEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JournalEntry) GetJournalText() string {
	if x != nil {
		return x.JournalText
	}
	return ""
}

func (x *JournalEntry) GetUserMood() string {
	if x != nil {
		return x.UserMood
	}
	return ""
}

func (x *JournalEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *JournalEntry) GetTopicNames() []string {
	if x != nil {
		return x.TopicNames
	}
	return nil
}

type GetJournalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Journals   []*JournalEntry `protobuf:"bytes,1,rep,name=journals,proto3" json:"journals,omitempty"`
	TotalCount int64           `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // total number of journals for this user
	HasMore    bool            `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // true if there are more results beyond this page
}

func (x *GetJournalsResponse) Reset() {
	*x = GetJournalsResponse{}
	mi := &file_proto_journal_journal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalsResponse) ProtoMessage() {}

func (x *GetJournalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalsResponse.ProtoReflect.Descriptor instead.
func (*GetJournalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{4}
}

func (x *GetJournalsResponse) GetJournals() []*JournalEntry {
	if x != nil {
		return x.Journals
	}
	return nil
}

func (x *GetJournalsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetJournalsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TriggerAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalId string `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
}

func (x *TriggerAnalysisRequest) Reset() {
	*x = TriggerAnalysisRequest{}
	mi := &file_proto_journal_journal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAnalysisRequest) ProtoMessage() {}

func (x *TriggerAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAnalysisRequest.ProtoReflect.Descriptor instead.
func (*TriggerAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerAnalysisRequest) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

type TriggerAnalysisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TriggerAnalysisResponse) Reset() {
	*x = TriggerAnalysisResponse{}
	mi := &file_proto_journal_journal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAnalysisResponse) ProtoMessage() {}

func (x *TriggerAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAnalysisResponse.ProtoReflect.Descriptor instead.
func (*TriggerAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerAnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchJournalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // optional - defaults to 20 if not provided
}

func (x *SearchJournalsRequest) Reset() {
	*x = SearchJournalsRequest{}
	mi := &file_proto_journal_journal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJournalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJournalsRequest) ProtoMessage() {}

func (x *SearchJournalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJournalsRequest.ProtoReflect.Descriptor instead.
func (*SearchJournalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{7}
}

func (x *SearchJournalsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchJournalsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchJournalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchJournalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*JournalSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchJournalsResponse) Reset() {
	*x = SearchJournalsResponse{}
	mi := &file_proto_journal_journal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJournalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJournalsResponse) ProtoMessage() {}

func (x *SearchJournalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJournalsResponse.ProtoReflect.Descriptor instead.
func (*SearchJournalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{8}
}

func (x *SearchJournalsResponse) GetResults() []*JournalSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type JournalSearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Journal         *JournalEntry `protobuf:"bytes,1,opt,name=journal,proto3" json:"journal,omitempty"`
	SimilarityScore float32       `protobuf:"fixed32,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
}

func (x *JournalSearchResult) Reset() {
	*x = JournalSearchResult{}
	mi := &file_proto_journal_journal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalSearchResult) ProtoMessage() {}

func (x *JournalSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_journal_journal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalSearchResult.ProtoReflect.Descriptor instead.
func (*JournalSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_journal_journal_proto_rawDescGZIP(), []int{9}
}

func (x *JournalSearchResult) GetJournal() *JournalEntry {
	if x != nil {
		return x.Journal
	}
	return nil
}

func (x *JournalSearchResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

var File_proto_journal_journal_proto protoreflect.FileDescriptor

var file_proto_journal_journal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x6f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6f, 0x64, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22,
	0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xc6, 0x01, 0x0a,
	0x0c, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4d, 0x6f, 0x6f, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22, 0x37, 0x0a, 0x16,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x17, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f,
	0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x50, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0x71, 0x0a, 0x13, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x6a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x10,
	0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x79, 0x61, 0x62, 0x6c, 0x6f, 0x6e, 0x73, 0x6b, 0x69,
	0x2f, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x3b, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_journal_journal_proto_rawDescOnce sync.Once
	file_proto_journal_journal_proto_rawDescData = file_proto_journal_journal_proto_rawDesc
)

func file_proto_journal_journal_proto_rawDescGZIP() []byte {
	file_proto_journal_journal_proto_rawDescOnce.Do(func() {
		file_proto_journal_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_journal_journal_proto_rawDescData)
	})
	return file_proto_journal_journal_proto_rawDescData
}

var file_proto_journal_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_journal_journal_proto_goTypes = []any{
	(*CreateJournalRequest)(nil),    // 0: journal.CreateJournalRequest
	(*CreateJournalResponse)(nil),   // 1: journal.CreateJournalResponse
	(*GetJournalsRequest)(nil),      // 2: journal.GetJournalsRequest
	(*JournalEntry)(nil),            // 3: journal.JournalEntry
	(*GetJournalsResponse)(nil),     // 4: journal.GetJournalsResponse
	(*TriggerAnalysisRequest)(nil),  // 5: journal.TriggerAnalysisRequest
	(*TriggerAnalysisResponse)(nil), // 6: journal.TriggerAnalysisResponse
	(*SearchJournalsRequest)(nil),   // 7: journal.SearchJournalsRequest
	(*SearchJournalsResponse)(nil),  // 8: journal.SearchJournalsResponse
	(*JournalSearchResult)(nil),     // 9: journal.JournalSearchResult
}
var file_proto_journal_journal_proto_depIdxs = []int32{
	3, // 0: journal.GetJournalsResponse.journals:type_name -> journal.JournalEntry
	9, // 1: journal.SearchJournalsResponse.results:type_name -> journal.JournalSearchResult
	3, // 2: journal.JournalSearchResult.journal:type_name -> journal.JournalEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_journal_journal_proto_init() }
func file_proto_journal_journal_proto_init() {
	if File_proto_journal_journal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_journal_journal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_journal_journal_proto_goTypes,
		DependencyIndexes: file_proto_journal_journal_proto_depIdxs,
		MessageInfos:      file_proto_journal_journal_proto_msgTypes,
	}.Build()
	File_proto_journal_journal_proto = out.File
	file_proto_journal_journal_proto_rawDesc = nil
	file_proto_journal_journal_proto_goTypes = nil
	file_proto_journal_journal_proto_depIdxs = nil
}
