// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type SourceUser struct {
	ID         int32
	Username   string
	Password   string
	Email      string
	Salt       string
	Role       string
	CreatedAt  time.Time
	ModifiedAt time.Time
	Timezone   string
}
