// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type SourceUser struct {
	ID         uuid.UUID
	Email      string
	Password   string
	Salt       string
	Role       string
	CreatedAt  time.Time
	ModifiedAt time.Time
	Timezone   string
}
