// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type SourceJournal struct {
	ID          int32
	UserID      uuid.UUID
	JournalText string
	MoodScore   sql.NullInt32
	CreatedAt   time.Time
	ModifiedAt  time.Time
}

type SourceUser struct {
	ID         uuid.UUID
	Email      string
	Password   string
	Salt       string
	Role       string
	CreatedAt  time.Time
	ModifiedAt time.Time
	Timezone   string
}
