// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/game/game_service.proto

package game_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetGameBalance_FullMethodName    = "/game.GameService/GetGameBalance"
	GameService_UpdateGameBalance_FullMethodName = "/game.GameService/UpdateGameBalance"
	GameService_RecordBets_FullMethodName        = "/game.GameService/RecordBets"
	GameService_GetBetHistory_FullMethodName     = "/game.GameService/GetBetHistory"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	GetGameBalance(ctx context.Context, in *GetGameBalanceRequest, opts ...grpc.CallOption) (*GetGameBalanceResponse, error)
	UpdateGameBalance(ctx context.Context, in *UpdateGameBalanceRequest, opts ...grpc.CallOption) (*UpdateGameBalanceResponse, error)
	RecordBets(ctx context.Context, in *RecordBetsRequest, opts ...grpc.CallOption) (*RecordBetsResponse, error)
	GetBetHistory(ctx context.Context, in *GetBetHistoryRequest, opts ...grpc.CallOption) (*GetBetHistoryResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetGameBalance(ctx context.Context, in *GetGameBalanceRequest, opts ...grpc.CallOption) (*GetGameBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameBalanceResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameBalance(ctx context.Context, in *UpdateGameBalanceRequest, opts ...grpc.CallOption) (*UpdateGameBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameBalanceResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGameBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RecordBets(ctx context.Context, in *RecordBetsRequest, opts ...grpc.CallOption) (*RecordBetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordBetsResponse)
	err := c.cc.Invoke(ctx, GameService_RecordBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetBetHistory(ctx context.Context, in *GetBetHistoryRequest, opts ...grpc.CallOption) (*GetBetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBetHistoryResponse)
	err := c.cc.Invoke(ctx, GameService_GetBetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations should embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	GetGameBalance(context.Context, *GetGameBalanceRequest) (*GetGameBalanceResponse, error)
	UpdateGameBalance(context.Context, *UpdateGameBalanceRequest) (*UpdateGameBalanceResponse, error)
	RecordBets(context.Context, *RecordBetsRequest) (*RecordBetsResponse, error)
	GetBetHistory(context.Context, *GetBetHistoryRequest) (*GetBetHistoryResponse, error)
}

// UnimplementedGameServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetGameBalance(context.Context, *GetGameBalanceRequest) (*GetGameBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameBalance not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameBalance(context.Context, *UpdateGameBalanceRequest) (*UpdateGameBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGameBalance not implemented")
}
func (UnimplementedGameServiceServer) RecordBets(context.Context, *RecordBetsRequest) (*RecordBetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordBets not implemented")
}
func (UnimplementedGameServiceServer) GetBetHistory(context.Context, *GetBetHistoryRequest) (*GetBetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBetHistory not implemented")
}
func (UnimplementedGameServiceServer) testEmbeddedByValue() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetGameBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameBalance(ctx, req.(*GetGameBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGameBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameBalance(ctx, req.(*UpdateGameBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_RecordBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).RecordBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_RecordBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).RecordBets(ctx, req.(*RecordBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetBetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetBetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetBetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetBetHistory(ctx, req.(*GetBetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameBalance",
			Handler:    _GameService_GetGameBalance_Handler,
		},
		{
			MethodName: "UpdateGameBalance",
			Handler:    _GameService_UpdateGameBalance_Handler,
		},
		{
			MethodName: "RecordBets",
			Handler:    _GameService_RecordBets_Handler,
		},
		{
			MethodName: "GetBetHistory",
			Handler:    _GameService_GetBetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game/game_service.proto",
}
