name: Analyzer CI / CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "services/analyzer/**"
      - "services/experiments/**"
      - ".github/workflows/analyzer.yaml"
  pull_request:
    paths:
      - "services/analyzer/**"
      - "services/experiments/**"
      - ".github/workflows/analyzer.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_VERSION: "0.10.9"
  PYTHON_VERSION: "3.13"

jobs:
  analyzer-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            services/analyzer/**
            services/experiments/**
            docker/**
            Makefile
          sparse-checkout-cone-mode: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/analyzer

      - name: Run analyzer tests
        env:
          ANALYZER_API_KEY: test-key
        run: make test-analyzer
