name: Backend CI / CD Pipeline

on:
  pull_request:
    paths:
      - 'services/backend/**'

jobs:
  backend-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
              services/backend/**
              docker/**
              Makefile
          sparse-checkout-cone-mode: false
          # needed to checkout only a single file

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: |
               services/backend/go.sum

      - name: Start Postgres
        run: make start-postgres
     
      - name: Run Backend Tests
        working-directory: services/backend
        run: |
          go test ./... -v -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | sort -k3 -nr
          echo "=== Coverage Summary ==="
          go tool cover -func=coverage.out | tail -n 1

      - name: Stop Postgres
        run: make stop-postgres
