name: Backend CI / CD Pipeline

on:
  pull_request:
    paths:
      - 'services/backend/**'

jobs:
  backend-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
              'services/backend/**'
              'docker/**'
              'Makefile'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: |
               services/backend/go.sum

      - name: Start Postgres
        run: make start-postgres
     
      - name: Run Go tests
        working-directory: backend
        run: go test ./... -v

      - name: Stop Postgres
        run: make stop-postgres
