name: Django CI / CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "services/django/**"
      - ".github/workflows/django.yaml"
  pull_request:
    paths:
      - "services/django/**"
      - ".github/workflows/django.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_VERSION: "0.10.9"
  PYTHON_VERSION: "3.13"

jobs:
  django-pipeline:
    runs-on: ubuntu-latest
    name: Test Suite

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            services/django/**
            services/dbt/models/sources/application_db/**
            docker/**
            scripts/generate-dbt-source-schema.sh
            Makefile
          sparse-checkout-cone-mode: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION}}
          enable-cache: true
          prune-cache: false
          working-directory: services/django

      - name: Start Services
        run: make start-postgres

      - name: Run Test Suite
        working-directory: services/django
        run: uv run pytest

      - name: Shutdown Services
        if: always()
        run: make stop-postgres
